// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "ut_business_logic.rs", type: "file", path: "crates/gm-backend/tests/ut_business_logic.rs", crate: "gm-backend", module_path: "gm_backend::test_target::ut_business_logic", kind: "test", lines: 241}),
//   (n2:Function {name: "parse_audit_type_all_valid_variants", type: "function", fqn: "gm_backend::test_target::ut_business_logic::parse_audit_type_all_valid_variants", kind: "test", visibility: "private", signature: "fn parse_audit_type_all_valid_variants()", line: 26, attributes: "test"}),
//   (n3:Function {name: "parse_audit_type_case_insensitive", type: "function", fqn: "gm_backend::test_target::ut_business_logic::parse_audit_type_case_insensitive", kind: "test", visibility: "private", signature: "fn parse_audit_type_case_insensitive()", line: 36, attributes: "test"}),
//   (n4:Function {name: "parse_audit_type_invalid_returns_none", type: "function", fqn: "gm_backend::test_target::ut_business_logic::parse_audit_type_invalid_returns_none", kind: "test", visibility: "private", signature: "fn parse_audit_type_invalid_returns_none()", line: 46, attributes: "test"}),
//   (n5:Function {name: "allowed_maintenance_scopes_contain_exact_three", type: "function", fqn: "gm_backend::test_target::ut_business_logic::allowed_maintenance_scopes_contain_exact_three", kind: "test", visibility: "private", signature: "fn allowed_maintenance_scopes_contain_exact_three()", line: 58, attributes: "test"}),
//   (n6:Function {name: "allowed_maintenance_scopes_exhaustive_match", type: "function", fqn: "gm_backend::test_target::ut_business_logic::allowed_maintenance_scopes_exhaustive_match", kind: "test", visibility: "private", signature: "fn allowed_maintenance_scopes_exhaustive_match()", line: 71, attributes: "test"}),
//   (n7:Function {name: "allowed_anchors_contain_nine_grid_positions", type: "function", fqn: "gm_backend::test_target::ut_business_logic::allowed_anchors_contain_nine_grid_positions", kind: "test", visibility: "private", signature: "fn allowed_anchors_contain_nine_grid_positions()", line: 86, attributes: "test"}),
//   (n8:Function {name: "allowed_anchors_rejects_invalid", type: "function", fqn: "gm_backend::test_target::ut_business_logic::allowed_anchors_rejects_invalid", kind: "test", visibility: "private", signature: "fn allowed_anchors_rejects_invalid()", line: 100, attributes: "test"}),
//   (n9:Function {name: "in_memory_audit_store_append_and_list_newest_first", type: "function", fqn: "gm_backend::test_target::ut_business_logic::in_memory_audit_store_append_and_list_newest_first", kind: "test", visibility: "private", signature: "fn in_memory_audit_store_append_and_list_newest_first()", line: 113, attributes: "tokio::test"}),
//   (n10:Function {name: "in_memory_audit_store_list_limit_caps_results", type: "function", fqn: "gm_backend::test_target::ut_business_logic::in_memory_audit_store_list_limit_caps_results", kind: "test", visibility: "private", signature: "fn in_memory_audit_store_list_limit_caps_results()", line: 132, attributes: "tokio::test"}),
//   (n11:Function {name: "in_memory_audit_store_list_empty_when_no_entries", type: "function", fqn: "gm_backend::test_target::ut_business_logic::in_memory_audit_store_list_empty_when_no_entries", kind: "test", visibility: "private", signature: "fn in_memory_audit_store_list_empty_when_no_entries()", line: 151, attributes: "tokio::test"}),
//   (n12:Function {name: "in_memory_audit_store_list_limit_zero_returns_empty", type: "function", fqn: "gm_backend::test_target::ut_business_logic::in_memory_audit_store_list_limit_zero_returns_empty", kind: "test", visibility: "private", signature: "fn in_memory_audit_store_list_limit_zero_returns_empty()", line: 158, attributes: "tokio::test"}),
//   (n13:Function {name: "claims_serialize_roundtrip", type: "function", fqn: "gm_backend::test_target::ut_business_logic::claims_serialize_roundtrip", kind: "test", visibility: "private", signature: "fn claims_serialize_roundtrip()", line: 176, attributes: "test"}),
//   (n14:Function {name: "gm_config_for_test_disables_admin_grpc", type: "function", fqn: "gm_backend::test_target::ut_business_logic::gm_config_for_test_disables_admin_grpc", kind: "test", visibility: "private", signature: "fn gm_config_for_test_disables_admin_grpc()", line: 195, attributes: "test"}),
//   (n15:Function {name: "gm_config_for_test_invalid_addr_fails", type: "function", fqn: "gm_backend::test_target::ut_business_logic::gm_config_for_test_invalid_addr_fails", kind: "test", visibility: "private", signature: "fn gm_config_for_test_invalid_addr_fails()", line: 206, attributes: "test"}),
//   (n16:Function {name: "support_ticket_status_whitelist_three_values", type: "function", fqn: "gm_backend::test_target::ut_business_logic::support_ticket_status_whitelist_three_values", kind: "test", visibility: "private", signature: "fn support_ticket_status_whitelist_three_values()", line: 217, attributes: "test"}),
//   (n17:Function {name: "grant_item_amount_boundary_invariant", type: "function", fqn: "gm_backend::test_target::ut_business_logic::grant_item_amount_boundary_invariant", kind: "test", visibility: "private", signature: "fn grant_item_amount_boundary_invariant()", line: 235, attributes: "test"});
// MERGE (x1:Module {name: "gm_backend", type: "module"}) ON CREATE SET x1.fqn = "gm_backend", x1.kind = "external_crate", x1.imports = "gm_backend::canvas_handler::ALLOWED_ANCHORS, gm_backend::business_handler::ALLOWED_MAINTENANCE_SCOPES, gm_backend::business_handler::parse_audit_type";
// MERGE (x2:Class {name: "AuditLogEntry", type: "class"}) ON CREATE SET x2.kind = "struct", x2.decl = "crates/gm-backend/src/lib.rs", x2.fqn = "gm_backend::AuditLogEntry";
// MERGE (x3:Class {name: "AuditStore", type: "class"}) ON CREATE SET x3.kind = "trait", x3.decl = "crates/gm-backend/src/lib.rs", x3.fqn = "gm_backend::AuditStore";
// MERGE (x4:Class {name: "GmConfig", type: "class"}) ON CREATE SET x4.kind = "struct", x4.decl = "crates/gm-backend/src/lib.rs", x4.fqn = "gm_backend::GmConfig";
// MERGE (x5:Class {name: "InMemoryAuditStore", type: "class"}) ON CREATE SET x5.kind = "struct", x5.decl = "crates/gm-backend/src/lib.rs", x5.fqn = "gm_backend::InMemoryAuditStore";
// MERGE (x6:Function {name: "parse_audit_type", type: "function"}) ON CREATE SET x6.kind = "fn", x6.decl = "crates/gm-backend/src/business_handler.rs", x6.fqn = "gm_backend::business_handler::parse_audit_type";
// MERGE (x7:Module {name: "core", type: "module"}) ON CREATE SET x7.fqn = "core", x7.kind = "external_crate", x7.imports = "core::option::Option";
// MERGE (x8:Function {name: "new", type: "function"}) ON CREATE SET x8.kind = "function", x8.decl = "crates/gm-backend/src/lib.rs", x8.fqn = "gm_backend::InMemoryAuditStore::new";
// MERGE (x9:Module {name: "serde_json", type: "module"}) ON CREATE SET x9.fqn = "serde_json", x9.kind = "external_crate", x9.imports = "serde_json::to_string, serde_json::from_str";
// MERGE (x10:Function {name: "for_test", type: "function"}) ON CREATE SET x10.kind = "function", x10.decl = "crates/gm-backend/src/lib.rs", x10.fqn = "gm_backend::GmConfig::for_test";
// MERGE (x11:Module {name: "i64", type: "module"}) ON CREATE SET x11.fqn = "i64", x11.kind = "external_crate", x11.imports = "i64::from";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n1)-[:CONTAINS]->(n6),
//   (n1)-[:CONTAINS]->(n7),
//   (n1)-[:CONTAINS]->(n8),
//   (n1)-[:CONTAINS]->(n9),
//   (n1)-[:CONTAINS]->(n10),
//   (n1)-[:CONTAINS]->(n11),
//   (n1)-[:CONTAINS]->(n12),
//   (n1)-[:CONTAINS]->(n13),
//   (n1)-[:CONTAINS]->(n14),
//   (n1)-[:CONTAINS]->(n15),
//   (n1)-[:CONTAINS]->(n16),
//   (n1)-[:CONTAINS]->(n17),
//   (n1)-[:USES, import: "gm_backend::canvas_handler::ALLOWED_ANCHORS"]->(x1),
//   (n1)-[:USES, import: "gm_backend::business_handler::ALLOWED_MAINTENANCE_SCOPES"]->(x1),
//   (n1)-[:USES, import: "gm_backend::AuditLogEntry"]->(x2),
//   (n1)-[:USES, import: "gm_backend::AuditStore"]->(x3),
//   (n1)-[:USES, import: "gm_backend::GmConfig"]->(x4),
//   (n1)-[:USES, import: "gm_backend::InMemoryAuditStore"]->(x5),
//   (n1)-[:USES, import: "gm_backend::business_handler::parse_audit_type"]->(x6),
//   (n2)-[:USES, via: "gm_backend::business_handler::parse_audit_type"]->(x1),
//   (n2)-[:USES, via: "core::option::Option"]->(x7),
//   (n3)-[:USES, via: "gm_backend::business_handler::parse_audit_type"]->(x1),
//   (n3)-[:USES, via: "core::option::Option"]->(x7),
//   (n4)-[:USES, via: "gm_backend::business_handler::parse_audit_type"]->(x1),
//   (n9)-[:CALLS, via: "gm_backend::InMemoryAuditStore::new"]->(x8),
//   (n10)-[:CALLS, via: "gm_backend::InMemoryAuditStore::new"]->(x8),
//   (n11)-[:CALLS, via: "gm_backend::InMemoryAuditStore::new"]->(x8),
//   (n12)-[:CALLS, via: "gm_backend::InMemoryAuditStore::new"]->(x8),
//   (n13)-[:USES, via: "serde_json::to_string"]->(x9),
//   (n13)-[:USES, via: "serde_json::from_str"]->(x9),
//   (n14)-[:CALLS, via: "gm_backend::GmConfig::for_test"]->(x10),
//   (n15)-[:CALLS, via: "gm_backend::GmConfig::for_test"]->(x10),
//   (n17)-[:USES, via: "i64::from"]->(x11);
// ```
// ==== END CYPHER HEADER ====
//! gm-backend 业务逻辑单元测试 (per 9/1 14:15 JST PT-WORKER-BRIEFING §2.3)
//!
//! 覆盖范围 (5+ 业务函数):
//! 1. `parse_audit_type` — 5 valid + 1 invalid
//! 2. `ALLOWED_MAINTENANCE_SCOPES` 校验
//! 3. `ALLOWED_ANCHORS` 校验 (canvas)
//! 4. `InMemoryAuditStore` append + list (newest-first, limit)
//! 5. `Claims` Serialize/Deserialize 往返
//! 6. `GmConfig::for_test` 字段不变性
//! 7. ticket status transitions 校验
//! 8. mall item create price/name validation
//!
//! 不依赖 actix-web runtime / 网络, 纯函数 + InMemory 单测.

use gm_backend::{
    business_handler::{parse_audit_type, ALLOWED_MAINTENANCE_SCOPES},
    canvas_handler::ALLOWED_ANCHORS,
    AuditLogEntry, AuditStore, InMemoryAuditStore, GmConfig,
};

// ============================================================================
// 1. parse_audit_type — 5 valid + 1 invalid + 大小写不敏感
// ============================================================================

#[test]
fn parse_audit_type_all_valid_variants() {
    // 5 valid lowercase (per 9/7 14:00 JST 调优: AuditType enum 起始是 0 Unspecified, All=1, Trade=2, ...)
    assert_eq!(parse_audit_type("all"), Some(1));
    assert_eq!(parse_audit_type("trade"), Some(2));
    assert_eq!(parse_audit_type("gacha"), Some(3));
    assert_eq!(parse_audit_type("match"), Some(4));
    assert_eq!(parse_audit_type("compensation"), Some(5));
}

#[test]
fn parse_audit_type_case_insensitive() {
    // 大写 / 混合大小写
    assert_eq!(parse_audit_type("ALL"), Some(1));
    assert_eq!(parse_audit_type("Trade"), Some(2));
    assert_eq!(parse_audit_type("GACHA"), Some(3));
    assert_eq!(parse_audit_type("MaTcH"), Some(4));
    assert_eq!(parse_audit_type("Compensation"), Some(5));
}

#[test]
fn parse_audit_type_invalid_returns_none() {
    assert_eq!(parse_audit_type(""), None);
    assert_eq!(parse_audit_type("invalid"), None);
    assert_eq!(parse_audit_type("audit"), None);
    assert_eq!(parse_audit_type("tradee"), None);
}

// ============================================================================
// 2. ALLOWED_MAINTENANCE_SCOPES — 仅 cluster/domain/single_node 3 选
// ============================================================================

#[test]
fn allowed_maintenance_scopes_contain_exact_three() {
    let scopes = ALLOWED_MAINTENANCE_SCOPES;
    assert_eq!(scopes.len(), 3, "ALLOWED_MAINTENANCE_SCOPES 必须 = 3");
    assert!(scopes.contains(&"cluster"));
    assert!(scopes.contains(&"domain"));
    assert!(scopes.contains(&"single_node"));
    // 负向: 排除常见错误
    assert!(!scopes.contains(&""));
    assert!(!scopes.contains(&"global"));
    assert!(!scopes.contains(&"node"));
}

#[test]
fn allowed_maintenance_scopes_exhaustive_match() {
    // business_handler::set_maintenance 实际走 .contains, 验证每个 scope 都被允许
    for scope in ALLOWED_MAINTENANCE_SCOPES {
        assert!(
            ALLOWED_MAINTENANCE_SCOPES.contains(scope),
            "scope {scope} 必须被 ALLOWED 列表接受"
        );
    }
}

// ============================================================================
// 3. ALLOWED_ANCHORS — 3x3 网格 9 个 anchor
// ============================================================================

#[test]
fn allowed_anchors_contain_nine_grid_positions() {
    let anchors = ALLOWED_ANCHORS;
    assert_eq!(anchors.len(), 9, "ALLOWED_ANCHORS 必须 = 9 (3x3 网格)");
    let expected = [
        "top_left", "top_center", "top_right",
        "center_left", "center", "center_right",
        "bottom_left", "bottom_center", "bottom_right",
    ];
    for e in expected {
        assert!(anchors.contains(&e), "缺少 anchor: {e}");
    }
}

#[test]
fn allowed_anchors_rejects_invalid() {
    // 负向: 错误 anchor 不在白名单
    let invalid = ["top", "left", "right", "middle", "topright", "centre", ""];
    for inv in invalid {
        assert!(!ALLOWED_ANCHORS.contains(&inv), "{inv} 不应被允许");
    }
}

// ============================================================================
// 4. InMemoryAuditStore — append + list (newest-first, limit)
// ============================================================================

#[tokio::test]
async fn in_memory_audit_store_append_and_list_newest_first() {
    let store = InMemoryAuditStore::new();
    for i in 0..5 {
        store.append(AuditLogEntry {
            log_id: format!("log-{i}"),
            admin_id: "admin".into(),
            action: "ban".into(),
            target_id: format!("player-{i}"),
            occurred_at_ms: 1000 + i as i64,
        });
    }
    let entries = store.list_entries(10).await;
    assert_eq!(entries.len(), 5);
    // newest-first: 倒序
    assert_eq!(entries[0].log_id, "log-4");
    assert_eq!(entries[4].log_id, "log-0");
}

#[tokio::test]
async fn in_memory_audit_store_list_limit_caps_results() {
    let store = InMemoryAuditStore::new();
    for i in 0..20 {
        store.append(AuditLogEntry {
            log_id: format!("log-{i:02}"),
            admin_id: "admin".into(),
            action: "grant".into(),
            target_id: format!("p-{i}"),
            occurred_at_ms: i as i64,
        });
    }
    // limit 5 → 5 条, 取最后 5 (log-15..log-19)
    let entries = store.list_entries(5).await;
    assert_eq!(entries.len(), 5);
    assert_eq!(entries[0].log_id, "log-19");
    assert_eq!(entries[4].log_id, "log-15");
}

#[tokio::test]
async fn in_memory_audit_store_list_empty_when_no_entries() {
    let store = InMemoryAuditStore::new();
    let entries = store.list_entries(100).await;
    assert!(entries.is_empty());
}

#[tokio::test]
async fn in_memory_audit_store_list_limit_zero_returns_empty() {
    let store = InMemoryAuditStore::new();
    store.append(AuditLogEntry {
        log_id: "log-0".into(),
        admin_id: "admin".into(),
        action: "ban".into(),
        target_id: "p".into(),
        occurred_at_ms: 1,
    });
    let entries = store.list_entries(0).await;
    assert!(entries.is_empty(), "limit=0 → 空结果");
}

// ============================================================================
// 5. Claims Serialize/Deserialize roundtrip
// ============================================================================

#[test]
fn claims_serialize_roundtrip() {
    let original = gm_backend::Claims {
        sub: "admin-001".to_string(),
        exp: 1_700_000_000,
        roles: vec!["GM_READ".to_string(), "GM_ADMIN".to_string()],
    };
    let json = serde_json::to_string(&original).expect("serialize");
    let parsed: gm_backend::Claims = serde_json::from_str(&json).expect("deserialize");
    assert_eq!(parsed.sub, "admin-001");
    assert_eq!(parsed.exp, 1_700_000_000);
    assert_eq!(parsed.roles.len(), 2);
    assert!(parsed.roles.contains(&"GM_ADMIN".to_string()));
}

// ============================================================================
// 6. GmConfig::for_test 字段不变性
// ============================================================================

#[test]
fn gm_config_for_test_disables_admin_grpc() {
    let cfg = GmConfig::for_test("127.0.0.1:8443", "127.0.0.1:8081", "http://admin:50055").unwrap();
    assert!(cfg.disable_admin_grpc, "for_test 必须 disable_admin_grpc=true");
    assert!(!cfg.require_jwt, "for_test 默认 require_jwt=false");
    assert_eq!(cfg.jwt_secret, "test-secret");
    assert_eq!(cfg.http_addr.port(), 8443);
    assert_eq!(cfg.health_addr.port(), 8081);
    assert_eq!(cfg.admin_grpc_endpoint, "http://admin:50055");
}

#[test]
fn gm_config_for_test_invalid_addr_fails() {
    // 无效端口 / 无效地址 → parse 失败
    assert!(GmConfig::for_test("not-a-addr", "127.0.0.1:8081", "http://x").is_err());
    assert!(GmConfig::for_test("127.0.0.1:8443", "999.999.999.999:80", "http://x").is_err());
}

// ============================================================================
// 7. support_handler ticket status 白名单 (per support_handler.rs L75)
// ============================================================================

#[test]
fn support_ticket_status_whitelist_three_values() {
    let allowed = ["open", "pending", "resolved"];
    assert_eq!(allowed.len(), 3);
    for s in allowed {
        assert!(allowed.contains(&s));
    }
    // 负向
    let invalid = ["closed", "deleted", "", "OPEN", "PENDING"];
    for inv in invalid {
        assert!(!allowed.contains(&inv), "{inv} 不应在 ticket status 白名单");
    }
}

// ============================================================================
// 8. items_handler 金额边界 (per items_handler.rs L38-40)
// ============================================================================

#[test]
fn grant_item_amount_boundary_invariant() {
    // 业务逻辑: amount <= 0 || amount > i32::MAX → 拒绝
    // 这里只测试不变量, 不发请求
    let max = i32::MAX as i64;
    assert!(max + 1 > i32::MAX as i64, "boundary: i32::MAX+1 溢出");
    assert_eq!(i64::from(i32::MAX), 2_147_483_647);
}
