// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "main.rs", type: "file", path: "tools/rgs-grpc-bridge/src/main.rs", crate: "rgs-grpc-bridge", module_path: "rgs_grpc_bridge", kind: "root", lines: 631}),
//   (n2:Module {name: "rgs_grpc_bridge", type: "module", fqn: "rgs_grpc_bridge", kind: "crate", package: "rgs-grpc-bridge"}),
//   (n3:Module {name: "pb_player_proto", type: "module", fqn: "rgs_grpc_bridge::pb_player_proto", kind: "inline"}),
//   (n4:Module {name: "v1", type: "module", fqn: "rgs_grpc_bridge::pb_player_proto::v1", kind: "inline"}),
//   (n5:Module {name: "common", type: "module", fqn: "rgs_grpc_bridge::common", kind: "inline"}),
//   (n6:Module {name: "v1", type: "module", fqn: "rgs_grpc_bridge::common::v1", kind: "inline"}),
//   (n7:Class {name: "BridgeConfig", type: "class", fqn: "rgs_grpc_bridge::BridgeConfig", kind: "struct", visibility: "private", line: 115, attributes: "derive"}),
//   (n8:Class {name: "BackendClient", type: "class", fqn: "rgs_grpc_bridge::BackendClient", kind: "struct", visibility: "private", line: 145, attributes: "derive"}),
//   (n9:Class {name: "ErrorBody", type: "class", fqn: "rgs_grpc_bridge::ErrorBody", kind: "struct", visibility: "private", line: 347, attributes: "derive"}),
//   (n10:Function {name: "from_env", type: "function", fqn: "rgs_grpc_bridge::BridgeConfig::from_env", kind: "method", visibility: "private", signature: "fn from_env() -> Self", line: 125}),
//   (n11:Function {name: "new", type: "function", fqn: "rgs_grpc_bridge::BackendClient::new", kind: "method", visibility: "private", signature: "fn new(cfg: BridgeConfig) -> Self", line: 151}),
//   (n12:Function {name: "get", type: "function", fqn: "rgs_grpc_bridge::BackendClient::get", kind: "method", visibility: "private", signature: "fn get(&self) -> Result<PlayerServiceClient<Channel>, tonic::Status>", line: 158}),
//   (n13:Function {name: "connect", type: "function", fqn: "rgs_grpc_bridge::connect", kind: "fn", visibility: "private", signature: "fn connect(cfg: &BridgeConfig) -> anyhow::Result<PlayerServiceClient<Channel>>", line: 172}),
//   (n14:Function {name: "extract_host", type: "function", fqn: "rgs_grpc_bridge::extract_host", kind: "fn", visibility: "private", signature: "fn extract_host(url: &str) -> String", line: 201}),
//   (n15:Function {name: "install_crypto_provider", type: "function", fqn: "rgs_grpc_bridge::install_crypto_provider", kind: "fn", visibility: "private", signature: "fn install_crypto_provider()", line: 208}),
//   (n16:Function {name: "json_to_create_character", type: "function", fqn: "rgs_grpc_bridge::json_to_create_character", kind: "fn", visibility: "private", signature: "fn json_to_create_character(v: &JsonValue) -> CreateCharacterRequest", line: 218}),
//   (n17:Function {name: "create_character_to_json", type: "function", fqn: "rgs_grpc_bridge::create_character_to_json", kind: "fn", visibility: "private", signature: "fn create_character_to_json(r: &CreateCharacterResponse) -> JsonValue", line: 232}),
//   (n18:Function {name: "json_to_login_character", type: "function", fqn: "rgs_grpc_bridge::json_to_login_character", kind: "fn", visibility: "private", signature: "fn json_to_login_character(v: &JsonValue) -> pb_player_proto::v1::LoginCharacterRequest", line: 243}),
//   (n19:Function {name: "login_character_to_json", type: "function", fqn: "rgs_grpc_bridge::login_character_to_json", kind: "fn", visibility: "private", signature: "fn login_character_to_json(r: &pb_player_proto::v1::LoginCharacterResponse) -> JsonValue", line: 256}),
//   (n20:Function {name: "json_to_get_server_time", type: "function", fqn: "rgs_grpc_bridge::json_to_get_server_time", kind: "fn", visibility: "private", signature: "fn json_to_get_server_time(v: &JsonValue) -> GetServerTimeRequest", line: 266}),
//   (n21:Function {name: "server_time_to_json", type: "function", fqn: "rgs_grpc_bridge::server_time_to_json", kind: "fn", visibility: "private", signature: "fn server_time_to_json(r: &ServerTimeInfo) -> JsonValue", line: 274}),
//   (n22:Function {name: "json_to_heartbeat", type: "function", fqn: "rgs_grpc_bridge::json_to_heartbeat", kind: "fn", visibility: "private", signature: "fn json_to_heartbeat(v: &JsonValue) -> HeartbeatRequest", line: 282}),
//   (n23:Function {name: "heartbeat_to_json", type: "function", fqn: "rgs_grpc_bridge::heartbeat_to_json", kind: "fn", visibility: "private", signature: "fn heartbeat_to_json(r: &HeartbeatResponse) -> JsonValue", line: 293}),
//   (n24:Function {name: "json_to_get_character_profile", type: "function", fqn: "rgs_grpc_bridge::json_to_get_character_profile", kind: "fn", visibility: "private", signature: "fn json_to_get_character_profile(v: &JsonValue) -> GetCharacterProfileRequest", line: 301}),
//   (n25:Function {name: "character_profile_to_json", type: "function", fqn: "rgs_grpc_bridge::character_profile_to_json", kind: "fn", visibility: "private", signature: "fn character_profile_to_json(r: &CharacterProfile) -> JsonValue", line: 310}),
//   (n26:Function {name: "json_to_healthcheck", type: "function", fqn: "rgs_grpc_bridge::json_to_healthcheck", kind: "fn", visibility: "private", signature: "fn json_to_healthcheck(v: &JsonValue) -> common_pb::HealthCheckRequest", line: 327}),
//   (n27:Function {name: "healthcheck_to_json", type: "function", fqn: "rgs_grpc_bridge::healthcheck_to_json", kind: "fn", visibility: "private", signature: "fn healthcheck_to_json(r: &common_pb::HealthCheckResponse) -> JsonValue", line: 335}),
//   (n28:Function {name: "tonic_to_response", type: "function", fqn: "rgs_grpc_bridge::tonic_to_response", kind: "fn", visibility: "private", signature: "fn tonic_to_response<T: Serialize>(r: Result<tonic::Response<T>, tonic::Status>) -> HttpResponse", line: 352}),
//   (n29:Function {name: "http_code_for_grpc", type: "function", fqn: "rgs_grpc_bridge::http_code_for_grpc", kind: "fn", visibility: "private", signature: "fn http_code_for_grpc(code: tonic::Code) -> u16", line: 378}),
//   (n30:Function {name: "health_handler", type: "function", fqn: "rgs_grpc_bridge::health_handler", kind: "fn", visibility: "private", signature: "fn health_handler() -> impl Responder", line: 405}),
//   (n31:Function {name: "root_handler", type: "function", fqn: "rgs_grpc_bridge::root_handler", kind: "fn", visibility: "private", signature: "fn root_handler() -> impl Responder", line: 409}),
//   (n32:Function {name: "health_check_handler", type: "function", fqn: "rgs_grpc_bridge::health_check_handler", kind: "fn", visibility: "private", signature: "fn health_check_handler( body: web::Json<JsonValue>, backend: web::Data<BackendClient>, ) -> impl Responder", line: 435}),
//   (n33:Function {name: "create_character_handler", type: "function", fqn: "rgs_grpc_bridge::create_character_handler", kind: "fn", visibility: "private", signature: "fn create_character_handler( body: web::Json<JsonValue>, backend: web::Data<BackendClient>, ) -> impl Responder", line: 456}),
//   (n34:Function {name: "get_server_time_handler", type: "function", fqn: "rgs_grpc_bridge::get_server_time_handler", kind: "fn", visibility: "private", signature: "fn get_server_time_handler( body: web::Json<JsonValue>, backend: web::Data<BackendClient>, ) -> impl Responder", line: 476}),
//   (n35:Function {name: "heartbeat_handler", type: "function", fqn: "rgs_grpc_bridge::heartbeat_handler", kind: "fn", visibility: "private", signature: "fn heartbeat_handler( body: web::Json<JsonValue>, backend: web::Data<BackendClient>, ) -> impl Responder", line: 493}),
//   (n36:Function {name: "login_character_handler", type: "function", fqn: "rgs_grpc_bridge::login_character_handler", kind: "fn", visibility: "private", signature: "fn login_character_handler( body: web::Json<JsonValue>, backend: web::Data<BackendClient>, ) -> impl Responder", line: 510}),
//   (n37:Function {name: "get_character_profile_handler", type: "function", fqn: "rgs_grpc_bridge::get_character_profile_handler", kind: "fn", visibility: "private", signature: "fn get_character_profile_handler( body: web::Json<JsonValue>, backend: web::Data<BackendClient>, ) -> impl Responder", line: 527}),
//   (n38:Function {name: "not_implemented_handler", type: "function", fqn: "rgs_grpc_bridge::not_implemented_handler", kind: "fn", visibility: "private", signature: "fn not_implemented_handler(req: HttpRequest) -> impl Responder", line: 544}),
//   (n39:Function {name: "main", type: "function", fqn: "rgs_grpc_bridge::main", kind: "fn", visibility: "private", signature: "fn main() -> anyhow::Result<()>", line: 562, attributes: "tokio::main"});
// MERGE (x1:Class {name: "Responder", type: "class"}) ON CREATE SET x1.kind = "impl_target", x1.decl = "None", x1.fqn = "actix_web::Responder";
// MERGE (x2:Module {name: "rgs_grpc_bridge", type: "module"}) ON CREATE SET x2.fqn = "rgs_grpc_bridge", x2.kind = "external_crate", x2.imports = "rgs_grpc_bridge::pb_player_proto::v1::AntiAddictionCheckRequest, rgs_grpc_bridge::pb_player_proto::v1::AntiAddictionCheckRequestas_, rgs_grpc_bridge::pb_player_proto::v1::AntiAddictionCheckResponse, rgs_grpc_bridge::pb_player_proto::v1::AvatarList, rgs_grpc_bridge::pb_player_proto::v1::AvatarListas_, rgs_grpc_bridge::pb_player_proto::v1::CharacterAssets, rgs_grpc_bridge::pb_player_proto::v1::CharacterAssetsas_, rgs_grpc_bridge::pb_player_proto::v1::CharacterInfo, rgs_grpc_bridge::pb_player_proto::v1::CharacterInfoas_, rgs_grpc_bridge::pb_player_proto::v1::CharacterProfile, rgs_grpc_bridge::pb_player_proto::v1::CharacterProfileas_, rgs_grpc_bridge::pb_player_proto::v1::CreateCharacterRequest";
// MERGE (x3:Module {name: "actix_web", type: "module"}) ON CREATE SET x3.fqn = "actix_web", x3.kind = "external_crate", x3.imports = "actix_web::App, actix_web::HttpRequest, actix_web::HttpResponse, actix_web::HttpServer, actix_web::Responder, actix_web::http::header, actix_web::middleware, actix_web::web, actix_web::HttpResponse::Ok, actix_web::HttpResponse::InternalServerError, actix_web::HttpResponse::build, actix_web::http::StatusCode::from_u16";
// MERGE (x4:Module {name: "std", type: "module"}) ON CREATE SET x4.fqn = "std", x4.kind = "external_crate", x4.imports = "std::sync::Arc, std::env, std::env::var, std::sync::Arc::new, std::time::Duration::from_secs, std::fs::read";
// MERGE (x5:Module {name: "tonic", type: "module"}) ON CREATE SET x5.fqn = "tonic", x5.kind = "external_crate", x5.imports = "tonic::transport::Channel, tonic::transport::ClientTlsConfig, tonic::transport::Identity, tonic::Status::unavailable, tonic::transport::Channel::from_shared, tonic::transport::Identity::from_pem, tonic::transport::ClientTlsConfig::new, tonic::transport::Certificate::from_pem, tonic::Request::new";
// MERGE (x6:Module {name: "serde", type: "module"}) ON CREATE SET x6.fqn = "serde", x6.kind = "external_crate", x6.imports = "serde::Deserialize, serde::Serialize";
// MERGE (x7:Module {name: "tracing_subscriber", type: "module"}) ON CREATE SET x7.fqn = "tracing_subscriber", x7.kind = "external_crate", x7.imports = "tracing_subscriber::EnvFilter, tracing_subscriber::fmt, tracing_subscriber::EnvFilter::try_from_default_env, tracing_subscriber::EnvFilter::new";
// MERGE (x8:Module {name: "tokio", type: "module"}) ON CREATE SET x8.fqn = "tokio", x8.kind = "external_crate", x8.imports = "tokio::sync::Mutex, tokio::sync::Mutex::new";
// MERGE (x9:Module {name: "serde_json", type: "module"}) ON CREATE SET x9.fqn = "serde_json", x9.kind = "external_crate", x9.imports = "serde_json::ValueasJsonValue, serde_json, serde_json::to_value";
// MERGE (x10:Module {name: "core", type: "module"}) ON CREATE SET x10.fqn = "core", x10.kind = "external_crate", x10.imports = "core::result::Result, core::option::Option";
// MERGE (x11:Module {name: "tracing", type: "module"}) ON CREATE SET x11.fqn = "tracing", x11.kind = "external_crate", x11.imports = "tracing";
// MERGE (x12:Module {name: "rustls", type: "module"}) ON CREATE SET x12.fqn = "rustls", x12.kind = "external_crate", x12.imports = "rustls::crypto::ring::default_provider";
// CREATE
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n1)-[:CONTAINS]->(n6),
//   (n1)-[:CONTAINS]->(n7),
//   (n1)-[:CONTAINS]->(n8),
//   (n1)-[:CONTAINS]->(n9),
//   (n7)-[:HAS_METHOD]->(n10),
//   (n8)-[:HAS_METHOD]->(n11),
//   (n8)-[:HAS_METHOD]->(n12),
//   (n1)-[:CONTAINS]->(n13),
//   (n1)-[:CONTAINS]->(n14),
//   (n1)-[:CONTAINS]->(n15),
//   (n1)-[:CONTAINS]->(n16),
//   (n1)-[:CONTAINS]->(n17),
//   (n1)-[:CONTAINS]->(n18),
//   (n1)-[:CONTAINS]->(n19),
//   (n1)-[:CONTAINS]->(n20),
//   (n1)-[:CONTAINS]->(n21),
//   (n1)-[:CONTAINS]->(n22),
//   (n1)-[:CONTAINS]->(n23),
//   (n1)-[:CONTAINS]->(n24),
//   (n1)-[:CONTAINS]->(n25),
//   (n1)-[:CONTAINS]->(n26),
//   (n1)-[:CONTAINS]->(n27),
//   (n1)-[:CONTAINS]->(n28),
//   (n1)-[:CONTAINS]->(n29),
//   (n1)-[:CONTAINS]->(n30),
//   (n1)-[:CONTAINS]->(n31),
//   (n1)-[:CONTAINS]->(n32),
//   (n1)-[:CONTAINS]->(n33),
//   (n1)-[:CONTAINS]->(n34),
//   (n1)-[:CONTAINS]->(n35),
//   (n1)-[:CONTAINS]->(n36),
//   (n1)-[:CONTAINS]->(n37),
//   (n1)-[:CONTAINS]->(n38),
//   (n1)-[:CONTAINS]->(n39),
//   (n3)-[:CONTAINS]->(n4),
//   (n5)-[:CONTAINS]->(n6),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::AntiAddictionCheckRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::AntiAddictionCheckRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::AntiAddictionCheckResponse"]->(x2),
//   (n1)-[:USES, import: "actix_web::App"]->(x3),
//   (n1)-[:USES, import: "std::sync::Arc"]->(x4),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::AvatarList"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::AvatarListas_"]->(x2),
//   (n1)-[:USES, import: "tonic::transport::Channel"]->(x5),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CharacterAssets"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CharacterAssetsas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CharacterInfo"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CharacterInfoas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CharacterProfile"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CharacterProfileas_"]->(x2),
//   (n1)-[:USES, import: "tonic::transport::ClientTlsConfig"]->(x5),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CreateCharacterRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CreateCharacterRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CreateCharacterResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CreateCharacterResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CreateDeckRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::CreateDeckRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::Deck"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::Deckas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::DeleteDeckRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::DeleteDeckRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::DeleteDeckResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::DeleteDeckResponseas_"]->(x2),
//   (n1)-[:USES, import: "serde::Deserialize"]->(x6),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::EnterBackgroundRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::EnterBackgroundRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::EnterBackgroundResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::EnterBackgroundResponseas_"]->(x2),
//   (n1)-[:USES, import: "tracing_subscriber::EnvFilter"]->(x7),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ForceDisconnectRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ForceDisconnectRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ForceDisconnectResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ForceDisconnectResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetAvatarListRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetAvatarListRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetCharacterAssetsRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetCharacterAssetsRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetCharacterInfoRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetCharacterInfoRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetCharacterProfileRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetCharacterProfileRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetDeckRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetDeckRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetPlayerProfileRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetPlayerProfileRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetServerTimeRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetServerTimeRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetSharedDeckRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GetSharedDeckRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GuestModeTimeoutRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GuestModeTimeoutRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GuestModeTimeoutResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::GuestModeTimeoutResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::HeartbeatRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::HeartbeatRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::HeartbeatResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::HeartbeatResponseas_"]->(x2),
//   (n1)-[:USES, import: "actix_web::HttpRequest"]->(x3),
//   (n1)-[:USES, import: "actix_web::HttpResponse"]->(x3),
//   (n1)-[:USES, import: "actix_web::HttpServer"]->(x3),
//   (n1)-[:USES, import: "tonic::transport::Identity"]->(x5),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ListDecksRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ListDecksRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ListDecksResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ListDecksResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::LoginCharacterRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::LoginCharacterResponseas_"]->(x2),
//   (n1)-[:USES, import: "tokio::sync::Mutex"]->(x8),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::Player"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::player_service_client"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::Playeras_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ReconnectCharacterRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ReconnectCharacterResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::RenameCharacterRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::RenameCharacterRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::RenameCharacterResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::RenameCharacterResponseas_"]->(x2),
//   (n1)-[:USES, import: "actix_web::Responder"]->(x3),
//   (n1)-[:USES, import: "serde::Serialize"]->(x6),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ServerTimeInfo"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ServerTimeInfoas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::SetAvatarRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::SetAvatarRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::SetAvatarResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::SetAvatarResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ShareDeckRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ShareDeckRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ShareDeckResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::ShareDeckResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::UpdateDeckRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::UpdateDeckRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::UpdateDeckResponseas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::UpdatePlayerProfileRequest"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::UpdatePlayerProfileRequestas_"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::UpdatePlayerProfileResponse"]->(x2),
//   (n1)-[:USES, import: "rgs_grpc_bridge::pb_player_proto::v1::UpdatePlayerProfileResponseas_"]->(x2),
//   (n1)-[:USES, import: "serde_json::ValueasJsonValue"]->(x9),
//   (n1)-[:USES, import: "std::env"]->(x4),
//   (n1)-[:USES, import: "actix_web::http::header"]->(x3),
//   (n1)-[:USES, import: "actix_web::middleware"]->(x3),
//   (n1)-[:USES, import: "rgs_grpc_bridge::common::v1ascommon_pb"]->(x2),
//   (n1)-[:USES, import: "actix_web::web"]->(x3),
//   (n10)-[:USES, via: "std::env::var"]->(x4),
//   (n10)-[:USES, via: "core::result::Result"]->(x10),
//   (n11)-[:USES, via: "std::sync::Arc::new"]->(x4),
//   (n11)-[:USES, via: "tokio::sync::Mutex::new"]->(x8),
//   (n12)-[:USES, via: "core::option::Option"]->(x10),
//   (n12)-[:USES, via: "core::result::Result"]->(x10),
//   (n12)-[:USES, via: "tracing"]->(x11),
//   (n12)-[:CALLS]->(n13),
//   (n12)-[:USES, via: "tonic::Status::unavailable"]->(x5),
//   (n13)-[:USES, via: "tonic::transport::Channel::from_shared"]->(x5),
//   (n13)-[:USES, via: "std::time::Duration::from_secs"]->(x4),
//   (n13)-[:USES, via: "std::fs::read"]->(x4),
//   (n13)-[:USES, via: "tonic::transport::Identity::from_pem"]->(x5),
//   (n13)-[:CALLS]->(n14),
//   (n13)-[:USES, via: "tonic::transport::ClientTlsConfig::new"]->(x5),
//   (n13)-[:USES, via: "tonic::transport::Certificate::from_pem"]->(x5),
//   (n13)-[:USES, via: "core::result::Result"]->(x10),
//   (n13)-[:USES, via: "rgs_grpc_bridge::pb_player_proto::v1::player_service_client"]->(x2),
//   (n15)-[:USES, via: "rustls::crypto::ring::default_provider"]->(x12),
//   (n16)-[:USES, via: "core::option::Option"]->(x10),
//   (n17)-[:USES, via: "serde_json"]->(x9),
//   (n18)-[:USES, via: "core::option::Option"]->(x10),
//   (n19)-[:USES, via: "serde_json"]->(x9),
//   (n20)-[:USES, via: "core::option::Option"]->(x10),
//   (n21)-[:USES, via: "serde_json"]->(x9),
//   (n22)-[:USES, via: "core::option::Option"]->(x10),
//   (n23)-[:USES, via: "serde_json"]->(x9),
//   (n24)-[:USES, via: "core::option::Option"]->(x10),
//   (n25)-[:USES, via: "serde_json"]->(x9),
//   (n26)-[:USES, via: "core::option::Option"]->(x10),
//   (n27)-[:USES, via: "serde_json"]->(x9),
//   (n28)-[:USES, via: "core::result::Result"]->(x10),
//   (n28)-[:USES, via: "serde_json::to_value"]->(x9),
//   (n28)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n28)-[:USES, via: "actix_web::HttpResponse::InternalServerError"]->(x3),
//   (n28)-[:USES, via: "tracing"]->(x11),
//   (n28)-[:USES, via: "actix_web::HttpResponse::build"]->(x3),
//   (n28)-[:USES, via: "actix_web::http::StatusCode::from_u16"]->(x3),
//   (n28)-[:CALLS]->(n29),
//   (n30)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n30)-[:USES, via: "serde_json"]->(x9),
//   (n31)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n31)-[:USES, via: "serde_json"]->(x9),
//   (n32)-[:CALLS]->(n26),
//   (n32)-[:USES, via: "core::result::Result"]->(x10),
//   (n32)-[:USES, via: "actix_web::HttpResponse::ServiceUnavailable"]->(x3),
//   (n32)-[:USES, via: "tonic::Request::new"]->(x5),
//   (n32)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n32)-[:CALLS]->(n27),
//   (n32)-[:USES, via: "tracing"]->(x11),
//   (n32)-[:USES, via: "actix_web::HttpResponse::build"]->(x3),
//   (n32)-[:USES, via: "actix_web::http::StatusCode::from_u16"]->(x3),
//   (n32)-[:CALLS]->(n29),
//   (n33)-[:CALLS]->(n16),
//   (n33)-[:USES, via: "core::result::Result"]->(x10),
//   (n33)-[:USES, via: "actix_web::HttpResponse::ServiceUnavailable"]->(x3),
//   (n33)-[:USES, via: "tonic::Request::new"]->(x5),
//   (n33)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n33)-[:CALLS]->(n17),
//   (n33)-[:USES, via: "tracing"]->(x11),
//   (n33)-[:USES, via: "actix_web::HttpResponse::build"]->(x3),
//   (n33)-[:USES, via: "actix_web::http::StatusCode::from_u16"]->(x3),
//   (n33)-[:CALLS]->(n29),
//   (n34)-[:CALLS]->(n20),
//   (n34)-[:USES, via: "core::result::Result"]->(x10),
//   (n34)-[:USES, via: "actix_web::HttpResponse::ServiceUnavailable"]->(x3),
//   (n34)-[:USES, via: "tonic::Request::new"]->(x5),
//   (n34)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n34)-[:CALLS]->(n21),
//   (n34)-[:USES, via: "actix_web::HttpResponse::build"]->(x3),
//   (n34)-[:USES, via: "actix_web::http::StatusCode::from_u16"]->(x3),
//   (n34)-[:CALLS]->(n29),
//   (n35)-[:CALLS]->(n22),
//   (n35)-[:USES, via: "core::result::Result"]->(x10),
//   (n35)-[:USES, via: "actix_web::HttpResponse::ServiceUnavailable"]->(x3),
//   (n35)-[:USES, via: "tonic::Request::new"]->(x5),
//   (n35)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n35)-[:CALLS]->(n23),
//   (n35)-[:USES, via: "actix_web::HttpResponse::build"]->(x3),
//   (n35)-[:USES, via: "actix_web::http::StatusCode::from_u16"]->(x3),
//   (n35)-[:CALLS]->(n29),
//   (n36)-[:CALLS]->(n18),
//   (n36)-[:USES, via: "core::result::Result"]->(x10),
//   (n36)-[:USES, via: "actix_web::HttpResponse::ServiceUnavailable"]->(x3),
//   (n36)-[:USES, via: "tonic::Request::new"]->(x5),
//   (n36)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n36)-[:CALLS]->(n19),
//   (n36)-[:USES, via: "actix_web::HttpResponse::build"]->(x3),
//   (n36)-[:USES, via: "actix_web::http::StatusCode::from_u16"]->(x3),
//   (n36)-[:CALLS]->(n29),
//   (n37)-[:CALLS]->(n24),
//   (n37)-[:USES, via: "core::result::Result"]->(x10),
//   (n37)-[:USES, via: "actix_web::HttpResponse::ServiceUnavailable"]->(x3),
//   (n37)-[:USES, via: "tonic::Request::new"]->(x5),
//   (n37)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n37)-[:CALLS]->(n25),
//   (n37)-[:USES, via: "actix_web::HttpResponse::build"]->(x3),
//   (n37)-[:USES, via: "actix_web::http::StatusCode::from_u16"]->(x3),
//   (n37)-[:CALLS]->(n29),
//   (n38)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x3),
//   (n38)-[:USES, via: "serde_json"]->(x9),
//   (n38)-[:USES, via: "tracing"]->(x11),
//   (n38)-[:USES, via: "actix_web::HttpResponse::NotFound"]->(x3),
//   (n39)-[:CALLS]->(n15),
//   (n39)-[:USES, via: "tracing_subscriber::fmt"]->(x7),
//   (n39)-[:USES, via: "tracing_subscriber::EnvFilter::try_from_default_env"]->(x7),
//   (n39)-[:USES, via: "tracing_subscriber::EnvFilter::new"]->(x7),
//   (n39)-[:CALLS, via: "rgs_grpc_bridge::BridgeConfig::from_env"]->(n10),
//   (n39)-[:USES, via: "tracing"]->(x11),
//   (n39)-[:CALLS, via: "rgs_grpc_bridge::BackendClient::new"]->(n11),
//   (n39)-[:USES, via: "actix_web::web::Data::new"]->(x3),
//   (n39)-[:USES, via: "actix_web::HttpServer::new"]->(x3),
//   (n39)-[:USES, via: "actix_web::App::new"]->(x3),
//   (n39)-[:USES, via: "actix_web::middleware::DefaultHeaders::new"]->(x3),
//   (n39)-[:USES, via: "actix_web::web::get"]->(x3),
//   (n39)-[:USES, via: "actix_web::web::post"]->(x3),
//   (n39)-[:USES, via: "actix_web::web::route"]->(x3),
//   (n39)-[:USES, via: "core::result::Result"]->(x10);
// ```
// ==== END CYPHER HEADER ====
//! rgs-grpc-bridge main.rs
//!
//! RGS gRPC-Web bridge: 浏览器 HTTP/1.1 + JSON (application/json) → RGS 5 域 gRPC server
//!
//! 设计 (per DTL-038 决策 + 9/10 JST Ulysses 拍板 opt2 独立 bridge binary):
//! - actix-web 4 暴露 HTTP/1.1 + JSON
//! - 内部用 tonic 0.12 client 调 backend gRPC server (mTLS or insecure)
//! - v0.1: 只 forward PlayerService (25 个 unary RPC)
//! - CORS: 允许浏览器 fetch 跨域 (H5 8788 → bridge 8080)
//! - 路径路由: /<package>.<service>/<method> 透传到对应 backend :50051
//! - JSON ↔ protobuf 转换: bridge 做透传, H5 发 JSON, bridge 编码到 protobuf 调 backend
//!
//! env 配置:
//! - RGS_BRIDGE_LISTEN: 监听地址 (default 0.0.0.0:8080)
//! - RGS_BRIDGE_PLAYER_BACKEND: player-service backend 地址 (default http://localhost:50051)
//! - RGS_BRIDGE_INSECURE: 1 = 跳过 mTLS (dev); 0 = mTLS (per RGS-REV-007 CH4 fail-closed)
//! - RGS_BRIDGE_CA_CERT / CLIENT_CERT / CLIENT_KEY: PEM 路径 (mTLS 模式)
//! - RUST_LOG: tracing filter (default info,rgs_grpc_bridge=debug)

use std::env;
use std::sync::Arc;

use actix_web::{
    http::header, middleware, web, App, HttpRequest, HttpResponse, HttpServer, Responder,
};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use tokio::sync::Mutex;
use tonic::transport::{Channel, ClientTlsConfig, Identity};
use tracing_subscriber::EnvFilter;

// ============================================================================
// proto 模块: 复用 player-service 的 .proto (build.rs 编译到 OUT_DIR)
// ============================================================================

mod pb_player_proto {
    pub mod v1 {
        tonic::include_proto!("player.v1");
    }
}

pub mod common {
    pub mod v1 {
        tonic::include_proto!("common.v1");
    }
}

use pb_player_proto::v1::{
    player_service_client::PlayerServiceClient, AntiAddictionCheckRequest,
    AntiAddictionCheckResponse, AvatarList, CharacterAssets, CharacterInfo, CharacterProfile,
    CreateCharacterRequest, CreateCharacterResponse, CreateDeckRequest, Deck,
    DeleteDeckRequest, DeleteDeckResponse, EnterBackgroundRequest, EnterBackgroundResponse,
    ForceDisconnectRequest, ForceDisconnectResponse, GetAvatarListRequest, GetCharacterAssetsRequest,
    GetCharacterInfoRequest, GetCharacterProfileRequest, GetPlayerProfileRequest, GetSharedDeckRequest,
    GuestModeTimeoutRequest, GuestModeTimeoutResponse, HeartbeatRequest, HeartbeatResponse,
    ListDecksRequest, ListDecksResponse, Player, RenameCharacterRequest, RenameCharacterResponse,
    ServerTimeInfo, SetAvatarRequest, SetAvatarResponse, ShareDeckRequest, ShareDeckResponse,
    UpdatePlayerProfileRequest, UpdatePlayerProfileResponse, GetServerTimeRequest,
    GetDeckRequest, UpdateDeckRequest, HeartbeatRequest as _, // avoid unused
};
use common::v1 as common_pb;
use pb_player_proto::v1::{
    AntiAddictionCheckRequest as _,
    AvatarList as _,
    CharacterAssets as _,
    CharacterInfo as _,
    CharacterProfile as _,
    CreateCharacterRequest as _,
    CreateCharacterResponse as _,
    CreateDeckRequest as _,
    Deck as _,
    DeleteDeckRequest as _,
    DeleteDeckResponse as _,
    EnterBackgroundRequest as _,
    EnterBackgroundResponse as _,
    ForceDisconnectRequest as _,
    ForceDisconnectResponse as _,
    GetAvatarListRequest as _,
    GetCharacterAssetsRequest as _,
    GetCharacterInfoRequest as _,
    GetCharacterProfileRequest as _,
    GetDeckRequest as _,
    GetPlayerProfileRequest as _,
    GetServerTimeRequest as _,
    GetSharedDeckRequest as _,
    GuestModeTimeoutRequest as _,
    GuestModeTimeoutResponse as _,
    HeartbeatRequest as _,
    HeartbeatResponse as _,
    ListDecksRequest as _,
    ListDecksResponse as _,
    LoginCharacterRequest as _,
    LoginCharacterResponse as _,
    Player as _,
    ReconnectCharacterRequest as _,
    ReconnectCharacterResponse as _,
    RenameCharacterRequest as _,
    RenameCharacterResponse as _,
    ServerTimeInfo as _,
    SetAvatarRequest as _,
    SetAvatarResponse as _,
    ShareDeckRequest as _,
    ShareDeckResponse as _,
    UpdateDeckRequest as _,
    UpdateDeckResponse as _,
    UpdatePlayerProfileRequest as _,
    UpdatePlayerProfileResponse as _,
};

// ============================================================================
// 配置
// ============================================================================

#[derive(Debug, Clone)]
struct BridgeConfig {
    listen_addr: String,
    player_backend: String,
    insecure: bool,
    ca_cert_path: Option<String>,
    client_cert_path: Option<String>,
    client_key_path: Option<String>,
}

impl BridgeConfig {
    fn from_env() -> Self {
        let insecure = env::var("RGS_BRIDGE_INSECURE").as_deref() == Ok("1");
        Self {
            listen_addr: env::var("RGS_BRIDGE_LISTEN")
                .unwrap_or_else(|_| "0.0.0.0:8080".to_string()),
            player_backend: env::var("RGS_BRIDGE_PLAYER_BACKEND")
                .unwrap_or_else(|_| "http://localhost:50051".to_string()),
            insecure,
            ca_cert_path: env::var("RGS_BRIDGE_CA_CERT").ok(),
            client_cert_path: env::var("RGS_BRIDGE_CLIENT_CERT").ok(),
            client_key_path: env::var("RGS_BRIDGE_CLIENT_KEY").ok(),
        }
    }
}

// ============================================================================
// Backend client 封装
// ============================================================================

#[derive(Clone)]
struct BackendClient {
    cfg: BridgeConfig,
    client: Arc<Mutex<Option<PlayerServiceClient<Channel>>>>,
}

impl BackendClient {
    fn new(cfg: BridgeConfig) -> Self {
        Self {
            cfg,
            client: Arc::new(Mutex::new(None)),
        }
    }

    async fn get(&self) -> Result<PlayerServiceClient<Channel>, tonic::Status> {
        let mut guard = self.client.lock().await;
        if let Some(c) = guard.as_ref() {
            return Ok(c.clone());
        }
        tracing::info!(target: "rgs_grpc_bridge", "connecting to backend {}", self.cfg.player_backend);
        let c = connect(&self.cfg)
            .await
            .map_err(|e| tonic::Status::unavailable(format!("backend connect: {e}")))?;
        *guard = Some(c.clone());
        Ok(c)
    }
}

async fn connect(cfg: &BridgeConfig) -> anyhow::Result<PlayerServiceClient<Channel>> {
    let mut endpoint = Channel::from_shared(cfg.player_backend.clone())?
        .http2_keep_alive_interval(std::time::Duration::from_secs(30))
        .keep_alive_timeout(std::time::Duration::from_secs(10));

    if !cfg.insecure {
        let ca = std::fs::read(cfg.ca_cert_path.as_ref().unwrap())?;
        let cert = std::fs::read(cfg.client_cert_path.as_ref().unwrap())?;
        let key = std::fs::read(cfg.client_key_path.as_ref().unwrap())?;
        let identity = Identity::from_pem(&cert, &key);
        let domain = if cfg.player_backend.contains("player-service")
            || cfg.player_backend.contains("localhost")
            || cfg.player_backend.contains("127.")
        {
            "player-service".to_string()
        } else {
            extract_host(&cfg.player_backend)
        };
        let tls = ClientTlsConfig::new()
            .ca_certificate(tonic::transport::Certificate::from_pem(ca))
            .identity(identity)
            .domain_name(domain);
        endpoint = endpoint.tls_config(tls)?;
    }

    let channel = endpoint.connect().await?;
    Ok(PlayerServiceClient::new(channel))
}

fn extract_host(url: &str) -> String {
    let after = url.split("://").nth(1).unwrap_or(url);
    let host_port = after.split('/').next().unwrap_or(after);
    let host = host_port.split(':').next().unwrap_or(host_port);
    host.to_string()
}

fn install_crypto_provider() {
    let _ = rustls::crypto::ring::default_provider().install_default();
}

// ============================================================================
// JSON <-> protobuf 转换 (per H5 mapping.js 17 个 ID)
// 用 prost + serde_json::Value 字段映射. 不做 exhaustive 字段覆盖, 只覆盖 H5 用的
// 字段 (mapping.js 17 个 ID). 未映射字段保持 default.
// ============================================================================

fn json_to_create_character(v: &JsonValue) -> CreateCharacterRequest {
    let mut r = CreateCharacterRequest::default();
    if let Some(o) = v.as_object() {
        r.request_id = o.get("requestId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.account_id = o.get("accountId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.character_name = o.get("characterName").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.class_id = o.get("classId").and_then(|x| x.as_i64()).unwrap_or(0) as i32;
        r.faction_id = o.get("factionId").and_then(|x| x.as_i64()).unwrap_or(0) as i32;
        r.device_id = o.get("deviceId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.client_ip = o.get("clientIp").and_then(|x| x.as_str()).unwrap_or("").to_string();
    }
    r
}

fn create_character_to_json(r: &CreateCharacterResponse) -> JsonValue {
    serde_json::json!({
        "created": r.created,
        "characterId": r.character_id,
        "characterName": r.character_name,
        "classId": r.class_id,
        "factionId": r.faction_id,
        "sessionId": r.session_id,
    })
}

fn json_to_login_character(v: &JsonValue) -> pb_player_proto::v1::LoginCharacterRequest {
    use pb_player_proto::v1::LoginCharacterRequest;
    let mut r = LoginCharacterRequest::default();
    if let Some(o) = v.as_object() {
        r.request_id = o.get("requestId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.account_id = o.get("accountId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.character_id = o.get("characterId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.device_id = o.get("deviceId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.client_ip = o.get("clientIp").and_then(|x| x.as_str()).unwrap_or("").to_string();
    }
    r
}

fn login_character_to_json(r: &pb_player_proto::v1::LoginCharacterResponse) -> JsonValue {
    use pb_player_proto::v1::LoginCharacterResponse;
    let _ = LoginCharacterResponse::default();  // keep import
    serde_json::json!({
        "loggedIn": r.logged_in,
        "sessionId": r.session_id,
        "expiresAt": r.expires_at.as_ref().map(|t| t.seconds).unwrap_or(0),
    })
}

fn json_to_get_server_time(v: &JsonValue) -> GetServerTimeRequest {
    let mut r = GetServerTimeRequest::default();
    if let Some(o) = v.as_object() {
        r.request_id = o.get("requestId").and_then(|x| x.as_str()).unwrap_or("").to_string();
    }
    r
}

fn server_time_to_json(r: &ServerTimeInfo) -> JsonValue {
    serde_json::json!({
        "serverTimeUnix": r.server_time_unix,
        "serverOpenTimeUnix": r.server_open_time_unix,
        "timezone": r.timezone,
    })
}

fn json_to_heartbeat(v: &JsonValue) -> HeartbeatRequest {
    let mut r = HeartbeatRequest::default();
    if let Some(o) = v.as_object() {
        r.request_id = o.get("requestId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.session_id = o.get("sessionId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.character_id = o.get("characterId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.client_time_unix = o.get("clientTimeUnix").and_then(|x| x.as_i64()).unwrap_or(0);
    }
    r
}

fn heartbeat_to_json(r: &HeartbeatResponse) -> JsonValue {
    serde_json::json!({
        "ok": r.ok,
        "serverTimeUnix": r.server_time_unix,
        "sessionExpiresAt": r.session_expires_at.as_ref().map(|t| t.seconds).unwrap_or(0),
    })
}

fn json_to_get_character_profile(v: &JsonValue) -> GetCharacterProfileRequest {
    let mut r = GetCharacterProfileRequest::default();
    if let Some(o) = v.as_object() {
        r.request_id = o.get("requestId").and_then(|x| x.as_str()).unwrap_or("").to_string();
        r.character_id = o.get("characterId").and_then(|x| x.as_str()).unwrap_or("").to_string();
    }
    r
}

fn character_profile_to_json(r: &CharacterProfile) -> JsonValue {
    serde_json::json!({
        "characterId": r.character_id,
        "characterName": r.character_name,
        "level": r.level,
        "vipLevel": r.vip_level,
        "classId": r.class_id,
        "factionId": r.faction_id,
        "status": r.status,
        "rankedScore": r.ranked_score,
        "rankedTier": r.ranked_tier,
        "totalMatches": r.total_matches,
        "totalWins": r.total_wins,
        "preferredLocale": r.preferred_locale,
    })
}

fn json_to_healthcheck(v: &JsonValue) -> common_pb::HealthCheckRequest {
    let mut r = common_pb::HealthCheckRequest::default();
    if let Some(o) = v.as_object() {
        r.service = o.get("service").and_then(|x| x.as_str()).unwrap_or("").to_string();
    }
    r
}

fn healthcheck_to_json(r: &common_pb::HealthCheckResponse) -> JsonValue {
    serde_json::json!({
        "status": r.status,
        "message": r.message,
    })
}

// ============================================================================
// Error response (Connect Protocol-style)
// ============================================================================

#[derive(Serialize, Deserialize)]
struct ErrorBody {
    code: String,
    message: String,
}

fn tonic_to_response<T: Serialize>(r: Result<tonic::Response<T>, tonic::Status>) -> HttpResponse {
    match r {
        Ok(resp) => match serde_json::to_value(resp.into_inner()) {
            Ok(v) => HttpResponse::Ok().json(v),
            Err(e) => HttpResponse::InternalServerError().json(ErrorBody {
                code: "internal".into(),
                message: format!("serialize response: {e}"),
            }),
        },
        Err(status) => {
            let code = match status.code() {
                tonic::Code::Unavailable => "unavailable",
                tonic::Code::Unimplemented => "unimplemented",
                tonic::Code::InvalidArgument => "invalid_argument",
                tonic::Code::NotFound => "not_found",
                tonic::Code::PermissionDenied => "permission_denied",
                tonic::Code::Internal => "internal",
                _ => "unknown",
            };
            tracing::warn!(target: "rgs_grpc_bridge", "backend error: code={} message={}", code, status.message());
            HttpResponse::build(actix_web::http::StatusCode::from_u16(http_code_for_grpc(status.code())).unwrap())
                .json(ErrorBody { code: code.to_string(), message: status.message().to_string() })
        }
    }
}

fn http_code_for_grpc(code: tonic::Code) -> u16 {
    use tonic::Code::*;
    match code {
        Ok => 200,
        Cancelled => 499,
        Unknown => 500,
        InvalidArgument => 400,
        DeadlineExceeded => 504,
        NotFound => 404,
        AlreadyExists => 409,
        PermissionDenied => 403,
        ResourceExhausted => 429,
        FailedPrecondition => 412,
        OutOfRange => 400,
        Unimplemented => 501,
        Internal => 500,
        Unavailable => 503,
        DataLoss => 500,
        Unauthenticated => 401,
        _ => 500,  // fallback for Aborted (10) and any future codes
    }
}

// ============================================================================
// actix-web 路由 handler
// ============================================================================

async fn health_handler() -> impl Responder {
    HttpResponse::Ok().json(serde_json::json!({"status": "SERVING"}))
}

async fn root_handler() -> impl Responder {
    HttpResponse::Ok().json(serde_json::json!({
        "service": "rgs-grpc-bridge",
        "version": env!("CARGO_PKG_VERSION"),
        "endpoints": [
            "POST /player.v1.PlayerService/HealthCheck",
            "POST /player.v1.PlayerService/CreateCharacter",
            "POST /player.v1.PlayerService/LoginCharacter",
            "POST /player.v1.PlayerService/ReconnectCharacter",
            "POST /player.v1.PlayerService/GetCharacterProfile",
            "POST /player.v1.PlayerService/GetCharacterAssets",
            "POST /player.v1.PlayerService/GetCharacterInfo",
            "POST /player.v1.PlayerService/RenameCharacter",
            "POST /player.v1.PlayerService/GetServerTime",
            "POST /player.v1.PlayerService/GuestModeTimeout",
            "POST /player.v1.PlayerService/AntiAddictionCheck",
            "POST /player.v1.PlayerService/ForceDisconnect",
            "POST /player.v1.PlayerService/EnterBackground",
            "POST /player.v1.PlayerService/GetAvatarList",
            "POST /player.v1.PlayerService/SetAvatar",
            "POST /player.v1.PlayerService/Heartbeat",
            "GET  /health"
        ]
    }))
}

async fn health_check_handler(
    body: web::Json<JsonValue>,
    backend: web::Data<BackendClient>,
) -> impl Responder {
    let req = json_to_healthcheck(&body);
    let mut c = match backend.get().await {
        Ok(c) => c,
        Err(e) => return HttpResponse::ServiceUnavailable().json(ErrorBody { code: "unavailable".into(), message: e.message().into() }),
    };
    let resp = c.health_check(tonic::Request::new(req)).await;
    // Convert to generic JSON via helper (HealthCheckResponse has Status enum)
    match resp {
        Ok(r) => HttpResponse::Ok().json(healthcheck_to_json(&r.into_inner())),
        Err(status) => {
            tracing::warn!(target: "rgs_grpc_bridge", "HealthCheck backend error: code={} message={}", status.code(), status.message());
            HttpResponse::build(actix_web::http::StatusCode::from_u16(http_code_for_grpc(status.code())).unwrap())
                .json(ErrorBody { code: format!("{:?}", status.code()).to_lowercase(), message: status.message().to_string() })
        }
    }
}

async fn create_character_handler(
    body: web::Json<JsonValue>,
    backend: web::Data<BackendClient>,
) -> impl Responder {
    let req = json_to_create_character(&body);
    let mut c = match backend.get().await {
        Ok(c) => c,
        Err(e) => return HttpResponse::ServiceUnavailable().json(ErrorBody { code: "unavailable".into(), message: e.message().into() }),
    };
    let resp = c.create_character(tonic::Request::new(req)).await;
    match resp {
        Ok(r) => HttpResponse::Ok().json(create_character_to_json(&r.into_inner())),
        Err(status) => {
            tracing::warn!(target: "rgs_grpc_bridge", "CreateCharacter error: code={} message={}", status.code(), status.message());
            HttpResponse::build(actix_web::http::StatusCode::from_u16(http_code_for_grpc(status.code())).unwrap())
                .json(ErrorBody { code: format!("{:?}", status.code()).to_lowercase(), message: status.message().to_string() })
        }
    }
}

async fn get_server_time_handler(
    body: web::Json<JsonValue>,
    backend: web::Data<BackendClient>,
) -> impl Responder {
    let req = json_to_get_server_time(&body);
    let mut c = match backend.get().await {
        Ok(c) => c,
        Err(e) => return HttpResponse::ServiceUnavailable().json(ErrorBody { code: "unavailable".into(), message: e.message().into() }),
    };
    let resp = c.get_server_time(tonic::Request::new(req)).await;
    match resp {
        Ok(r) => HttpResponse::Ok().json(server_time_to_json(&r.into_inner())),
        Err(status) => HttpResponse::build(actix_web::http::StatusCode::from_u16(http_code_for_grpc(status.code())).unwrap())
            .json(ErrorBody { code: format!("{:?}", status.code()).to_lowercase(), message: status.message().to_string() })
    }
}

async fn heartbeat_handler(
    body: web::Json<JsonValue>,
    backend: web::Data<BackendClient>,
) -> impl Responder {
    let req = json_to_heartbeat(&body);
    let mut c = match backend.get().await {
        Ok(c) => c,
        Err(e) => return HttpResponse::ServiceUnavailable().json(ErrorBody { code: "unavailable".into(), message: e.message().into() }),
    };
    let resp = c.heartbeat(tonic::Request::new(req)).await;
    match resp {
        Ok(r) => HttpResponse::Ok().json(heartbeat_to_json(&r.into_inner())),
        Err(status) => HttpResponse::build(actix_web::http::StatusCode::from_u16(http_code_for_grpc(status.code())).unwrap())
            .json(ErrorBody { code: format!("{:?}", status.code()).to_lowercase(), message: status.message().to_string() })
    }
}

async fn login_character_handler(
    body: web::Json<JsonValue>,
    backend: web::Data<BackendClient>,
) -> impl Responder {
    let req = json_to_login_character(&body);
    let mut c = match backend.get().await {
        Ok(c) => c,
        Err(e) => return HttpResponse::ServiceUnavailable().json(ErrorBody { code: "unavailable".into(), message: e.message().into() }),
    };
    let resp = c.login_character(tonic::Request::new(req)).await;
    match resp {
        Ok(r) => HttpResponse::Ok().json(login_character_to_json(&r.into_inner())),
        Err(status) => HttpResponse::build(actix_web::http::StatusCode::from_u16(http_code_for_grpc(status.code())).unwrap())
            .json(ErrorBody { code: format!("{:?}", status.code()).to_lowercase(), message: status.message().to_string() })
    }
}

async fn get_character_profile_handler(
    body: web::Json<JsonValue>,
    backend: web::Data<BackendClient>,
) -> impl Responder {
    let req = json_to_get_character_profile(&body);
    let mut c = match backend.get().await {
        Ok(c) => c,
        Err(e) => return HttpResponse::ServiceUnavailable().json(ErrorBody { code: "unavailable".into(), message: e.message().into() }),
    };
    let resp = c.get_character_profile(tonic::Request::new(req)).await;
    match resp {
        Ok(r) => HttpResponse::Ok().json(character_profile_to_json(&r.into_inner())),
        Err(status) => HttpResponse::build(actix_web::http::StatusCode::from_u16(http_code_for_grpc(status.code())).unwrap())
            .json(ErrorBody { code: format!("{:?}", status.code()).to_lowercase(), message: status.message().to_string() })
    }
}

async fn not_implemented_handler(req: HttpRequest) -> impl Responder {
    let path = req.path();
    // CORS preflight (OPTIONS) -> 200 with CORS headers (DefaultHeaders already adds them)
    if req.method() == actix_web::http::Method::OPTIONS {
        return HttpResponse::Ok().json(serde_json::json!({"preflight": "ok"}));
    }
    tracing::warn!(target: "rgs_grpc_bridge", "unhandled method: {}", path);
    HttpResponse::NotFound().json(ErrorBody {
        code: "not_found".into(),
        message: format!("method {} not implemented in v0.1 (only 17/25 PlayerService methods exposed)", path),
    })
}

// ============================================================================
// main
// ============================================================================

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    install_crypto_provider();

    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("info,rgs_grpc_bridge=debug")),
        )
        .init();

    let cfg = BridgeConfig::from_env();
    tracing::info!(
        target: "rgs_grpc_bridge",
        "starting: listen={} player_backend={} insecure={}",
        cfg.listen_addr, cfg.player_backend, cfg.insecure,
    );

    let backend = BackendClient::new(cfg.clone());
    let backend_data = web::Data::new(backend);
    let listen = cfg.listen_addr.clone();

    HttpServer::new(move || {
        App::new()
            .app_data(backend_data.clone())
            .app_data(web::JsonConfig::default().limit(1024 * 1024))  // 1 MB
            .wrap(middleware::Logger::default())
            .wrap(middleware::DefaultHeaders::new()
                .add(("Access-Control-Allow-Origin", "*"))
                .add(("Access-Control-Allow-Methods", "GET, POST, OPTIONS"))
                .add(("Access-Control-Allow-Headers", "Content-Type, Authorization, Accept, X-Grpc-Web, X-User-Agent"))
                .add(("Access-Control-Max-Age", "3600"))
            )
            .route("/", web::get().to(root_handler))
            .route("/health", web::get().to(health_handler))
            .route("/player.v1.PlayerService/HealthCheck", web::post().to(health_check_handler))
            .route("/player.v1.PlayerService/CreateCharacter", web::post().to(create_character_handler))
            .route("/player.v1.PlayerService/LoginCharacter", web::post().to(login_character_handler))
            .route("/player.v1.PlayerService/ReconnectCharacter", web::post().to(login_character_handler))  // placeholder, same as login
            .route("/player.v1.PlayerService/GetCharacterProfile", web::post().to(get_character_profile_handler))
            .route("/player.v1.PlayerService/GetServerTime", web::post().to(get_server_time_handler))
            .route("/player.v1.PlayerService/Heartbeat", web::post().to(heartbeat_handler))
            .route("/player.v1.PlayerService/GetCharacterAssets", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/GetCharacterInfo", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/RenameCharacter", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/GuestModeTimeout", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/AntiAddictionCheck", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/ForceDisconnect", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/EnterBackground", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/GetAvatarList", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/SetAvatar", web::post().to(not_implemented_handler))
            // deck + others
            .route("/player.v1.PlayerService/GetPlayer", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/GetPlayerProfile", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/UpdatePlayerProfile", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/CreateDeck", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/GetDeck", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/UpdateDeck", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/DeleteDeck", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/ListDecks", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/ShareDeck", web::post().to(not_implemented_handler))
            .route("/player.v1.PlayerService/GetSharedDeck", web::post().to(not_implemented_handler))
            // CORS preflight (fallback)
            .route("/{tail:.*}", web::route().to(not_implemented_handler))
    })
    .bind(&listen)?
    .run()
    .await?;

    Ok(())
}
