# 50-secret-economy-tls.yaml
# 角色:economy 域 server 证书 + 私钥 Secret(kubernetes.io/tls)
# 状态:🔴 模板占位(实际值由 phase-0-5-step-4-render-secrets.ps1 注入)
# 注入后产出: E:\DevCache\cargo\target\rendered-secrets\50-secret-economy-tls.yaml
# apply 路径(主对话 WF-0.5-2/0.5-3 合入后):
#   kubectl apply -f E:/DevCache/cargo/target/rendered-secrets/50-secret-economy-tls.yaml
#
# 文件映射(容器内,通过 50-secret-* volumes 挂载到 /etc/rgs/certs/):
#   /etc/rgs/certs/server.pem  ← tls.crt (economy.service.crt.pem)
#   /etc/rgs/certs/server.key  ← tls.key (economy.service.key.pem)
#   /etc/rgs/certs/ca.pem      ← 来自 rgs-secret-ca(独立 mount)
#
# 关联: RGS-INC-001 v0.2 §1.4 (mTLS fail-closed) + 55.21 wire-up
# 注意: economy 域是 Q-003 Saga 跨域核心,证书含 rust-game-server.io/saga-critical=true
apiVersion: v1
kind: Secret
metadata:
  name: rgs-secret-economy-tls
  namespace: rgs
  labels:
    app.kubernetes.io/part-of: rust-game-server
    app.kubernetes.io/name: economy
    app.kubernetes.io/component: domain-service
    rust-game-server.io/cert-type: mtls-server
    rust-game-server.io/saga-critical: "true"
type: kubernetes.io/tls
# data 字段(实际值)由 phase-0-5-step-4-render-secrets.ps1 替换:
#   tls.crt: <base64(economy.service.crt.pem)>
#   tls.key: <base64(economy.service.key.pem)>
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlCaFRDQ0FTdWdBd0lCQWdJVUZaQjRIbjE4dHplK0FvK3lWUFEwdTl4UFlCTXdDZ1lJS29aSXpqMEVBd0l3DQpNakVlTUJ3R0ExVUVBd3dWVW5WemRFZGhiV1ZUWlhKMlpYSWdSR1YySUVOQk1SQXdEZ1lEVlFRS0RBZFZiSGx6DQpjMlZ6TUI0WERUSTJNRGd5TkRBNU1UQXpNMW9YRFRJNE1EZ3lNekE1TVRBek0xb3dNekVZTUJZR0ExVUVBd3dQDQpaV052Ym05dGVTNXpaWEoyYVdObE1SY3dGUVlEVlFRS0RBNVNkWE4wUjJGdFpWTmxjblpsY2pCWk1CTUdCeXFHDQpTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRGwxSW0wN3dYUXFvMFQrL05RWnoxUHk3WWN0QVU3bVJMNUdMdERhDQp4ZTR0dC9Cb2x4Y3JYZG84Vjk5MTVOWnNaTU9RSUdKbG10Zk90WTJKcjYxU1RzMmpIakFjTUJvR0ExVWRFUVFUDQpNQkdDRDJWamIyNXZiWGt1YzJWeWRtbGpaVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBMS9VVjNYZThoYWVsDQpXc2d6c1Z2eFdIdGFyVGVjeHRoK1pWcUo0c01xc0dRQ0lEaGtOWWgvMjFURTdTSUZHSzNtUGxrQ0QrR01rNU9uDQoyTUd4alNQME9pUksNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg=="
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUdIQWdFQU1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhCRzB3YXdJQkFRUWd3RzFIVnVPb1B3Q0s0T1RWDQpvOUxPdFNqTGlORVRWeXBQd3JreGx2anNUUzZoUkFOQ0FBUTVkU0p0TzhGMEtxTkUvdnpVR2M5VDh1MkhMUUZPDQo1a1MrUmk3UTJzWHVMYmZ3YUpjWEsxM2FQRmZmZGVUV2JHVERrQ0JpWlpyWHpyV05pYSt0VWs3Tg0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ0K"
