# 50-secret-match-tls.yaml
# 角色:match 域 server 证书 + 私钥 Secret(kubernetes.io/tls)
# 状态:🔴 模板占位(实际值由 phase-0-5-step-4-render-secrets.ps1 注入)
# 注入后产出: E:\DevCache\cargo\target\rendered-secrets\50-secret-match-tls.yaml
# apply 路径(主对话 WF-0.5-2/0.5-3 合入后):
#   kubectl apply -f E:/DevCache/cargo/target/rendered-secrets/50-secret-match-tls.yaml
#
# 文件映射(容器内,通过 50-secret-* volumes 挂载到 /etc/rgs/certs/):
#   /etc/rgs/certs/server.pem  ← tls.crt (match.service.crt.pem)
#   /etc/rgs/certs/server.key  ← tls.key (match.service.key.pem)
#   /etc/rgs/certs/ca.pem      ← 来自 rgs-secret-ca(独立 mount)
#
# 关联: RGS-INC-001 v0.2 §1.4 (mTLS fail-closed) + 55.21 wire-up
apiVersion: v1
kind: Secret
metadata:
  name: rgs-secret-match-tls
  namespace: rgs
  labels:
    app.kubernetes.io/part-of: rust-game-server
    app.kubernetes.io/name: match
    app.kubernetes.io/component: domain-service
    rust-game-server.io/cert-type: mtls-server
type: kubernetes.io/tls
# data 字段(实际值)由 phase-0-5-step-4-render-secrets.ps1 替换:
#   tls.crt: <base64(match.service.crt.pem)>
#   tls.key: <base64(match.service.key.pem)>
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlCZ1RDQ0FTZWdBd0lCQWdJVWIyOGpCN3RtWHh6c0I2aTR1N2w1b0dweGZ1VXdDZ1lJS29aSXpqMEVBd0l3DQpNakVlTUJ3R0ExVUVBd3dWVW5WemRFZGhiV1ZUWlhKMlpYSWdSR1YySUVOQk1SQXdEZ1lEVlFRS0RBZFZiSGx6DQpjMlZ6TUI0WERUSTJNRGd5TkRBNU1UQXpNMW9YRFRJNE1EZ3lNekE1TVRBek0xb3dNVEVXTUJRR0ExVUVBd3dODQpiV0YwWTJndWMyVnlkbWxqWlRFWE1CVUdBMVVFQ2d3T1VuVnpkRWRoYldWVFpYSjJaWEl3V1RBVEJnY3Foa2pPDQpQUUlCQmdncWhrak9QUU1CQndOQ0FBUlRhdGFPQ3Q4emhGT1NMODFyTkhlUTNlUytrZDVqdGJqK0JaUVVsYlNjDQo3WGJnaksrd0NZTXJKanVVUS8vRFNpSWlzcUlnQlo4ZjEvMHJIU1R3dFBzWG94d3dHakFZQmdOVkhSRUVFVEFQDQpnZzF0WVhSamFDNXpaWEoyYVdObE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRGZzVHRSMHJhQVVORjFsamJrDQpUQ2dxajgrTDNUN25EVENXeGxhRDE4SVN0d0lnSEpQTmQrTGJjREJBSnNrYUFiYmhTQy93TEFxa0ZNNlVhUTRzDQo1SkJjcTV3PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K"
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUdIQWdFQU1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhCRzB3YXdJQkFRUWc4a1pEbmpJSWE2MDZNa1BFDQpmdEVRQTZIM1hnaTdtYW56QmVPa09PQ2VFUU9oUkFOQ0FBUlRhdGFPQ3Q4emhGT1NMODFyTkhlUTNlUytrZDVqDQp0YmorQlpRVWxiU2M3WGJnaksrd0NZTXJKanVVUS8vRFNpSWlzcUlnQlo4ZjEvMHJIU1R3dFBzWA0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ0K"
