apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-service-account
  namespace: rust-game-server
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scene-service-account
  namespace: rust-game-server
  labels:
    app.kubernetes.io/name: scene
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: battle-service-account
  namespace: rust-game-server
  labels:
    app.kubernetes.io/name: battle
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-gateway-account
  namespace: rust-game-server
  labels:
    app.kubernetes.io/name: network-gateway
