// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "entity.rs", type: "file", path: "crates/scene-service/src/entity.rs", crate: "scene-service", module_path: "scene_service::entity", kind: "src", lines: 206}),
//   (n2:Class {name: "Position", type: "class", fqn: "scene_service::entity::Position", kind: "struct", visibility: "private", line: 17, attributes: "derive"}),
//   (n3:Class {name: "Scene", type: "class", fqn: "scene_service::entity::Scene", kind: "struct", visibility: "private", line: 32, attributes: "derive"}),
//   (n4:Class {name: "SceneInstance", type: "class", fqn: "scene_service::entity::SceneInstance", kind: "struct", visibility: "private", line: 69, attributes: "derive"}),
//   (n5:Class {name: "InstanceStatus", type: "class", fqn: "scene_service::entity::InstanceStatus", kind: "enum", visibility: "private", line: 82, attributes: "derive, serde"}),
//   (n6:Class {name: "MapUnit", type: "class", fqn: "scene_service::entity::MapUnit", kind: "struct", visibility: "private", line: 127, attributes: "derive"}),
//   (n7:Class {name: "SpaceInfo", type: "class", fqn: "scene_service::entity::SpaceInfo", kind: "struct", visibility: "private", line: 166, attributes: "derive"}),
//   (n8:Function {name: "new", type: "function", fqn: "scene_service::entity::Position::new", kind: "method", visibility: "private", signature: "fn new(x: i32, y: i32, dir: i32) -> Self", line: 25}),
//   (n9:Function {name: "new", type: "function", fqn: "scene_service::entity::Scene::new", kind: "method", visibility: "private", signature: "fn new(id: String, name: String, map_resource_id: String) -> Self", line: 46}),
//   (n10:Function {name: "is_level_allowed", type: "function", fqn: "scene_service::entity::Scene::is_level_allowed", kind: "method", visibility: "private", signature: "fn is_level_allowed(&self, level: i32) -> bool", line: 62}),
//   (n11:Function {name: "new", type: "function", fqn: "scene_service::entity::SceneInstance::new", kind: "method", visibility: "private", signature: "fn new(scene_id: String, owner_id: Uuid, capacity: i32, server_node_id: i64) -> Self", line: 91}),
//   (n12:Function {name: "is_full", type: "function", fqn: "scene_service::entity::SceneInstance::is_full", kind: "method", visibility: "private", signature: "fn is_full(&self) -> bool", line: 106}),
//   (n13:Function {name: "add_player", type: "function", fqn: "scene_service::entity::SceneInstance::add_player", kind: "method", visibility: "private", signature: "fn add_player(&mut self)", line: 111}),
//   (n14:Function {name: "remove_player", type: "function", fqn: "scene_service::entity::SceneInstance::remove_player", kind: "method", visibility: "private", signature: "fn remove_player(&mut self)", line: 118}),
//   (n15:Function {name: "new", type: "function", fqn: "scene_service::entity::MapUnit::new", kind: "method", visibility: "private", signature: "fn new(scene_id: String, base_id: i32, name: String, x: i32, y: i32) -> Self", line: 142}),
//   (n16:Function {name: "move_to", type: "function", fqn: "scene_service::entity::MapUnit::move_to", kind: "method", visibility: "private", signature: "fn move_to(&mut self, x: i32, y: i32)", line: 158}),
//   (n17:Function {name: "new", type: "function", fqn: "scene_service::entity::SpaceInfo::new", kind: "method", visibility: "private", signature: "fn new(player_id: Uuid) -> Self", line: 176}),
//   (n18:Function {name: "update_sign", type: "function", fqn: "scene_service::entity::SpaceInfo::update_sign", kind: "method", visibility: "private", signature: "fn update_sign(&mut self, sign: String) -> crate::Result<()>", line: 187}),
//   (n19:Function {name: "set_background", type: "function", fqn: "scene_service::entity::SpaceInfo::set_background", kind: "method", visibility: "private", signature: "fn set_background(&mut self, background_id: String)", line: 198}),
//   (n20:Function {name: "add_visit", type: "function", fqn: "scene_service::entity::SpaceInfo::add_visit", kind: "method", visibility: "private", signature: "fn add_visit(&mut self)", line: 203});
// MERGE (x1:Module {name: "chrono", type: "module"}) ON CREATE SET x1.fqn = "chrono", x1.kind = "external_crate", x1.imports = "chrono::DateTime, chrono::Utc, chrono::Utc::now";
// MERGE (x2:Module {name: "serde", type: "module"}) ON CREATE SET x2.fqn = "serde", x2.kind = "external_crate", x2.imports = "serde::Deserialize, serde::Serialize";
// MERGE (x3:Module {name: "uuid", type: "module"}) ON CREATE SET x3.fqn = "uuid", x3.kind = "external_crate", x3.imports = "uuid::Uuid, uuid::Uuid::new_v4";
// MERGE (x4:Module {name: "std", type: "module"}) ON CREATE SET x4.fqn = "std", x4.kind = "external_crate", x4.imports = "std::string::String::new";
// MERGE (x5:Module {name: "core", type: "module"}) ON CREATE SET x5.fqn = "core", x5.kind = "external_crate", x5.imports = "core::result::Result";
// MERGE (x6:Module {name: "scene_service", type: "module"}) ON CREATE SET x6.fqn = "scene_service", x6.kind = "external_crate", x6.imports = "scene_service::Error";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n1)-[:CONTAINS]->(n6),
//   (n1)-[:CONTAINS]->(n7),
//   (n2)-[:HAS_METHOD]->(n8),
//   (n3)-[:HAS_METHOD]->(n9),
//   (n3)-[:HAS_METHOD]->(n10),
//   (n4)-[:HAS_METHOD]->(n11),
//   (n4)-[:HAS_METHOD]->(n12),
//   (n4)-[:HAS_METHOD]->(n13),
//   (n4)-[:HAS_METHOD]->(n14),
//   (n6)-[:HAS_METHOD]->(n15),
//   (n6)-[:HAS_METHOD]->(n16),
//   (n7)-[:HAS_METHOD]->(n17),
//   (n7)-[:HAS_METHOD]->(n18),
//   (n7)-[:HAS_METHOD]->(n19),
//   (n7)-[:HAS_METHOD]->(n20),
//   (n1)-[:USES, import: "chrono::DateTime"]->(x1),
//   (n1)-[:USES, import: "serde::Deserialize"]->(x2),
//   (n1)-[:USES, import: "serde::Serialize"]->(x2),
//   (n1)-[:USES, import: "chrono::Utc"]->(x1),
//   (n1)-[:USES, import: "uuid::Uuid"]->(x3),
//   (n9)-[:USES, via: "chrono::Utc::now"]->(x1),
//   (n9)-[:USES, via: "std::string::String::new"]->(x4),
//   (n11)-[:USES, via: "chrono::Utc::now"]->(x1),
//   (n11)-[:USES, via: "uuid::Uuid::new_v4"]->(x3),
//   (n15)-[:USES, via: "uuid::Uuid::new_v4"]->(x3),
//   (n17)-[:USES, via: "std::string::String::new"]->(x4),
//   (n18)-[:USES, via: "core::result::Result"]->(x5),
//   (n18)-[:USES, via: "scene_service::Error"]->(x6);
// ```
// ==== END CYPHER HEADER ====
//! scene-service 域 entity 定义
//!
//! 7 域 scene-service 业务核心 entity (per 9/4 MD §2 + 9/5 改进路线图 Phase 2)
//! - Scene: 静态场景元数据 (master data)
//! - SceneInstance: 玩家实例化的场景 (transaction)
//! - MapUnit: 地图上的单位 (master + work)
//! - SpaceInfo: 玩家空间/签名 (master)
//!
//! 设计原则: Master / Transaction / Work 三分类 (per 9/1 18:30 JST 横展)

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// 坐标 (per [游戏A] proto_102.erl)
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub struct Position {
    pub x: i32,
    pub y: i32,
    pub dir: i32,
}

impl Position {
    /// 工厂: 新建坐标
    pub fn new(x: i32, y: i32, dir: i32) -> Self {
        Self { x, y, dir }
    }
}

/// 场景元数据 (Master data, per 9/1 18:30 JST DB 三分类)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Scene {
    pub id: String,
    pub name: String,
    pub description: String,
    pub map_resource_id: String,
    pub max_players: i32,
    pub min_level: i32,
    pub max_level: i32,
    pub scene_type: String,
    pub created_at: DateTime<Utc>,
}

impl Scene {
    /// 工厂: 新建场景
    pub fn new(id: String, name: String, map_resource_id: String) -> Self {
        let now = Utc::now();
        Self {
            id,
            name,
            description: String::new(),
            map_resource_id,
            max_players: 100,
            min_level: 1,
            max_level: 999,
            scene_type: "normal".to_string(),
            created_at: now,
        }
    }

    /// 业务规则: 等级是否在范围内
    pub fn is_level_allowed(&self, level: i32) -> bool {
        level >= self.min_level && level <= self.max_level
    }
}

/// 场景实例 (Transaction, per 9/1 18:30 JST)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SceneInstance {
    pub id: Uuid,
    pub scene_id: String,
    pub owner_id: Uuid,
    pub player_count: i32,
    pub capacity: i32,
    pub status: InstanceStatus,
    pub server_node_id: i64,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InstanceStatus {
    Active,
    Loading,
    Closing,
    Closed,
}

impl SceneInstance {
    /// 工厂: 新建场景实例
    pub fn new(scene_id: String, owner_id: Uuid, capacity: i32, server_node_id: i64) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            scene_id,
            owner_id,
            player_count: 1,
            capacity,
            status: InstanceStatus::Active,
            server_node_id,
            created_at: now,
        }
    }

    /// 业务规则: 是否已满
    pub fn is_full(&self) -> bool {
        self.player_count >= self.capacity
    }

    /// 业务规则: 加入玩家
    pub fn add_player(&mut self) {
        if !self.is_full() {
            self.player_count += 1;
        }
    }

    /// 业务规则: 离开玩家
    pub fn remove_player(&mut self) {
        if self.player_count > 0 {
            self.player_count -= 1;
        }
    }
}

/// 地图单位 (per [游戏A] proto_102.erl map_unit)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MapUnit {
    pub id: Uuid,
    pub battle_id: i32,
    pub base_id: i32,
    pub name: String,
    pub status: i32,
    pub speed: i32,
    pub x: i32,
    pub y: i32,
    pub level: i32,
    pub scene_id: String,
}

impl MapUnit {
    /// 工厂: 新建单位
    pub fn new(scene_id: String, base_id: i32, name: String, x: i32, y: i32) -> Self {
        Self {
            id: Uuid::new_v4(),
            battle_id: 0,
            base_id,
            name,
            status: 0,
            speed: 100,
            x,
            y,
            level: 1,
            scene_id,
        }
    }

    /// 业务规则: 移动
    pub fn move_to(&mut self, x: i32, y: i32) {
        self.x = x;
        self.y = y;
    }
}

/// 玩家空间 (per [游戏A] proto_103.erl 空间背景/签名)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SpaceInfo {
    pub player_id: Uuid,
    pub background_id: String,
    pub sign: String,
    pub visits: i32,
    pub likes: i32,
}

impl SpaceInfo {
    /// 工厂: 新建空间
    pub fn new(player_id: Uuid) -> Self {
        Self {
            player_id,
            background_id: "default".to_string(),
            sign: String::new(),
            visits: 0,
            likes: 0,
        }
    }

    /// 业务规则: 更新签名 (业务校验 ≤ 50 字符)
    pub fn update_sign(&mut self, sign: String) -> crate::Result<()> {
        if sign.chars().count() > 50 {
            return Err(crate::Error::Validation(
                "sign must be <= 50 characters".to_string(),
            ));
        }
        self.sign = sign;
        Ok(())
    }

    /// 业务规则: 设置背景
    pub fn set_background(&mut self, background_id: String) {
        self.background_id = background_id;
    }

    /// 业务规则: 增加访问
    pub fn add_visit(&mut self) {
        self.visits += 1;
    }
}
