// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "metrics.rs", type: "file", path: "crates/shared-platform/src/metrics.rs", crate: "shared-platform", module_path: "shared_platform::metrics", kind: "src", lines: 478}),
//   (n2:Module {name: "tests", type: "module", fqn: "shared_platform::metrics::tests", kind: "inline"}),
//   (n3:Class {name: "MetricsError", type: "class", fqn: "shared_platform::metrics::MetricsError", kind: "enum", visibility: "private", line: 34, attributes: "derive"}),
//   (n4:Class {name: "Metrics", type: "class", fqn: "shared_platform::metrics::Metrics", kind: "struct", visibility: "private", line: 64}),
//   (n5:Function {name: "registry", type: "function", fqn: "shared_platform::metrics::registry", kind: "fn", visibility: "private", signature: "fn registry() -> &'static Registry", line: 45}),
//   (n6:Function {name: "new", type: "function", fqn: "shared_platform::metrics::Metrics::new", kind: "method", visibility: "private", signature: "fn new() -> Result<Self, MetricsError>", line: 95}),
//   (n7:Function {name: "record_http_request", type: "function", fqn: "shared_platform::metrics::Metrics::record_http_request", kind: "method", visibility: "private", signature: "fn record_http_request(&self, service: &str, method: &str, status: &str)", line: 208}),
//   (n8:Function {name: "record_http_duration", type: "function", fqn: "shared_platform::metrics::Metrics::record_http_duration", kind: "method", visibility: "private", signature: "fn record_http_duration(&self, service: &str, method: &str, duration_secs: f64)", line: 215}),
//   (n9:Function {name: "set_saga_state", type: "function", fqn: "shared_platform::metrics::Metrics::set_saga_state", kind: "method", visibility: "private", signature: "fn set_saga_state(&self, saga_type: &str, status: &str, count: i64)", line: 222}),
//   (n10:Function {name: "set_outbox_pending", type: "function", fqn: "shared_platform::metrics::Metrics::set_outbox_pending", kind: "method", visibility: "private", signature: "fn set_outbox_pending(&self, service: &str, aggregate_type: &str, count: i64)", line: 231}),
//   (n11:Function {name: "set_outbox_inflight", type: "function", fqn: "shared_platform::metrics::Metrics::set_outbox_inflight", kind: "method", visibility: "private", signature: "fn set_outbox_inflight(&self, service: &str, aggregate_type: &str, count: i64)", line: 238}),
//   (n12:Function {name: "set_outbox_inflight_lease_lag", type: "function", fqn: "shared_platform::metrics::Metrics::set_outbox_inflight_lease_lag", kind: "method", visibility: "private", signature: "fn set_outbox_inflight_lease_lag(&self, service: &str, max_lag_secs: f64)", line: 245}),
//   (n13:Function {name: "set_outbox_failed", type: "function", fqn: "shared_platform::metrics::Metrics::set_outbox_failed", kind: "method", visibility: "private", signature: "fn set_outbox_failed(&self, service: &str, aggregate_type: &str, count: i64)", line: 252}),
//   (n14:Function {name: "observe_outbox_poll_cycle_duration", type: "function", fqn: "shared_platform::metrics::Metrics::observe_outbox_poll_cycle_duration", kind: "method", visibility: "private", signature: "fn observe_outbox_poll_cycle_duration(&self, service: &str, secs: f64)", line: 259}),
//   (n15:Function {name: "record_outbox_publish", type: "function", fqn: "shared_platform::metrics::Metrics::record_outbox_publish", kind: "method", visibility: "private", signature: "fn record_outbox_publish(&self, service: &str, aggregate_type: &str, result: &str)", line: 269}),
//   (n16:Function {name: "observe_outbox_event_age", type: "function", fqn: "shared_platform::metrics::Metrics::observe_outbox_event_age", kind: "method", visibility: "private", signature: "fn observe_outbox_event_age(&self, service: &str, aggregate_type: &str, secs: f64)", line: 276}),
//   (n17:Function {name: "observe_outbox_batch_size", type: "function", fqn: "shared_platform::metrics::Metrics::observe_outbox_batch_size", kind: "method", visibility: "private", signature: "fn observe_outbox_batch_size(&self, service: &str, count: usize)", line: 283}),
//   (n18:Function {name: "set_outbox_oldest_pending_created_at", type: "function", fqn: "shared_platform::metrics::Metrics::set_outbox_oldest_pending_created_at", kind: "method", visibility: "private", signature: "fn set_outbox_oldest_pending_created_at(&self, service: &str, unix_secs: f64)", line: 290}),
//   (n19:Function {name: "metrics", type: "function", fqn: "shared_platform::metrics::metrics", kind: "fn", visibility: "private", signature: "fn metrics() -> &'static Metrics", line: 301}),
//   (n20:Function {name: "encode_to_text", type: "function", fqn: "shared_platform::metrics::encode_to_text", kind: "fn", visibility: "private", signature: "fn encode_to_text() -> Result<String, MetricsError>", line: 306}),
//   (n21:Function {name: "global_metrics_init_works", type: "function", fqn: "shared_platform::metrics::global_metrics_init_works", kind: "test", visibility: "private", signature: "fn global_metrics_init_works()", line: 318, attributes: "test"}),
//   (n22:Function {name: "global_metrics_idempotent", type: "function", fqn: "shared_platform::metrics::global_metrics_idempotent", kind: "test", visibility: "private", signature: "fn global_metrics_idempotent()", line: 327, attributes: "test"}),
//   (n23:Function {name: "encode_to_text_works", type: "function", fqn: "shared_platform::metrics::encode_to_text_works", kind: "test", visibility: "private", signature: "fn encode_to_text_works()", line: 333, attributes: "test"}),
//   (n24:Function {name: "record_http_request_increments_counter", type: "function", fqn: "shared_platform::metrics::record_http_request_increments_counter", kind: "test", visibility: "private", signature: "fn record_http_request_increments_counter()", line: 349, attributes: "test"}),
//   (n25:Function {name: "set_saga_state_visible_in_text_format", type: "function", fqn: "shared_platform::metrics::set_saga_state_visible_in_text_format", kind: "test", visibility: "private", signature: "fn set_saga_state_visible_in_text_format()", line: 361, attributes: "test"}),
//   (n26:Function {name: "set_outbox_pending_negative_value_works", type: "function", fqn: "shared_platform::metrics::set_outbox_pending_negative_value_works", kind: "test", visibility: "private", signature: "fn set_outbox_pending_negative_value_works()", line: 370, attributes: "test"}),
//   (n27:Function {name: "record_http_duration_records_histogram", type: "function", fqn: "shared_platform::metrics::record_http_duration_records_histogram", kind: "test", visibility: "private", signature: "fn record_http_duration_records_histogram()", line: 379, attributes: "test"}),
//   (n28:Function {name: "outbox_pending_gauge_emits_service_and_aggregate_type_labels", type: "function", fqn: "shared_platform::metrics::outbox_pending_gauge_emits_service_and_aggregate_type_labels", kind: "test", visibility: "private", signature: "fn outbox_pending_gauge_emits_service_and_aggregate_type_labels()", line: 391, attributes: "test"}),
//   (n29:Function {name: "outbox_inflight_count_and_lease_lag_gauge_work", type: "function", fqn: "shared_platform::metrics::outbox_inflight_count_and_lease_lag_gauge_work", kind: "test", visibility: "private", signature: "fn outbox_inflight_count_and_lease_lag_gauge_work()", line: 405, attributes: "test"}),
//   (n30:Function {name: "outbox_failed_gauge_emits_correctly", type: "function", fqn: "shared_platform::metrics::outbox_failed_gauge_emits_correctly", kind: "test", visibility: "private", signature: "fn outbox_failed_gauge_emits_correctly()", line: 417, attributes: "test"}),
//   (n31:Function {name: "outbox_relay_publish_total_records_all_three_results", type: "function", fqn: "shared_platform::metrics::outbox_relay_publish_total_records_all_three_results", kind: "test", visibility: "private", signature: "fn outbox_relay_publish_total_records_all_three_results()", line: 427, attributes: "test"}),
//   (n32:Function {name: "outbox_event_age_histogram_observes", type: "function", fqn: "shared_platform::metrics::outbox_event_age_histogram_observes", kind: "test", visibility: "private", signature: "fn outbox_event_age_histogram_observes()", line: 440, attributes: "test"}),
//   (n33:Function {name: "outbox_batch_size_histogram_observes", type: "function", fqn: "shared_platform::metrics::outbox_batch_size_histogram_observes", kind: "test", visibility: "private", signature: "fn outbox_batch_size_histogram_observes()", line: 450, attributes: "test"}),
//   (n34:Function {name: "outbox_poll_cycle_duration_histogram_observes", type: "function", fqn: "shared_platform::metrics::outbox_poll_cycle_duration_histogram_observes", kind: "test", visibility: "private", signature: "fn outbox_poll_cycle_duration_histogram_observes()", line: 461, attributes: "test"}),
//   (n35:Function {name: "outbox_oldest_pending_created_at_gauge_works", type: "function", fqn: "shared_platform::metrics::outbox_oldest_pending_created_at_gauge_works", kind: "test", visibility: "private", signature: "fn outbox_oldest_pending_created_at_gauge_works()", line: 471, attributes: "test"}),
//   (n36:Variable {name: "DEFAULT_BUCKETS", type: "variable", fqn: "shared_platform::metrics::DEFAULT_BUCKETS", kind: "const", visibility: "private", line: 53}),
//   (n37:Variable {name: "BATCH_SIZE_BUCKETS", type: "variable", fqn: "shared_platform::metrics::BATCH_SIZE_BUCKETS", kind: "const", visibility: "private", line: 56}),
//   (n38:Variable {name: "EVENT_AGE_BUCKETS", type: "variable", fqn: "shared_platform::metrics::EVENT_AGE_BUCKETS", kind: "const", visibility: "private", line: 59}),
//   (n39:Variable {name: "REGISTRY", type: "variable", fqn: "shared_platform::metrics::REGISTRY", kind: "static", visibility: "private", line: 43}),
//   (n40:Variable {name: "METRICS", type: "variable", fqn: "shared_platform::metrics::METRICS", kind: "static", visibility: "private", line: 298});
// MERGE (x1:Module {name: "prometheus", type: "module"}) ON CREATE SET x1.fqn = "prometheus", x1.kind = "external_crate", x1.imports = "prometheus::CounterVec, prometheus::GaugeVec, prometheus::HistogramVec, prometheus::Registry, prometheus::register_counter_vec_with_registry, prometheus::register_gauge_vec_with_registry, prometheus::register_histogram_vec_with_registry, prometheus::TextEncoder::new";
// MERGE (x2:Module {name: "thiserror", type: "module"}) ON CREATE SET x2.fqn = "thiserror", x2.kind = "external_crate", x2.imports = "thiserror::Error";
// MERGE (x3:Module {name: "std", type: "module"}) ON CREATE SET x3.fqn = "std", x3.kind = "external_crate", x3.imports = "std::sync::OnceLock";
// MERGE (x4:Module {name: "core", type: "module"}) ON CREATE SET x4.fqn = "core", x4.kind = "external_crate", x4.imports = "core::result::Result";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n4)-[:HAS_METHOD]->(n6),
//   (n4)-[:HAS_METHOD]->(n7),
//   (n4)-[:HAS_METHOD]->(n8),
//   (n4)-[:HAS_METHOD]->(n9),
//   (n4)-[:HAS_METHOD]->(n10),
//   (n4)-[:HAS_METHOD]->(n11),
//   (n4)-[:HAS_METHOD]->(n12),
//   (n4)-[:HAS_METHOD]->(n13),
//   (n4)-[:HAS_METHOD]->(n14),
//   (n4)-[:HAS_METHOD]->(n15),
//   (n4)-[:HAS_METHOD]->(n16),
//   (n4)-[:HAS_METHOD]->(n17),
//   (n4)-[:HAS_METHOD]->(n18),
//   (n1)-[:CONTAINS]->(n19),
//   (n1)-[:CONTAINS]->(n20),
//   (n1)-[:CONTAINS]->(n21),
//   (n1)-[:CONTAINS]->(n22),
//   (n1)-[:CONTAINS]->(n23),
//   (n1)-[:CONTAINS]->(n24),
//   (n1)-[:CONTAINS]->(n25),
//   (n1)-[:CONTAINS]->(n26),
//   (n1)-[:CONTAINS]->(n27),
//   (n1)-[:CONTAINS]->(n28),
//   (n1)-[:CONTAINS]->(n29),
//   (n1)-[:CONTAINS]->(n30),
//   (n1)-[:CONTAINS]->(n31),
//   (n1)-[:CONTAINS]->(n32),
//   (n1)-[:CONTAINS]->(n33),
//   (n1)-[:CONTAINS]->(n34),
//   (n1)-[:CONTAINS]->(n35),
//   (n1)-[:CONTAINS]->(n36),
//   (n1)-[:CONTAINS]->(n37),
//   (n1)-[:CONTAINS]->(n38),
//   (n1)-[:CONTAINS]->(n39),
//   (n1)-[:CONTAINS]->(n40),
//   (n2)-[:CONTAINS]->(n21),
//   (n2)-[:CONTAINS]->(n22),
//   (n2)-[:CONTAINS]->(n23),
//   (n2)-[:CONTAINS]->(n24),
//   (n2)-[:CONTAINS]->(n25),
//   (n2)-[:CONTAINS]->(n26),
//   (n2)-[:CONTAINS]->(n27),
//   (n2)-[:CONTAINS]->(n28),
//   (n2)-[:CONTAINS]->(n29),
//   (n2)-[:CONTAINS]->(n30),
//   (n2)-[:CONTAINS]->(n31),
//   (n2)-[:CONTAINS]->(n32),
//   (n2)-[:CONTAINS]->(n33),
//   (n2)-[:CONTAINS]->(n34),
//   (n2)-[:CONTAINS]->(n35),
//   (n1)-[:USES, import: "prometheus::CounterVec"]->(x1),
//   (n1)-[:USES, import: "thiserror::Error"]->(x2),
//   (n1)-[:USES, import: "prometheus::GaugeVec"]->(x1),
//   (n1)-[:USES, import: "prometheus::HistogramVec"]->(x1),
//   (n1)-[:USES, import: "std::sync::OnceLock"]->(x3),
//   (n1)-[:USES, import: "prometheus::Registry"]->(x1),
//   (n1)-[:USES, import: "prometheus::register_counter_vec_with_registry"]->(x1),
//   (n1)-[:USES, import: "prometheus::register_gauge_vec_with_registry"]->(x1),
//   (n1)-[:USES, import: "prometheus::register_histogram_vec_with_registry"]->(x1),
//   (n6)-[:CALLS]->(n5),
//   (n6)-[:USES, via: "shared_platform::metrics::MetricsError"]->(n3),
//   (n6)-[:USES, via: "core::result::Result"]->(x4),
//   (n19)-[:CALLS, via: "shared_platform::metrics::Metrics::new"]->(n6),
//   (n20)-[:USES, via: "prometheus::TextEncoder::new"]->(x1),
//   (n20)-[:CALLS]->(n5),
//   (n20)-[:USES, via: "shared_platform::metrics::MetricsError"]->(n3),
//   (n21)-[:CALLS]->(n19),
//   (n22)-[:CALLS]->(n19),
//   (n23)-[:CALLS]->(n19),
//   (n23)-[:CALLS]->(n20),
//   (n24)-[:CALLS]->(n19),
//   (n24)-[:CALLS]->(n20),
//   (n25)-[:CALLS]->(n19),
//   (n25)-[:CALLS]->(n20),
//   (n26)-[:CALLS]->(n19),
//   (n26)-[:CALLS]->(n20),
//   (n27)-[:CALLS]->(n19),
//   (n27)-[:CALLS]->(n20),
//   (n28)-[:CALLS]->(n19),
//   (n28)-[:CALLS]->(n20),
//   (n29)-[:CALLS]->(n19),
//   (n29)-[:CALLS]->(n20),
//   (n30)-[:CALLS]->(n19),
//   (n30)-[:CALLS]->(n20),
//   (n31)-[:CALLS]->(n19),
//   (n31)-[:CALLS]->(n20),
//   (n32)-[:CALLS]->(n19),
//   (n32)-[:CALLS]->(n20),
//   (n33)-[:CALLS]->(n19),
//   (n33)-[:CALLS]->(n20),
//   (n34)-[:CALLS]->(n19),
//   (n34)-[:CALLS]->(n20),
//   (n35)-[:CALLS]->(n19),
//   (n35)-[:CALLS]->(n20);
// ```
// ==== END CYPHER HEADER ====
//! Prometheus Metrics（per RGS-ARC-051 集群运营中心观测 + ULYS-100 P2-#2 outbox）
//!
//! 54.13 实化：MetricsRegistry + 4 个核心指标 + 业务 helper
//! ULYS-100 扩展：8 个 outbox 专项指标 + 业务 helper
//!   (per docs/00-基准与治理/ULYS-56-follow-up-drafts/06_Outbox监控指标草案.md §1.1+§1.2)
//!
//! 设计：
//! - 全局 MetricsRegistry 单例（OnceCell）
//! - HTTP / Saga 核心指标：rgs_http_requests_total / rgs_http_request_duration_seconds / rgs_saga_state_count
//! - Outbox 8 指标：
//!   * rgs_outbox_pending_count{service, aggregate_type}         Gauge   条
//!   * rgs_outbox_inflight_count{service, aggregate_type}        Gauge   条
//!   * rgs_outbox_inflight_lease_lag_seconds{service}            Gauge   秒（最大 lease 剩余时间）
//!   * rgs_outbox_failed_count{service, aggregate_type}          Gauge   条
//!   * rgs_outbox_relay_poll_cycle_duration_seconds{service}     Histogram 秒
//!   * rgs_outbox_relay_publish_total{service, aggregate_type, result}  Counter
//!   * rgs_outbox_event_age_seconds{service, aggregate_type}     Histogram 秒（created_at→sent_at）
//!   * rgs_outbox_batch_size{service}                            Histogram 条
//!   * rgs_outbox_oldest_pending_created_at_seconds{service}    Gauge   unix_ts（供 recording rule 派生 age）
//! - 业务 helper：record_http_request / record_saga_state / record_outbox_publish /
//!                observe_outbox_event_age / observe_outbox_poll_cycle / observe_outbox_batch_size /
//!                set_outbox_gauge (Pending/Inflight/Failed) / set_outbox_lease_lag / set_outbox_oldest_pending_created_at
//! - 导出：encode_to_text() → Prometheus text format (scrape 端读取)

use prometheus::{
    register_counter_vec_with_registry, register_gauge_vec_with_registry,
    register_histogram_vec_with_registry, CounterVec, GaugeVec, HistogramVec, Registry,
};
use std::sync::OnceLock;
use thiserror::Error;

/// Metrics 错误
#[derive(Debug, Error)]
pub enum MetricsError {
    #[error("Prometheus encoding error: {0}")]
    Encoding(String),

    #[error("Prometheus register error: {0}")]
    Register(String),
}

/// 全局 Registry（per RGS-SPEC-CROSS-008 草案）
static REGISTRY: OnceLock<Registry> = OnceLock::new();

fn registry() -> &'static Registry {
    REGISTRY.get_or_init(Registry::new)
}

/// Histogram 默认桶（per 06_Outbox监控指标草案.md §2 阈值分布）
///
/// - HTTP: 1ms..10s（既有 54.13 默认）
/// - Outbox poll cycle / event age / batch size: 同区间复用
const DEFAULT_BUCKETS: &[f64] = &[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0];

/// Batch size 桶（per 草案 §1.2 批量范围）
const BATCH_SIZE_BUCKETS: &[f64] = &[1.0, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0, 1000.0];

/// Event age 桶（草案 §1.2 端到端延迟，秒）
const EVENT_AGE_BUCKETS: &[f64] = &[
    0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 300.0,
];

/// 指标容器（每个进程一个）
pub struct Metrics {
    /// HTTP 请求计数（按 service / method / status 分桶）
    pub http_requests: CounterVec,
    /// HTTP 请求延迟（秒）
    pub http_request_duration: HistogramVec,
    /// Saga 状态计数（按 service / saga_type / status）
    pub saga_state: GaugeVec,

    // ============ ULYS-100 outbox 指标 ============
    /// 当前 `status = 'Pending'` 的 outbox 行数（service × aggregate_type）
    pub outbox_pending: GaugeVec,
    /// 当前 `status = 'InFlight'` 且 lease 仍有效的 outbox 行数
    pub outbox_inflight: GaugeVec,
    /// InFlight 行 lease 剩余时间最大值（秒；接近 30s = 接近过期）
    pub outbox_inflight_lease_lag: GaugeVec,
    /// 当前 `status = 'Failed'` 的 outbox 行数
    pub outbox_failed: GaugeVec,
    /// 单次轮询周期耗时（list_pending + publish + mark_sent/_failed 全过程）
    pub outbox_relay_poll_cycle_duration: HistogramVec,
    /// Relay 发布次数（result = success / failure / timeout）
    pub outbox_relay_publish: CounterVec,
    /// outbox 端到端延迟（created_at → sent_at），仅成功 publish 后 observe
    pub outbox_event_age: HistogramVec,
    /// 单次轮询批量大小（list_pending LIMIT N 返回的条数）
    pub outbox_batch_size: HistogramVec,
    /// 最旧 Pending 行的 created_at unix 秒（供 recording rule 派生 `time() - oldest_pending_age_seconds`）
    pub outbox_oldest_pending_created_at: GaugeVec,
}

impl Metrics {
    /// 注册所有指标
    pub fn new() -> Result<Self, MetricsError> {
        let reg = registry();
        let http_requests = register_counter_vec_with_registry!(
            "rgs_http_requests_total",
            "Total HTTP/gRPC requests",
            &["service", "method", "status"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let http_request_duration = register_histogram_vec_with_registry!(
            "rgs_http_request_duration_seconds",
            "HTTP/gRPC request duration in seconds",
            &["service", "method"],
            DEFAULT_BUCKETS.to_vec(),
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let saga_state = register_gauge_vec_with_registry!(
            "rgs_saga_state_count",
            "Saga state count by status",
            &["saga_type", "status"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;

        // ----- ULYS-100 P2-#2 outbox 8 + 1 指标 -----
        // 注：pending / inflight / failed 沿用 06_草案 §1.1 标签集 {service, aggregate_type}
        //     lease_lag / oldest_pending 只按 service 聚合（per §1.1 单 label 形式）
        //     relay_publish_total 含 result 维度
        let outbox_pending = register_gauge_vec_with_registry!(
            "rgs_outbox_pending_count",
            "Outbox pending entry count (status=pending) by service and aggregate_type",
            &["service", "aggregate_type"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_inflight = register_gauge_vec_with_registry!(
            "rgs_outbox_inflight_count",
            "Outbox in-flight entry count (status=in_flight AND lease_until>NOW()) by service and aggregate_type",
            &["service", "aggregate_type"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_inflight_lease_lag = register_gauge_vec_with_registry!(
            "rgs_outbox_inflight_lease_lag_seconds",
            "Max remaining lease seconds across in-flight outbox rows by service (approaching 30s = nearing reclaim)",
            &["service"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_failed = register_gauge_vec_with_registry!(
            "rgs_outbox_failed_count",
            "Outbox failed entry count (status=failed, retry_count >= max) by service and aggregate_type",
            &["service", "aggregate_type"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_relay_poll_cycle_duration = register_histogram_vec_with_registry!(
            "rgs_outbox_relay_poll_cycle_duration_seconds",
            "Outbox relay single poll cycle duration (list_pending + publish batch + mark_sent/_failed)",
            &["service"],
            DEFAULT_BUCKETS.to_vec(),
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_relay_publish = register_counter_vec_with_registry!(
            "rgs_outbox_relay_publish_total",
            "Outbox relay publish attempts (result=success|failure|timeout)",
            &["service", "aggregate_type", "result"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_event_age = register_histogram_vec_with_registry!(
            "rgs_outbox_event_age_seconds",
            "Outbox end-to-end latency from created_at to sent_at (per published entry)",
            &["service", "aggregate_type"],
            EVENT_AGE_BUCKETS.to_vec(),
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_batch_size = register_histogram_vec_with_registry!(
            "rgs_outbox_batch_size",
            "Outbox relay single poll batch size (number of entries fetched per tick)",
            &["service"],
            BATCH_SIZE_BUCKETS.to_vec(),
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;
        let outbox_oldest_pending_created_at = register_gauge_vec_with_registry!(
            "rgs_outbox_oldest_pending_created_at_seconds",
            "Unix timestamp of oldest pending outbox entry (per service); use recording rule time()-gauge to derive age_seconds",
            &["service"],
            reg
        )
        .map_err(|e| MetricsError::Register(e.to_string()))?;

        Ok(Self {
            http_requests,
            http_request_duration,
            saga_state,
            outbox_pending,
            outbox_inflight,
            outbox_inflight_lease_lag,
            outbox_failed,
            outbox_relay_poll_cycle_duration,
            outbox_relay_publish,
            outbox_event_age,
            outbox_batch_size,
            outbox_oldest_pending_created_at,
        })
    }

    /// 业务 helper：记录 HTTP 请求
    pub fn record_http_request(&self, service: &str, method: &str, status: &str) {
        self.http_requests
            .with_label_values(&[service, method, status])
            .inc();
    }

    /// 业务 helper：记录 HTTP 延迟
    pub fn record_http_duration(&self, service: &str, method: &str, duration_secs: f64) {
        self.http_request_duration
            .with_label_values(&[service, method])
            .observe(duration_secs);
    }

    /// 业务 helper：记录 Saga 状态变化
    pub fn set_saga_state(&self, saga_type: &str, status: &str, count: i64) {
        self.saga_state
            .with_label_values(&[saga_type, status])
            .set(count as f64);
    }

    // ============ ULYS-100 outbox 业务 helper ============

    /// 设置当前 Pending 计数（per service × aggregate_type）
    pub fn set_outbox_pending(&self, service: &str, aggregate_type: &str, count: i64) {
        self.outbox_pending
            .with_label_values(&[service, aggregate_type])
            .set(count as f64);
    }

    /// 设置当前 InFlight 计数
    pub fn set_outbox_inflight(&self, service: &str, aggregate_type: &str, count: i64) {
        self.outbox_inflight
            .with_label_values(&[service, aggregate_type])
            .set(count as f64);
    }

    /// 设置 InFlight 行 lease 剩余秒数最大值（per service 单 label 聚合）
    pub fn set_outbox_inflight_lease_lag(&self, service: &str, max_lag_secs: f64) {
        self.outbox_inflight_lease_lag
            .with_label_values(&[service])
            .set(max_lag_secs);
    }

    /// 设置当前 Failed 计数
    pub fn set_outbox_failed(&self, service: &str, aggregate_type: &str, count: i64) {
        self.outbox_failed
            .with_label_values(&[service, aggregate_type])
            .set(count as f64);
    }

    /// 观察 relay 单次轮询周期耗时（秒）
    pub fn observe_outbox_poll_cycle_duration(&self, service: &str, secs: f64) {
        self.outbox_relay_poll_cycle_duration
            .with_label_values(&[service])
            .observe(secs);
    }

    /// 记录 relay 发布尝试计数
    ///
    /// `result` 必须是 `"success"` / `"failure"` / `"timeout"` 之一
    /// （per 06_草案 §1.1 + 派生 recording rule `rgs_outbox_publish_failure_rate_5m`）
    pub fn record_outbox_publish(&self, service: &str, aggregate_type: &str, result: &str) {
        self.outbox_relay_publish
            .with_label_values(&[service, aggregate_type, result])
            .inc();
    }

    /// 观察 outbox 端到端延迟（成功 publish 后由 relay 调用；created_at→sent_at）
    pub fn observe_outbox_event_age(&self, service: &str, aggregate_type: &str, secs: f64) {
        self.outbox_event_age
            .with_label_values(&[service, aggregate_type])
            .observe(secs);
    }

    /// 观察单次轮询批量大小
    pub fn observe_outbox_batch_size(&self, service: &str, count: usize) {
        self.outbox_batch_size
            .with_label_values(&[service])
            .observe(count as f64);
    }

    /// 设置最旧 Pending 行 created_at unix 秒（per service；供 recording rule 派生 age）
    pub fn set_outbox_oldest_pending_created_at(&self, service: &str, unix_secs: f64) {
        self.outbox_oldest_pending_created_at
            .with_label_values(&[service])
            .set(unix_secs);
    }
}

/// 全局 Metrics 实例（per process 共享）
static METRICS: OnceLock<Metrics> = OnceLock::new();

/// 获取全局 Metrics（lazy init）
pub fn metrics() -> &'static Metrics {
    METRICS.get_or_init(|| Metrics::new().expect("metrics init"))
}

/// 编码为 Prometheus text format
pub fn encode_to_text() -> Result<String, MetricsError> {
    let encoder = prometheus::TextEncoder::new();
    encoder
        .encode_to_string(&registry().gather())
        .map_err(|e| MetricsError::Encoding(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn global_metrics_init_works() {
        let m = metrics();
        m.record_http_request("test", "ping", "200");
        m.record_http_duration("test", "ping", 0.001);
        m.set_saga_state("transfer", "running", 3);
        m.set_outbox_pending("economy", "economy.transfer", 5);
    }

    #[test]
    fn global_metrics_idempotent() {
        let _ = metrics();
        let _ = metrics();
    }

    #[test]
    fn encode_to_text_works() {
        let m = metrics();
        m.record_http_request("test", "ping", "200");
        m.record_http_duration("test", "ping", 0.001);
        m.set_saga_state("transfer", "running", 3);
        m.set_outbox_pending("economy", "economy.transfer", 5);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_http_requests_total"));
        assert!(text.contains("rgs_saga_state_count"));
        assert!(text.contains("rgs_outbox_pending_count"));
    }

    // ---- 9/1 pt/shared-platform worker 派工 (per PT-WORKER-BRIEFING.md §2) ----
    // Prometheus 指标是 ARC-051 集群运营中心入口, 加 4 单测

    #[test]
    fn record_http_request_increments_counter() {
        // 同一 label 多次 inc, Prometheus 输出应包含样例
        let m = metrics();
        for _ in 0..3 {
            m.record_http_request("unit-test-svc", "GET", "200");
        }
        let text = encode_to_text().unwrap();
        assert!(text.contains("unit-test-svc"));
        assert!(text.contains("rgs_http_requests_total"));
    }

    #[test]
    fn set_saga_state_visible_in_text_format() {
        let m = metrics();
        m.set_saga_state("test-saga", "completed", 42);
        let text = encode_to_text().unwrap();
        assert!(text.contains("test-saga"));
        assert!(text.contains("rgs_saga_state_count"));
    }

    #[test]
    fn set_outbox_pending_negative_value_works() {
        // Gauge 支持负数 (虽然业务上不会, 但 Prometheus 允许)
        let m = metrics();
        m.set_outbox_pending("test-domain", "test-domain.unknown", -1);
        let text = encode_to_text().unwrap();
        assert!(text.contains("test-domain"));
    }

    #[test]
    fn record_http_duration_records_histogram() {
        let m = metrics();
        m.record_http_duration("test-dur-svc", "Slow", 0.123);
        m.record_http_duration("test-dur-svc", "Fast", 0.001);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_http_request_duration_seconds"));
        assert!(text.contains("test-dur-svc"));
    }

    // ============ ULYS-100 P2-#2 outbox metrics tests ============

    #[test]
    fn outbox_pending_gauge_emits_service_and_aggregate_type_labels() {
        let m = metrics();
        m.set_outbox_pending("economy", "economy.transfer", 42);
        m.set_outbox_pending("economy", "economy.credit", 7);
        m.set_outbox_pending("player", "player.registered", 100);
        let text = encode_to_text().unwrap();
        // service × aggregate_type 标签都在
        assert!(text.contains("rgs_outbox_pending_count"));
        assert!(text.contains("service=\"economy\""));
        assert!(text.contains("aggregate_type=\"economy.transfer\""));
        assert!(text.contains("service=\"player\""));
    }

    #[test]
    fn outbox_inflight_count_and_lease_lag_gauge_work() {
        let m = metrics();
        m.set_outbox_inflight("admin", "admin.lcm", 15);
        m.set_outbox_inflight_lease_lag("admin", 25.5);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_outbox_inflight_count"));
        assert!(text.contains("service=\"admin\""));
        assert!(text.contains("aggregate_type=\"admin.lcm\""));
        assert!(text.contains("rgs_outbox_inflight_lease_lag_seconds"));
    }

    #[test]
    fn outbox_failed_gauge_emits_correctly() {
        let m = metrics();
        m.set_outbox_failed("match", "match.matchmake", 3);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_outbox_failed_count"));
        assert!(text.contains("service=\"match\""));
        assert!(text.contains("aggregate_type=\"match.matchmake\""));
    }

    #[test]
    fn outbox_relay_publish_total_records_all_three_results() {
        let m = metrics();
        m.record_outbox_publish("economy", "economy.transfer", "success");
        m.record_outbox_publish("economy", "economy.transfer", "failure");
        m.record_outbox_publish("economy", "economy.transfer", "timeout");
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_outbox_relay_publish_total"));
        assert!(text.contains("result=\"success\""));
        assert!(text.contains("result=\"failure\""));
        assert!(text.contains("result=\"timeout\""));
    }

    #[test]
    fn outbox_event_age_histogram_observes() {
        let m = metrics();
        m.observe_outbox_event_age("social", "social.friend", 0.5);
        m.observe_outbox_event_age("social", "social.friend", 2.5);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_outbox_event_age_seconds"));
        assert!(text.contains("rgs_outbox_event_age_seconds_bucket"));
    }

    #[test]
    fn outbox_batch_size_histogram_observes() {
        let m = metrics();
        m.observe_outbox_batch_size("player", 0);
        m.observe_outbox_batch_size("player", 50);
        m.observe_outbox_batch_size("player", 200);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_outbox_batch_size"));
        assert!(text.contains("rgs_outbox_batch_size_bucket"));
    }

    #[test]
    fn outbox_poll_cycle_duration_histogram_observes() {
        let m = metrics();
        m.observe_outbox_poll_cycle_duration("cluster_ops", 0.05);
        m.observe_outbox_poll_cycle_duration("cluster_ops", 1.5);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_outbox_relay_poll_cycle_duration_seconds"));
        assert!(text.contains("rgs_outbox_relay_poll_cycle_duration_seconds_bucket"));
    }

    #[test]
    fn outbox_oldest_pending_created_at_gauge_works() {
        let m = metrics();
        m.set_outbox_oldest_pending_created_at("admin", 1_700_000_000.0);
        let text = encode_to_text().unwrap();
        assert!(text.contains("rgs_outbox_oldest_pending_created_at_seconds"));
        assert!(text.contains("1700000000"));
    }
}
