// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "entity.rs", type: "file", path: "crates/i18n-service/src/entity.rs", crate: "i18n-service", module_path: "i18n_service::entity", kind: "src", lines: 132}),
//   (n2:Module {name: "tests", type: "module", fqn: "i18n_service::entity::tests", kind: "inline"}),
//   (n3:Class {name: "Locale", type: "class", fqn: "i18n_service::entity::Locale", kind: "enum", visibility: "private", line: 17, attributes: "derive, serde"}),
//   (n4:Class {name: "I18nText", type: "class", fqn: "i18n_service::entity::I18nText", kind: "struct", visibility: "private", line: 57, attributes: "derive"}),
//   (n5:Class {name: "LanguageInfo", type: "class", fqn: "i18n_service::entity::LanguageInfo", kind: "struct", visibility: "private", line: 85, attributes: "derive"}),
//   (n6:Function {name: "as_str", type: "function", fqn: "i18n_service::entity::Locale::as_str", kind: "method", visibility: "private", signature: "fn as_str(&self) -> &'static str", line: 25}),
//   (n7:Function {name: "from_str", type: "function", fqn: "i18n_service::entity::Locale::from_str", kind: "method", visibility: "private", signature: "fn from_str(s: &str) -> Option<Self>", line: 34}),
//   (n8:Function {name: "default_locale", type: "function", fqn: "i18n_service::entity::Locale::default_locale", kind: "method", visibility: "private", signature: "fn default_locale() -> Self", line: 45}),
//   (n9:Function {name: "fallback_locale", type: "function", fqn: "i18n_service::entity::Locale::fallback_locale", kind: "method", visibility: "private", signature: "fn fallback_locale() -> Self", line: 50}),
//   (n10:Function {name: "new", type: "function", fqn: "i18n_service::entity::I18nText::new", kind: "method", visibility: "private", signature: "fn new(key: String, locale: Locale, text: String) -> Self", line: 71}),
//   (n11:Function {name: "new", type: "function", fqn: "i18n_service::entity::LanguageInfo::new", kind: "method", visibility: "private", signature: "fn new(locale: Locale, display_name: String, is_default: bool, enabled: bool) -> Self", line: 96}),
//   (n12:Function {name: "locale_roundtrip", type: "function", fqn: "i18n_service::entity::locale_roundtrip", kind: "test", visibility: "private", signature: "fn locale_roundtrip()", line: 111, attributes: "test"}),
//   (n13:Function {name: "locale_default_is_zh_cn", type: "function", fqn: "i18n_service::entity::locale_default_is_zh_cn", kind: "test", visibility: "private", signature: "fn locale_default_is_zh_cn()", line: 120, attributes: "test"}),
//   (n14:Function {name: "i18n_text_factory_initializes_timestamps", type: "function", fqn: "i18n_service::entity::i18n_text_factory_initializes_timestamps", kind: "test", visibility: "private", signature: "fn i18n_text_factory_initializes_timestamps()", line: 126, attributes: "test"});
// MERGE (x1:Module {name: "chrono", type: "module"}) ON CREATE SET x1.fqn = "chrono", x1.kind = "external_crate", x1.imports = "chrono::DateTime, chrono::Utc, chrono::Utc::now";
// MERGE (x2:Module {name: "serde", type: "module"}) ON CREATE SET x2.fqn = "serde", x2.kind = "external_crate", x2.imports = "serde::Deserialize, serde::Serialize";
// MERGE (x3:Module {name: "core", type: "module"}) ON CREATE SET x3.fqn = "core", x3.kind = "external_crate", x3.imports = "core::option::Option";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n3)-[:HAS_METHOD]->(n6),
//   (n3)-[:HAS_METHOD]->(n7),
//   (n3)-[:HAS_METHOD]->(n8),
//   (n3)-[:HAS_METHOD]->(n9),
//   (n4)-[:HAS_METHOD]->(n10),
//   (n5)-[:HAS_METHOD]->(n11),
//   (n1)-[:CONTAINS]->(n12),
//   (n1)-[:CONTAINS]->(n13),
//   (n1)-[:CONTAINS]->(n14),
//   (n2)-[:CONTAINS]->(n12),
//   (n2)-[:CONTAINS]->(n13),
//   (n2)-[:CONTAINS]->(n14),
//   (n1)-[:USES, import: "chrono::DateTime"]->(x1),
//   (n1)-[:USES, import: "serde::Deserialize"]->(x2),
//   (n1)-[:USES, import: "serde::Serialize"]->(x2),
//   (n1)-[:USES, import: "chrono::Utc"]->(x1),
//   (n7)-[:USES, via: "core::option::Option"]->(x3),
//   (n10)-[:USES, via: "chrono::Utc::now"]->(x1),
//   (n12)-[:CALLS, via: "i18n_service::entity::Locale::from_str"]->(n7),
//   (n12)-[:USES, via: "core::option::Option"]->(x3),
//   (n13)-[:CALLS, via: "i18n_service::entity::Locale::default_locale"]->(n8),
//   (n13)-[:CALLS, via: "i18n_service::entity::Locale::fallback_locale"]->(n9),
//   (n14)-[:CALLS, via: "i18n_service::entity::I18nText::new"]->(n10);
// ```
// ==== END CYPHER HEADER ====
//! i18n-service 域 entity 定义
//!
//! 2 个核心 entity:
//! - Locale: 语言枚举 (zh_cn / en_us / ja_jp / ko_kr, per RGS-DTL-038 §4.1)
//! - I18nText: 单 key + locale 的文案条目
//! - LanguageInfo: 系统支持语言元数据
//!
//! 规范: RGS-REQ-038 §NFR-005 + RGS-DTL-038 §4.1 + DEC-038-05

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// 系统支持的语言 (与 common.proto v2 Locale enum 对齐)
/// locale string 格式: lowercase_underscore, e.g. "zh_cn"
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum Locale {
    ZhCn,
    EnUs,
    JaJp,
    KoKr,
}

impl Locale {
    pub fn as_str(&self) -> &'static str {
        match self {
            Locale::ZhCn => "zh_cn",
            Locale::EnUs => "en_us",
            Locale::JaJp => "ja_jp",
            Locale::KoKr => "ko_kr",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "zh_cn" => Some(Locale::ZhCn),
            "en_us" => Some(Locale::EnUs),
            "ja_jp" => Some(Locale::JaJp),
            "ko_kr" => Some(Locale::KoKr),
            _ => None,
        }
    }

    /// 默认 fallback locale (per RGS-DTL-038 §4.1: 默认 zh_cn, fallback en_us)
    pub fn default_locale() -> Self {
        Locale::ZhCn
    }

    /// 二级 fallback locale (per RGS-DTL-038 §4.1: zh_cn 缺失时回 en_us)
    pub fn fallback_locale() -> Self {
        Locale::EnUs
    }
}

/// 文案条目 (key, locale, text 三元组)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct I18nText {
    /// 文案 key, e.g. "card.shanghai.welcome"
    pub key: String,
    /// 语言
    pub locale: Locale,
    /// 文案内容
    pub text: String,
    /// 更新时间
    pub updated_at: DateTime<Utc>,
    /// 创建时间
    pub created_at: DateTime<Utc>,
}

impl I18nText {
    pub fn new(key: String, locale: Locale, text: String) -> Self {
        let now = Utc::now();
        Self {
            key,
            locale,
            text,
            updated_at: now,
            created_at: now,
        }
    }
}

/// 语言元数据 (per i18n_languages 表)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LanguageInfo {
    pub locale: Locale,
    /// 本地化显示名, e.g. "简体中文" / "English" / "日本語" / "한국어"
    pub display_name: String,
    /// 是否系统默认
    pub is_default: bool,
    /// 是否启用 (false = 客户端不应使用)
    pub enabled: bool,
}

impl LanguageInfo {
    pub fn new(locale: Locale, display_name: String, is_default: bool, enabled: bool) -> Self {
        Self {
            locale,
            display_name,
            is_default,
            enabled,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn locale_roundtrip() {
        for l in [Locale::ZhCn, Locale::EnUs, Locale::JaJp, Locale::KoKr] {
            assert_eq!(Locale::from_str(l.as_str()), Some(l));
        }
        assert_eq!(Locale::from_str("bogus"), None);
        assert_eq!(Locale::from_str("zh-CN"), None, "must be lowercase_underscore");
    }

    #[test]
    fn locale_default_is_zh_cn() {
        assert_eq!(Locale::default_locale(), Locale::ZhCn);
        assert_eq!(Locale::fallback_locale(), Locale::EnUs);
    }

    #[test]
    fn i18n_text_factory_initializes_timestamps() {
        let t = I18nText::new("k".to_string(), Locale::EnUs, "hello".to_string());
        assert_eq!(t.key, "k");
        assert_eq!(t.locale, Locale::EnUs);
        assert_eq!(t.text, "hello");
    }
}
