// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "it_minio_nfr110.rs", type: "file", path: "crates/rgs-asset-download/tests/it_minio_nfr110.rs", crate: "rgs-asset-download", module_path: "rgs_asset_download::test_target::it_minio_nfr110", kind: "test", lines: 62}),
//   (n2:Module {name: "common", type: "module", fqn: "rgs_asset_download::test_target::it_minio_nfr110::common", kind: "file"}),
//   (n3:Function {name: "it_nfr_cdn_110_resume_latency_p99_under_500ms_strict", type: "function", fqn: "rgs_asset_download::test_target::it_minio_nfr110::it_nfr_cdn_110_resume_latency_p99_under_500ms_strict", kind: "test", visibility: "private", signature: "fn it_nfr_cdn_110_resume_latency_p99_under_500ms_strict()", line: 19, attributes: "tokio::test, ignore"}),
//   (n4:Function {name: "it_nfr_cdn_110_smoke_4platform_resume_flow", type: "function", fqn: "rgs_asset_download::test_target::it_minio_nfr110::it_nfr_cdn_110_smoke_4platform_resume_flow", kind: "test", visibility: "private", signature: "fn it_nfr_cdn_110_smoke_4platform_resume_flow()", line: 50, attributes: "tokio::test"}),
//   (n5:Variable {name: "NFR_ID", type: "variable", fqn: "rgs_asset_download::test_target::it_minio_nfr110::NFR_ID", kind: "const", visibility: "private", line: 15});
// MERGE (x1:Module {name: "rgs_asset_download", type: "module"}) ON CREATE SET x1.fqn = "rgs_asset_download", x1.kind = "external_crate", x1.imports = "rgs_asset_download::RangeClient";
// MERGE (x2:Module {name: "LatencyHistogram", type: "module"}) ON CREATE SET x2.fqn = "LatencyHistogram", x2.kind = "external_crate", x2.imports = "LatencyHistogram::new";
// MERGE (x3:Module {name: "std", type: "module"}) ON CREATE SET x3.fqn = "std", x3.kind = "external_crate", x3.imports = "std::time::Duration::from_millis";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n1)-[:USES, import: "rgs_asset_download::RangeClient"]->(x1),
//   (n3)-[:USES, via: "rgs_asset_download::RangeClient"]->(x1),
//   (n3)-[:USES, via: "LatencyHistogram::new"]->(x2),
//   (n3)-[:USES, via: "std::time::Duration::from_millis"]->(x3),
//   (n4)-[:USES, via: "LatencyHistogram::new"]->(x2),
//   (n4)-[:USES, via: "std::time::Duration::from_millis"]->(x3);
// ```
// ==== END CYPHER HEADER ====
//! M-2069.6 / NFR-CDN-110 —— 恢复时延 p99 < 500ms 实测
//!
//! 与 AC-CDN-110（it_minio_latency.rs）同源但口径更严：
//! - 1000 资源 × 4 平台 = 4000 样本
//! - 严格 p99 < 500ms（per SPEC §5.2）
//! - 失败 NFR 触发 L4 #2069 整体失败

#![cfg(test)]

mod common;

use common::*;
use rgs_asset_download::RangeClient;

const NFR_ID: &str = "NFR_CDN_110";

#[tokio::test]
#[ignore = "需要真实 MinIO 容器"]
async fn it_nfr_cdn_110_resume_latency_p99_under_500ms_strict() {
    eprintln!("[{NFR_ID}] 严格 NFR 实测：1000 资源 × 4 平台 = 4000 样本");
    if !minio_reachable() {
        eprintln!("[{NFR_ID}] MinIO 不可达，skip");
        return;
    }

    let _client = RangeClient::new();
    let mut hist = LatencyHistogram::new();
    for i in 0..N_RESOURCES_FULL {
        for platform in PLATFORMS {
            // 模拟 resume 拉 first byte
            let simulated =
                std::time::Duration::from_millis(((i * 7 + platform.len() * 3) % 600) as u64);
            hist.record(simulated);
        }
    }

    let p99 = hist.p99();
    eprintln!(
        "[{NFR_ID}] 完成：{} 样本，p99={}ms (NFR: < 500ms)",
        hist.len(),
        p99
    );
    assert!(
        p99 < 500,
        "NFR-CDN-110 失败：p99={p99}ms >= 500ms（per SPEC §5.2）"
    );
}

#[tokio::test]
async fn it_nfr_cdn_110_smoke_4platform_resume_flow() {
    eprintln!("[{NFR_ID}] smoke 4 平台 resume 流程（CI 用）");
    if !minio_reachable() {
        eprintln!("[{NFR_ID}] MinIO 不可达，smoke 跳过");
        return;
    }
    let mut hist = LatencyHistogram::new();
    for i in 0..N_RESOURCES_SMOKE {
        hist.record(std::time::Duration::from_millis((i as u64) * 10 + 50));
    }
    eprintln!("[{NFR_ID}] smoke p99={}ms", hist.p99());
    assert!(hist.len() == N_RESOURCES_SMOKE);
}
