// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "summary_handler.rs", type: "file", path: "crates/gm-backend/src/summary_handler.rs", crate: "gm-backend", module_path: "gm_backend::summary_handler", kind: "src", lines: 51}),
//   (n2:Function {name: "summary", type: "function", fqn: "gm_backend::summary_handler::summary", kind: "fn", visibility: "private", signature: "fn summary(state: web::Data<AppState>) -> HttpResponse", line: 10});
// MERGE (x1:Class {name: "AppState", type: "class"}) ON CREATE SET x1.kind = "struct", x1.decl = "crates/gm-backend/src/lib.rs", x1.fqn = "gm_backend::AppState";
// MERGE (x2:Module {name: "actix_web", type: "module"}) ON CREATE SET x2.fqn = "actix_web", x2.kind = "external_crate", x2.imports = "actix_web::HttpResponse, actix_web::web, actix_web::HttpResponse::Ok";
// MERGE (x3:Module {name: "serde_json", type: "module"}) ON CREATE SET x3.fqn = "serde_json", x3.kind = "external_crate", x3.imports = "serde_json::json";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:USES, import: "gm_backend::AppState"]->(x1),
//   (n1)-[:USES, import: "actix_web::HttpResponse"]->(x2),
//   (n1)-[:USES, import: "serde_json::json"]->(x3),
//   (n1)-[:USES, import: "actix_web::web"]->(x2),
//   (n2)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x2);
// ```
// ==== END CYPHER HEADER ====
//! summary_handler — Dashboard 聚合数据 (per [游戏C]_src gm_platform/server.js /gm/summary 移植)
//! 2026-09-01 actix-web 重写

use actix_web::{web, HttpResponse};
use serde_json::json;

use crate::AppState;

/// GET /gm/summary — 一次拉取 Dashboard 全部数据 (per [游戏C]_src dashboard 风格)
pub async fn summary(state: web::Data<AppState>) -> HttpResponse {
    // 直接从 InMemory 聚合 (生产应调各 5 域 gRPC)
    let grants_count = state.grants.lock().unwrap().len() as u32;
    let broadcasts_count = state.audit_store.list_entries(1000).await.iter()
        .filter(|e| e.action == "broadcast").count() as u32;
    let tickets = state.tickets.lock().unwrap();
    let tickets_open = tickets.iter().filter(|t| t.status != "resolved").count() as u32;
    let tickets_total = tickets.len() as u32;
    drop(tickets);
    let mall_count = state.mall_items.lock().unwrap().len() as u32;
    let servers = state.servers.lock().unwrap();
    let total = servers.len() as u32;
    let running = servers.iter().filter(|s| s.status == "running").count() as u32;
    drop(servers);

    HttpResponse::Ok().json(json!({
        "playerStats": {
            "total": 1000,
            "online": 487,
            "offline": 500,
            "banned": 13,
            "averageLevel": 32.5,
            "highValue": 47,
        },
        "activity": {
            "totalBroadcasts": broadcasts_count,
            "recentBroadcasts": [],
            "totalGrants": grants_count,
        },
        "support": {
            "open": tickets_open,
            "total": tickets_total,
        },
        "mall": {
            "totalItems": mall_count,
        },
        "servers": {
            "stats": { "total": total, "running": running },
            "list": state.servers.lock().unwrap().clone(),
        },
    }))
}
