// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "support_handler.rs", type: "file", path: "crates/gm-backend/src/support_handler.rs", crate: "gm-backend", module_path: "gm_backend::support_handler", kind: "src", lines: 82}),
//   (n2:Class {name: "TicketEntry", type: "class", fqn: "gm_backend::support_handler::TicketEntry", kind: "struct", visibility: "private", line: 12, attributes: "derive"}),
//   (n3:Class {name: "CreateTicketRequest", type: "class", fqn: "gm_backend::support_handler::CreateTicketRequest", kind: "struct", visibility: "private", line: 23, attributes: "derive"}),
//   (n4:Class {name: "UpdateTicketStatusRequest", type: "class", fqn: "gm_backend::support_handler::UpdateTicketStatusRequest", kind: "struct", visibility: "private", line: 29, attributes: "derive"}),
//   (n5:Function {name: "create_ticket", type: "function", fqn: "gm_backend::support_handler::create_ticket", kind: "fn", visibility: "private", signature: "fn create_ticket( state: web::Data<AppState>, req: HttpRequest, body: web::Json<CreateTicketRequest>, ) -> HttpResponse", line: 35}),
//   (n6:Function {name: "list_tickets", type: "function", fqn: "gm_backend::support_handler::list_tickets", kind: "fn", visibility: "private", signature: "fn list_tickets(state: web::Data<AppState>) -> HttpResponse", line: 59}),
//   (n7:Function {name: "update_ticket_status", type: "function", fqn: "gm_backend::support_handler::update_ticket_status", kind: "fn", visibility: "private", signature: "fn update_ticket_status( state: web::Data<AppState>, path: web::Path<u64>, body: web::Json<UpdateTicketStatusRequest>, ) -> HttpResponse", line: 64}),
//   (n8:Variable {name: "NEXT_TICKET_ID", type: "variable", fqn: "gm_backend::support_handler::NEXT_TICKET_ID", kind: "static", visibility: "private", line: 33});
// MERGE (x1:Class {name: "AppState", type: "class"}) ON CREATE SET x1.kind = "struct", x1.decl = "crates/gm-backend/src/lib.rs", x1.fqn = "gm_backend::AppState";
// MERGE (x2:Class {name: "Claims", type: "class"}) ON CREATE SET x2.kind = "struct", x2.decl = "crates/gm-backend/src/lib.rs", x2.fqn = "gm_backend::Claims";
// MERGE (x3:Module {name: "serde", type: "module"}) ON CREATE SET x3.fqn = "serde", x3.kind = "external_crate", x3.imports = "serde::Deserialize, serde::Serialize";
// MERGE (x4:Module {name: "actix_web", type: "module"}) ON CREATE SET x4.fqn = "actix_web", x4.kind = "external_crate", x4.imports = "actix_web::HttpRequest, actix_web::HttpResponse, actix_web::web, actix_web::HttpResponse::BadRequest, actix_web::HttpResponse::Ok, actix_web::HttpResponse::NotFound";
// MERGE (x5:Module {name: "chrono", type: "module"}) ON CREATE SET x5.fqn = "chrono", x5.kind = "external_crate", x5.imports = "chrono::Utc, chrono::Utc::now";
// MERGE (x6:Function {name: "extract_claims", type: "function"}) ON CREATE SET x6.kind = "fn", x6.decl = "crates/gm-backend/src/lib.rs", x6.fqn = "gm_backend::extract_claims";
// MERGE (x7:Module {name: "serde_json", type: "module"}) ON CREATE SET x7.fqn = "serde_json", x7.kind = "external_crate", x7.imports = "serde_json::json";
// MERGE (x8:Module {name: "gm_backend", type: "module"}) ON CREATE SET x8.fqn = "gm_backend", x8.kind = "external_crate", x8.imports = "gm_backend::extract_claims";
// MERGE (x9:Module {name: "core", type: "module"}) ON CREATE SET x9.fqn = "core", x9.kind = "external_crate", x9.imports = "core::option::Option";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n1)-[:CONTAINS]->(n6),
//   (n1)-[:CONTAINS]->(n7),
//   (n1)-[:CONTAINS]->(n8),
//   (n1)-[:USES, import: "gm_backend::AppState"]->(x1),
//   (n1)-[:USES, import: "gm_backend::Claims"]->(x2),
//   (n1)-[:USES, import: "serde::Deserialize"]->(x3),
//   (n1)-[:USES, import: "actix_web::HttpRequest"]->(x4),
//   (n1)-[:USES, import: "actix_web::HttpResponse"]->(x4),
//   (n1)-[:USES, import: "serde::Serialize"]->(x3),
//   (n1)-[:USES, import: "chrono::Utc"]->(x5),
//   (n1)-[:USES, import: "gm_backend::extract_claims"]->(x6),
//   (n1)-[:USES, import: "serde_json::json"]->(x7),
//   (n1)-[:USES, import: "actix_web::web"]->(x4),
//   (n5)-[:USES, via: "actix_web::HttpResponse::BadRequest"]->(x4),
//   (n5)-[:USES, via: "gm_backend::extract_claims"]->(x8),
//   (n5)-[:USES, via: "chrono::Utc::now"]->(x5),
//   (n5)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x4),
//   (n6)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x4),
//   (n7)-[:USES, via: "core::option::Option"]->(x9),
//   (n7)-[:USES, via: "actix_web::HttpResponse::NotFound"]->(x4),
//   (n7)-[:USES, via: "actix_web::HttpResponse::BadRequest"]->(x4),
//   (n7)-[:USES, via: "chrono::Utc::now"]->(x5),
//   (n7)-[:USES, via: "actix_web::HttpResponse::Ok"]->(x4);
// ```
// ==== END CYPHER HEADER ====
//! support_handler — 客服工单 (per [游戏C]_src gm_platform/modules/support 移植)
//! 2026-09-01 actix-web 重写

use actix_web::{web, HttpRequest, HttpResponse};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::{extract_claims, AppState, Claims};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketEntry {
    pub id: u64,
    pub player_id: String,
    pub message: String,
    pub admin: String,
    pub status: String, // "open" / "pending" / "resolved"
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Deserialize)]
pub struct CreateTicketRequest {
    pub player_id: String,
    pub message: String,
}

#[derive(Debug, Deserialize)]
pub struct UpdateTicketStatusRequest {
    pub status: String,
}

static NEXT_TICKET_ID: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(1);

pub async fn create_ticket(
    state: web::Data<AppState>,
    req: HttpRequest,
    body: web::Json<CreateTicketRequest>,
) -> HttpResponse {
    if body.player_id.trim().is_empty() || body.message.trim().is_empty() {
        return HttpResponse::BadRequest().json(json!({"error": "missing_fields"}));
    }
    let admin = extract_claims(&req).map(|c: Claims| c.sub).unwrap_or_else(|| "unknown".to_string());
    let id = NEXT_TICKET_ID.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let now = Utc::now().to_rfc3339();
    let ticket = TicketEntry {
        id,
        player_id: body.player_id.clone(),
        message: body.message.clone(),
        admin,
        status: "open".to_string(),
        created_at: now.clone(),
        updated_at: now,
    };
    state.tickets.lock().unwrap().push(ticket.clone());
    HttpResponse::Ok().json(json!({"status": "received", "ticket": ticket}))
}

pub async fn list_tickets(state: web::Data<AppState>) -> HttpResponse {
    let tickets = state.tickets.lock().unwrap();
    HttpResponse::Ok().json(json!({"tickets": tickets.clone()}))
}

pub async fn update_ticket_status(
    state: web::Data<AppState>,
    path: web::Path<u64>,
    body: web::Json<UpdateTicketStatusRequest>,
) -> HttpResponse {
    let id = path.into_inner();
    let mut tickets = state.tickets.lock().unwrap();
    let ticket = match tickets.iter_mut().find(|t| t.id == id) {
        Some(t) => t,
        None => return HttpResponse::NotFound().json(json!({"error": "not_found"})),
    };
    let allowed = ["open", "pending", "resolved"];
    if !allowed.contains(&body.status.as_str()) {
        return HttpResponse::BadRequest().json(json!({"error": "invalid_status", "allowed": allowed}));
    }
    ticket.status = body.status.clone();
    ticket.updated_at = Utc::now().to_rfc3339();
    HttpResponse::Ok().json(json!({"ticket": ticket.clone()}))
}
