// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "gm_handlers.rs", type: "file", path: "crates/admin-service/src/gm_handlers.rs", crate: "admin-service", module_path: "admin_service::gm_handlers", kind: "src", lines: 1170}),
//   (n2:Module {name: "tests", type: "module", fqn: "admin_service::gm_handlers::tests", kind: "inline"}),
//   (n3:Class {name: "GmHandlerState", type: "class", fqn: "admin_service::gm_handlers::GmHandlerState", kind: "struct", visibility: "private", line: 48, attributes: "derive"}),
//   (n4:Class {name: "JwtClaims", type: "class", fqn: "admin_service::gm_handlers::JwtClaims", kind: "struct", visibility: "private", line: 584, attributes: "derive"}),
//   (n5:Function {name: "new", type: "function", fqn: "admin_service::gm_handlers::GmHandlerState::new", kind: "method", visibility: "private", signature: "fn new( audit_log: Arc<dyn AuditLogRepository>, users: Arc<dyn AdminUserRepository>, ) -> Self", line: 59}),
//   (n6:Function {name: "with_coc_policy", type: "function", fqn: "admin_service::gm_handlers::GmHandlerState::with_coc_policy", kind: "method", visibility: "private", signature: "fn with_coc_policy(mut self, host: Arc<WasmHost>) -> Self", line: 72}),
//   (n7:Function {name: "coc_policy_decide_or_default_allow", type: "function", fqn: "admin_service::gm_handlers::coc_policy_decide_or_default_allow", kind: "fn", visibility: "private", signature: "fn coc_policy_decide_or_default_allow( actor_id: Uuid, action: &str, target_id: &str, amount: i64, target_blacklisted: bool, ) -> CocPolicyOutput", line: 82}),
//   (n8:Function {name: "init_state", type: "function", fqn: "admin_service::gm_handlers::init_state", kind: "fn", visibility: "private", signature: "fn init_state(state: GmHandlerState)", line: 145}),
//   (n9:Function {name: "state", type: "function", fqn: "admin_service::gm_handlers::state", kind: "fn", visibility: "private", signature: "fn state() -> &'static GmHandlerState", line: 149}),
//   (n10:Function {name: "ban_account", type: "function", fqn: "admin_service::gm_handlers::ban_account", kind: "fn", visibility: "private", signature: "fn ban_account( request: Request<BanAccountRequest>, ) -> Result<Response<BanAccountResponse>, Status>", line: 159}),
//   (n11:Function {name: "grant_compensation", type: "function", fqn: "admin_service::gm_handlers::grant_compensation", kind: "fn", visibility: "private", signature: "fn grant_compensation( request: Request<GrantCompensationRequest>, ) -> Result<Response<GrantCompensationResponse>, Status>", line: 282}),
//   (n12:Function {name: "set_maintenance", type: "function", fqn: "admin_service::gm_handlers::set_maintenance", kind: "fn", visibility: "private", signature: "fn set_maintenance( request: Request<SetMaintenanceRequest>, ) -> Result<Response<SetMaintenanceResponse>, Status>", line: 397}),
//   (n13:Function {name: "query_audit_log", type: "function", fqn: "admin_service::gm_handlers::query_audit_log", kind: "fn", visibility: "private", signature: "fn query_audit_log( request: Request<QueryAuditLogRequest>, ) -> Result<Response<QueryAuditLogResponse>, Status>", line: 514}),
//   (n14:Function {name: "in_memory_latest", type: "function", fqn: "admin_service::gm_handlers::in_memory_latest", kind: "fn", visibility: "private", signature: "fn in_memory_latest(limit: usize) -> Vec<DbAuditLogEntry>", line: 566}),
//   (n15:Function {name: "escape", type: "function", fqn: "admin_service::gm_handlers::escape", kind: "fn", visibility: "private", signature: "fn escape(s: &str) -> String", line: 574}),
//   (n16:Function {name: "action_target_domain", type: "function", fqn: "admin_service::gm_handlers::action_target_domain", kind: "fn", visibility: "private", signature: "fn action_target_domain(action: &str) -> &'static str", line: 595}),
//   (n17:Function {name: "require_coc_role", type: "function", fqn: "admin_service::gm_handlers::require_coc_role", kind: "fn", visibility: "private", signature: "fn require_coc_role(admin: &AdminUser, action: &str) -> Result<(), Error>", line: 613}),
//   (n18:Function {name: "extract_admin_user_from_jwt", type: "function", fqn: "admin_service::gm_handlers::extract_admin_user_from_jwt", kind: "fn", visibility: "private", signature: "fn extract_admin_user_from_jwt<T>( request: &Request<T>, ) -> Result<AdminUser, Status>", line: 634}),
//   (n19:Function {name: "extract_admin_id_from_jwt", type: "function", fqn: "admin_service::gm_handlers::extract_admin_id_from_jwt", kind: "fn", visibility: "private", signature: "fn extract_admin_id_from_jwt<T>(request: &Request<T>) -> String", line: 684, attributes: "allow"}),
//   (n20:Function {name: "admin", type: "function", fqn: "admin_service::gm_handlers::admin", kind: "fn", visibility: "private", signature: "fn admin(role: AdminRole, scope: Option<&str>) -> AdminUser", line: 724}),
//   (n21:Function {name: "rbac_super_admin_can_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_super_admin_can_ban_player", kind: "test", visibility: "private", signature: "fn rbac_super_admin_can_ban_player()", line: 732, attributes: "test"}),
//   (n22:Function {name: "rbac_super_admin_can_grant_economy", type: "function", fqn: "admin_service::gm_handlers::rbac_super_admin_can_grant_economy", kind: "test", visibility: "private", signature: "fn rbac_super_admin_can_grant_economy()", line: 737, attributes: "test"}),
//   (n23:Function {name: "rbac_super_admin_can_set_cluster_maintenance", type: "function", fqn: "admin_service::gm_handlers::rbac_super_admin_can_set_cluster_maintenance", kind: "test", visibility: "private", signature: "fn rbac_super_admin_can_set_cluster_maintenance()", line: 742, attributes: "test"}),
//   (n24:Function {name: "rbac_domain_admin_player_can_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_player_can_ban_player", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_player_can_ban_player()", line: 749, attributes: "test"}),
//   (n25:Function {name: "rbac_domain_admin_player_cannot_grant_economy", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_player_cannot_grant_economy", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_player_cannot_grant_economy()", line: 754, attributes: "test"}),
//   (n26:Function {name: "rbac_domain_admin_player_cannot_set_cluster_maintenance", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_player_cannot_set_cluster_maintenance", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_player_cannot_set_cluster_maintenance()", line: 760, attributes: "test"}),
//   (n27:Function {name: "rbac_domain_admin_economy_cannot_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_economy_cannot_ban_player", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_economy_cannot_ban_player()", line: 768, attributes: "test"}),
//   (n28:Function {name: "rbac_domain_admin_economy_can_grant_economy", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_economy_can_grant_economy", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_economy_can_grant_economy()", line: 774, attributes: "test"}),
//   (n29:Function {name: "rbac_domain_admin_economy_cannot_set_cluster_maintenance", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_economy_cannot_set_cluster_maintenance", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_economy_cannot_set_cluster_maintenance()", line: 779, attributes: "test"}),
//   (n30:Function {name: "rbac_domain_admin_cluster_cannot_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_cluster_cannot_ban_player", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_cluster_cannot_ban_player()", line: 787, attributes: "test"}),
//   (n31:Function {name: "rbac_domain_admin_cluster_cannot_grant_economy", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_cluster_cannot_grant_economy", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_cluster_cannot_grant_economy()", line: 793, attributes: "test"}),
//   (n32:Function {name: "rbac_domain_admin_cluster_can_set_cluster_maintenance", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_cluster_can_set_cluster_maintenance", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_cluster_can_set_cluster_maintenance()", line: 799, attributes: "test"}),
//   (n33:Function {name: "rbac_auditor_cannot_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_auditor_cannot_ban_player", kind: "test", visibility: "private", signature: "fn rbac_auditor_cannot_ban_player()", line: 806, attributes: "test"}),
//   (n34:Function {name: "rbac_auditor_cannot_grant_economy", type: "function", fqn: "admin_service::gm_handlers::rbac_auditor_cannot_grant_economy", kind: "test", visibility: "private", signature: "fn rbac_auditor_cannot_grant_economy()", line: 812, attributes: "test"}),
//   (n35:Function {name: "rbac_auditor_cannot_set_cluster_maintenance", type: "function", fqn: "admin_service::gm_handlers::rbac_auditor_cannot_set_cluster_maintenance", kind: "test", visibility: "private", signature: "fn rbac_auditor_cannot_set_cluster_maintenance()", line: 818, attributes: "test"}),
//   (n36:Function {name: "rbac_support_cannot_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_support_cannot_ban_player", kind: "test", visibility: "private", signature: "fn rbac_support_cannot_ban_player()", line: 826, attributes: "test"}),
//   (n37:Function {name: "rbac_support_cannot_grant_economy", type: "function", fqn: "admin_service::gm_handlers::rbac_support_cannot_grant_economy", kind: "test", visibility: "private", signature: "fn rbac_support_cannot_grant_economy()", line: 832, attributes: "test"}),
//   (n38:Function {name: "rbac_support_cannot_set_cluster_maintenance", type: "function", fqn: "admin_service::gm_handlers::rbac_support_cannot_set_cluster_maintenance", kind: "test", visibility: "private", signature: "fn rbac_support_cannot_set_cluster_maintenance()", line: 838, attributes: "test"}),
//   (n39:Function {name: "rbac_disabled_admin_returns_session_expired", type: "function", fqn: "admin_service::gm_handlers::rbac_disabled_admin_returns_session_expired", kind: "test", visibility: "private", signature: "fn rbac_disabled_admin_returns_session_expired()", line: 846, attributes: "test"}),
//   (n40:Function {name: "action_target_domain_mapping", type: "function", fqn: "admin_service::gm_handlers::action_target_domain_mapping", kind: "test", visibility: "private", signature: "fn action_target_domain_mapping()", line: 858, attributes: "test"}),
//   (n41:Function {name: "rbac_unknown_action_super_admin_passes_others_rejected", type: "function", fqn: "admin_service::gm_handlers::rbac_unknown_action_super_admin_passes_others_rejected", kind: "test", visibility: "private", signature: "fn rbac_unknown_action_super_admin_passes_others_rejected()", line: 875, attributes: "test"}),
//   (n42:Function {name: "rbac_super_admin_passes_all_eleven_actions", type: "function", fqn: "admin_service::gm_handlers::rbac_super_admin_passes_all_eleven_actions", kind: "test", visibility: "private", signature: "fn rbac_super_admin_passes_all_eleven_actions()", line: 906, attributes: "test"}),
//   (n43:Function {name: "rbac_domain_admin_match_can_kick_match", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_match_can_kick_match", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_match_can_kick_match()", line: 931, attributes: "test"}),
//   (n44:Function {name: "rbac_domain_admin_match_can_end_match", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_match_can_end_match", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_match_can_end_match()", line: 936, attributes: "test"}),
//   (n45:Function {name: "rbac_domain_admin_match_cannot_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_match_cannot_ban_player", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_match_cannot_ban_player()", line: 941, attributes: "test"}),
//   (n46:Function {name: "rbac_domain_admin_match_cannot_dissolve_guild", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_match_cannot_dissolve_guild", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_match_cannot_dissolve_guild()", line: 947, attributes: "test"}),
//   (n47:Function {name: "rbac_domain_admin_match_cannot_set_cluster_maintenance", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_match_cannot_set_cluster_maintenance", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_match_cannot_set_cluster_maintenance()", line: 953, attributes: "test"}),
//   (n48:Function {name: "rbac_domain_admin_social_can_dissolve_guild", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_social_can_dissolve_guild", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_social_can_dissolve_guild()", line: 961, attributes: "test"}),
//   (n49:Function {name: "rbac_domain_admin_social_can_promote_guild", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_social_can_promote_guild", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_social_can_promote_guild()", line: 966, attributes: "test"}),
//   (n50:Function {name: "rbac_domain_admin_social_cannot_ban_player", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_social_cannot_ban_player", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_social_cannot_ban_player()", line: 971, attributes: "test"}),
//   (n51:Function {name: "rbac_domain_admin_social_cannot_grant_economy", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_social_cannot_grant_economy", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_social_cannot_grant_economy()", line: 977, attributes: "test"}),
//   (n52:Function {name: "rbac_domain_admin_with_none_scope_rejects_all", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_with_none_scope_rejects_all", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_with_none_scope_rejects_all()", line: 985, attributes: "test"}),
//   (n53:Function {name: "rbac_domain_admin_with_empty_string_scope_rejects_all", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_with_empty_string_scope_rejects_all", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_with_empty_string_scope_rejects_all()", line: 1002, attributes: "test"}),
//   (n54:Function {name: "rbac_domain_admin_case_mismatch_rejected", type: "function", fqn: "admin_service::gm_handlers::rbac_domain_admin_case_mismatch_rejected", kind: "test", visibility: "private", signature: "fn rbac_domain_admin_case_mismatch_rejected()", line: 1019, attributes: "test"}),
//   (n55:Function {name: "rbac_auditor_with_domain_scope_still_rejected", type: "function", fqn: "admin_service::gm_handlers::rbac_auditor_with_domain_scope_still_rejected", kind: "test", visibility: "private", signature: "fn rbac_auditor_with_domain_scope_still_rejected()", line: 1029, attributes: "test"}),
//   (n56:Function {name: "rbac_support_with_domain_scope_still_rejected", type: "function", fqn: "admin_service::gm_handlers::rbac_support_with_domain_scope_still_rejected", kind: "test", visibility: "private", signature: "fn rbac_support_with_domain_scope_still_rejected()", line: 1035, attributes: "test"}),
//   (n57:Function {name: "rbac_action_target_domain_complete_coverage", type: "function", fqn: "admin_service::gm_handlers::rbac_action_target_domain_complete_coverage", kind: "test", visibility: "private", signature: "fn rbac_action_target_domain_complete_coverage()", line: 1043, attributes: "test"}),
//   (n58:Function {name: "rbac_session_expired_precedes_rbac_check", type: "function", fqn: "admin_service::gm_handlers::rbac_session_expired_precedes_rbac_check", kind: "test", visibility: "private", signature: "fn rbac_session_expired_precedes_rbac_check()", line: 1065, attributes: "test"}),
//   (n59:Function {name: "rbac_same_admin_multi_action_sequence_super_admin", type: "function", fqn: "admin_service::gm_handlers::rbac_same_admin_multi_action_sequence_super_admin", kind: "test", visibility: "private", signature: "fn rbac_same_admin_multi_action_sequence_super_admin()", line: 1081, attributes: "test"}),
//   (n60:Function {name: "rbac_same_admin_multi_action_sequence_domain_admin_player", type: "function", fqn: "admin_service::gm_handlers::rbac_same_admin_multi_action_sequence_domain_admin_player", kind: "test", visibility: "private", signature: "fn rbac_same_admin_multi_action_sequence_domain_admin_player()", line: 1090, attributes: "test"}),
//   (n61:Function {name: "rbac_disabled_domain_admin_session_expired_precedes_scope", type: "function", fqn: "admin_service::gm_handlers::rbac_disabled_domain_admin_session_expired_precedes_scope", kind: "test", visibility: "private", signature: "fn rbac_disabled_domain_admin_session_expired_precedes_scope()", line: 1108, attributes: "test"}),
//   (n62:Function {name: "test_gm_handler_state_new_coc_policy_none", type: "function", fqn: "admin_service::gm_handlers::test_gm_handler_state_new_coc_policy_none", kind: "test", visibility: "private", signature: "fn test_gm_handler_state_new_coc_policy_none()", line: 1129, attributes: "test"}),
//   (n63:Function {name: "test_gm_handler_state_with_coc_policy_some", type: "function", fqn: "admin_service::gm_handlers::test_gm_handler_state_with_coc_policy_some", kind: "test", visibility: "private", signature: "fn test_gm_handler_state_with_coc_policy_some()", line: 1141, attributes: "test"}),
//   (n64:Function {name: "test_coc_decision_serde_snake_case", type: "function", fqn: "admin_service::gm_handlers::test_coc_decision_serde_snake_case", kind: "test", visibility: "private", signature: "fn test_coc_decision_serde_snake_case()", line: 1154, attributes: "test"}),
//   (n65:Variable {name: "STATE", type: "variable", fqn: "admin_service::gm_handlers::STATE", kind: "static", visibility: "private", line: 142});
// MERGE (x1:Class {name: "AdminRole", type: "class"}) ON CREATE SET x1.kind = "enum", x1.decl = "crates/admin-service/src/entity.rs", x1.fqn = "admin_service::entity::AdminRole";
// MERGE (x2:Class {name: "AdminUser", type: "class"}) ON CREATE SET x2.kind = "struct", x2.decl = "crates/admin-service/src/entity.rs", x2.fqn = "admin_service::entity::AdminUser";
// MERGE (x3:Class {name: "AdminUserRepository", type: "class"}) ON CREATE SET x3.kind = "trait", x3.decl = "crates/admin-service/src/repository.rs", x3.fqn = "admin_service::repository::AdminUserRepository";
// MERGE (x4:Module {name: "std", type: "module"}) ON CREATE SET x4.fqn = "std", x4.kind = "external_crate", x4.imports = "std::sync::Arc, std::sync::OnceLock, std::sync::Arc::new, std::sync::Mutex::new, std::vec::Vec::new, std::string::String::new, std::env::var";
// MERGE (x5:Module {name: "admin_service", type: "module"}) ON CREATE SET x5.fqn = "admin_service", x5.kind = "external_crate", x5.imports = "admin_service::entity::AuditLogEntryasDbAuditLogEntry, admin_service::proto::v1::AuditLogEntryasProtoAuditLogEntry, admin_service::proto::v1::BanAccountRequest, admin_service::proto::v1::BanAccountResponse, admin_service::proto::v1::GrantCompensationRequest, admin_service::proto::v1::GrantCompensationResponse, admin_service::InMemoryAdminUserRepository, admin_service::InMemoryAuditLogRepository, admin_service::proto::v1::PropagationStatus, admin_service::proto::v1::QueryAuditLogRequest, admin_service::proto::v1::QueryAuditLogResponse, admin_service::proto::v1::SetMaintenanceRequest";
// MERGE (x6:Class {name: "AuditLogRepository", type: "class"}) ON CREATE SET x6.kind = "trait", x6.decl = "crates/admin-service/src/repository.rs", x6.fqn = "admin_service::repository::AuditLogRepository";
// MERGE (x7:Module {name: "function_plane", type: "module"}) ON CREATE SET x7.fqn = "function_plane", x7.kind = "external_crate", x7.imports = "function_plane::CocDecision, function_plane::CocPolicyInput, function_plane::CocPolicyOutput, function_plane::FunctionMetadata, function_plane::FunctionStatus, function_plane::Runtime, function_plane::TriggerType, function_plane::WasmHost";
// MERGE (x8:Module {name: "jsonwebtoken", type: "module"}) ON CREATE SET x8.fqn = "jsonwebtoken", x8.kind = "external_crate", x8.imports = "jsonwebtoken::DecodingKey, jsonwebtoken::Validation, jsonwebtoken::decode, jsonwebtoken::DecodingKey::from_secret";
// MERGE (x9:Module {name: "serde", type: "module"}) ON CREATE SET x9.fqn = "serde", x9.kind = "external_crate", x9.imports = "serde::Deserialize, serde::Serialize";
// MERGE (x10:Class {name: "Error", type: "class"}) ON CREATE SET x10.kind = "enum", x10.decl = "crates/admin-service/src/error.rs", x10.fqn = "admin_service::error::Error";
// MERGE (x11:Module {name: "tonic", type: "module"}) ON CREATE SET x11.fqn = "tonic", x11.kind = "external_crate", x11.imports = "tonic::Request, tonic::Response, tonic::Status, tonic::Status::permission_denied, tonic::Status::failed_precondition, tonic::Response::new, tonic::Status::unauthenticated, tonic::Status::internal";
// MERGE (x12:Module {name: "chrono", type: "module"}) ON CREATE SET x12.fqn = "chrono", x12.kind = "external_crate", x12.imports = "chrono::Utc, chrono::Utc::now";
// MERGE (x13:Module {name: "uuid", type: "module"}) ON CREATE SET x13.fqn = "uuid", x13.kind = "external_crate", x13.imports = "uuid::Uuid, uuid::Uuid::parse_str";
// MERGE (x14:Module {name: "core", type: "module"}) ON CREATE SET x14.fqn = "core", x14.kind = "external_crate", x14.imports = "core::option::Option, core::result::Result";
// MERGE (x15:Module {name: "serde_json", type: "module"}) ON CREATE SET x15.fqn = "serde_json", x15.kind = "external_crate", x15.imports = "serde_json, serde_json::to_string";
// MERGE (x16:Module {name: "tracing", type: "module"}) ON CREATE SET x16.fqn = "tracing", x16.kind = "external_crate", x16.imports = "tracing";
// MERGE (x17:Module {name: "DbAuditLogEntry", type: "module"}) ON CREATE SET x17.fqn = "DbAuditLogEntry", x17.kind = "external_crate", x17.imports = "DbAuditLogEntry::new";
// MERGE (x18:Function {name: "new", type: "function"}) ON CREATE SET x18.kind = "function", x18.decl = "crates/admin-service/src/entity.rs", x18.fqn = "admin_service::entity::AdminUser::new";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n3)-[:HAS_METHOD]->(n5),
//   (n3)-[:HAS_METHOD]->(n6),
//   (n1)-[:CONTAINS]->(n7),
//   (n1)-[:CONTAINS]->(n8),
//   (n1)-[:CONTAINS]->(n9),
//   (n1)-[:CONTAINS]->(n10),
//   (n1)-[:CONTAINS]->(n11),
//   (n1)-[:CONTAINS]->(n12),
//   (n1)-[:CONTAINS]->(n13),
//   (n1)-[:CONTAINS]->(n14),
//   (n1)-[:CONTAINS]->(n15),
//   (n1)-[:CONTAINS]->(n16),
//   (n1)-[:CONTAINS]->(n17),
//   (n1)-[:CONTAINS]->(n18),
//   (n1)-[:CONTAINS]->(n19),
//   (n1)-[:CONTAINS]->(n20),
//   (n1)-[:CONTAINS]->(n21),
//   (n1)-[:CONTAINS]->(n22),
//   (n1)-[:CONTAINS]->(n23),
//   (n1)-[:CONTAINS]->(n24),
//   (n1)-[:CONTAINS]->(n25),
//   (n1)-[:CONTAINS]->(n26),
//   (n1)-[:CONTAINS]->(n27),
//   (n1)-[:CONTAINS]->(n28),
//   (n1)-[:CONTAINS]->(n29),
//   (n1)-[:CONTAINS]->(n30),
//   (n1)-[:CONTAINS]->(n31),
//   (n1)-[:CONTAINS]->(n32),
//   (n1)-[:CONTAINS]->(n33),
//   (n1)-[:CONTAINS]->(n34),
//   (n1)-[:CONTAINS]->(n35),
//   (n1)-[:CONTAINS]->(n36),
//   (n1)-[:CONTAINS]->(n37),
//   (n1)-[:CONTAINS]->(n38),
//   (n1)-[:CONTAINS]->(n39),
//   (n1)-[:CONTAINS]->(n40),
//   (n1)-[:CONTAINS]->(n41),
//   (n1)-[:CONTAINS]->(n42),
//   (n1)-[:CONTAINS]->(n43),
//   (n1)-[:CONTAINS]->(n44),
//   (n1)-[:CONTAINS]->(n45),
//   (n1)-[:CONTAINS]->(n46),
//   (n1)-[:CONTAINS]->(n47),
//   (n1)-[:CONTAINS]->(n48),
//   (n1)-[:CONTAINS]->(n49),
//   (n1)-[:CONTAINS]->(n50),
//   (n1)-[:CONTAINS]->(n51),
//   (n1)-[:CONTAINS]->(n52),
//   (n1)-[:CONTAINS]->(n53),
//   (n1)-[:CONTAINS]->(n54),
//   (n1)-[:CONTAINS]->(n55),
//   (n1)-[:CONTAINS]->(n56),
//   (n1)-[:CONTAINS]->(n57),
//   (n1)-[:CONTAINS]->(n58),
//   (n1)-[:CONTAINS]->(n59),
//   (n1)-[:CONTAINS]->(n60),
//   (n1)-[:CONTAINS]->(n61),
//   (n1)-[:CONTAINS]->(n62),
//   (n1)-[:CONTAINS]->(n63),
//   (n1)-[:CONTAINS]->(n64),
//   (n1)-[:CONTAINS]->(n65),
//   (n2)-[:CONTAINS]->(n20),
//   (n2)-[:CONTAINS]->(n21),
//   (n2)-[:CONTAINS]->(n22),
//   (n2)-[:CONTAINS]->(n23),
//   (n2)-[:CONTAINS]->(n24),
//   (n2)-[:CONTAINS]->(n25),
//   (n2)-[:CONTAINS]->(n26),
//   (n2)-[:CONTAINS]->(n27),
//   (n2)-[:CONTAINS]->(n28),
//   (n2)-[:CONTAINS]->(n29),
//   (n2)-[:CONTAINS]->(n30),
//   (n2)-[:CONTAINS]->(n31),
//   (n2)-[:CONTAINS]->(n32),
//   (n2)-[:CONTAINS]->(n33),
//   (n2)-[:CONTAINS]->(n34),
//   (n2)-[:CONTAINS]->(n35),
//   (n2)-[:CONTAINS]->(n36),
//   (n2)-[:CONTAINS]->(n37),
//   (n2)-[:CONTAINS]->(n38),
//   (n2)-[:CONTAINS]->(n39),
//   (n2)-[:CONTAINS]->(n40),
//   (n2)-[:CONTAINS]->(n41),
//   (n2)-[:CONTAINS]->(n42),
//   (n2)-[:CONTAINS]->(n43),
//   (n2)-[:CONTAINS]->(n44),
//   (n2)-[:CONTAINS]->(n45),
//   (n2)-[:CONTAINS]->(n46),
//   (n2)-[:CONTAINS]->(n47),
//   (n2)-[:CONTAINS]->(n48),
//   (n2)-[:CONTAINS]->(n49),
//   (n2)-[:CONTAINS]->(n50),
//   (n2)-[:CONTAINS]->(n51),
//   (n2)-[:CONTAINS]->(n52),
//   (n2)-[:CONTAINS]->(n53),
//   (n2)-[:CONTAINS]->(n54),
//   (n2)-[:CONTAINS]->(n55),
//   (n2)-[:CONTAINS]->(n56),
//   (n2)-[:CONTAINS]->(n57),
//   (n2)-[:CONTAINS]->(n58),
//   (n2)-[:CONTAINS]->(n59),
//   (n2)-[:CONTAINS]->(n60),
//   (n2)-[:CONTAINS]->(n61),
//   (n2)-[:CONTAINS]->(n62),
//   (n2)-[:CONTAINS]->(n63),
//   (n2)-[:CONTAINS]->(n64),
//   (n1)-[:USES, import: "admin_service::entity::AdminRole"]->(x1),
//   (n1)-[:USES, import: "admin_service::entity::AdminUser"]->(x2),
//   (n1)-[:USES, import: "admin_service::repository::AdminUserRepository"]->(x3),
//   (n1)-[:USES, import: "std::sync::Arc"]->(x4),
//   (n1)-[:USES, import: "admin_service::entity::AuditLogEntryasDbAuditLogEntry"]->(x5),
//   (n1)-[:USES, import: "admin_service::proto::v1::AuditLogEntryasProtoAuditLogEntry"]->(x5),
//   (n1)-[:USES, import: "admin_service::repository::AuditLogRepository"]->(x6),
//   (n1)-[:USES, import: "admin_service::proto::v1::BanAccountRequest"]->(x5),
//   (n1)-[:USES, import: "admin_service::proto::v1::BanAccountResponse"]->(x5),
//   (n1)-[:USES, import: "function_plane::CocDecision"]->(x7),
//   (n1)-[:USES, import: "function_plane::CocPolicyInput"]->(x7),
//   (n1)-[:USES, import: "function_plane::CocPolicyOutput"]->(x7),
//   (n1)-[:USES, import: "jsonwebtoken::DecodingKey"]->(x8),
//   (n1)-[:USES, import: "serde::Deserialize"]->(x9),
//   (n1)-[:USES, import: "admin_service::error::Error"]->(x10),
//   (n1)-[:USES, import: "function_plane::FunctionMetadata"]->(x7),
//   (n1)-[:USES, import: "function_plane::FunctionStatus"]->(x7),
//   (n1)-[:USES, import: "admin_service::proto::v1::GrantCompensationRequest"]->(x5),
//   (n1)-[:USES, import: "admin_service::proto::v1::GrantCompensationResponse"]->(x5),
//   (n1)-[:USES, import: "admin_service::InMemoryAdminUserRepository"]->(x5),
//   (n1)-[:USES, import: "admin_service::InMemoryAuditLogRepository"]->(x5),
//   (n1)-[:USES, import: "std::sync::OnceLock"]->(x4),
//   (n1)-[:USES, import: "admin_service::proto::v1::PropagationStatus"]->(x5),
//   (n1)-[:USES, import: "admin_service::proto::v1::QueryAuditLogRequest"]->(x5),
//   (n1)-[:USES, import: "admin_service::proto::v1::QueryAuditLogResponse"]->(x5),
//   (n1)-[:USES, import: "tonic::Request"]->(x11),
//   (n1)-[:USES, import: "tonic::Response"]->(x11),
//   (n1)-[:USES, import: "function_plane::Runtime"]->(x7),
//   (n1)-[:USES, import: "serde::Serialize"]->(x9),
//   (n1)-[:USES, import: "admin_service::proto::v1::SetMaintenanceRequest"]->(x5),
//   (n1)-[:USES, import: "admin_service::proto::v1::SetMaintenanceResponse"]->(x5),
//   (n1)-[:USES, import: "tonic::Status"]->(x11),
//   (n1)-[:USES, import: "function_plane::TriggerType"]->(x7),
//   (n1)-[:USES, import: "chrono::Utc"]->(x12),
//   (n1)-[:USES, import: "uuid::Uuid"]->(x13),
//   (n1)-[:USES, import: "jsonwebtoken::Validation"]->(x8),
//   (n1)-[:USES, import: "function_plane::WasmHost"]->(x7),
//   (n1)-[:USES, import: "jsonwebtoken::decode"]->(x8),
//   (n5)-[:USES, via: "std::sync::Arc::new"]->(x4),
//   (n5)-[:USES, via: "std::sync::Mutex::new"]->(x4),
//   (n5)-[:USES, via: "std::vec::Vec::new"]->(x4),
//   (n6)-[:USES, via: "core::option::Option"]->(x14),
//   (n7)-[:USES, via: "core::option::Option"]->(x14),
//   (n7)-[:CALLS]->(n9),
//   (n7)-[:USES, via: "serde_json"]->(x15),
//   (n7)-[:USES, via: "std::string::String::new"]->(x4),
//   (n7)-[:USES, via: "function_plane::FunctionMetadata"]->(x7),
//   (n7)-[:USES, via: "tracing"]->(x16),
//   (n10)-[:CALLS]->(n18),
//   (n10)-[:CALLS]->(n17),
//   (n10)-[:USES, via: "chrono::Utc::now"]->(x12),
//   (n10)-[:CALLS]->(n7),
//   (n10)-[:USES, via: "DbAuditLogEntry::new"]->(x17),
//   (n10)-[:CALLS]->(n15),
//   (n10)-[:CALLS]->(n9),
//   (n10)-[:USES, via: "core::result::Result"]->(x14),
//   (n10)-[:USES, via: "tracing"]->(x16),
//   (n10)-[:USES, via: "tonic::Status::permission_denied"]->(x11),
//   (n10)-[:USES, via: "tonic::Status::failed_precondition"]->(x11),
//   (n10)-[:USES, via: "tonic::Response::new"]->(x11),
//   (n11)-[:CALLS]->(n18),
//   (n11)-[:CALLS]->(n17),
//   (n11)-[:USES, via: "chrono::Utc::now"]->(x12),
//   (n11)-[:CALLS]->(n7),
//   (n11)-[:USES, via: "DbAuditLogEntry::new"]->(x17),
//   (n11)-[:CALLS]->(n15),
//   (n11)-[:CALLS]->(n9),
//   (n11)-[:USES, via: "core::result::Result"]->(x14),
//   (n11)-[:USES, via: "tracing"]->(x16),
//   (n11)-[:USES, via: "tonic::Status::permission_denied"]->(x11),
//   (n11)-[:USES, via: "tonic::Status::failed_precondition"]->(x11),
//   (n11)-[:USES, via: "tonic::Response::new"]->(x11),
//   (n12)-[:CALLS]->(n18),
//   (n12)-[:CALLS]->(n17),
//   (n12)-[:USES, via: "chrono::Utc::now"]->(x12),
//   (n12)-[:CALLS]->(n7),
//   (n12)-[:USES, via: "DbAuditLogEntry::new"]->(x17),
//   (n12)-[:CALLS]->(n15),
//   (n12)-[:CALLS]->(n9),
//   (n12)-[:USES, via: "core::result::Result"]->(x14),
//   (n12)-[:USES, via: "tracing"]->(x16),
//   (n12)-[:USES, via: "tonic::Status::permission_denied"]->(x11),
//   (n12)-[:USES, via: "tonic::Status::failed_precondition"]->(x11),
//   (n12)-[:USES, via: "tonic::Response::new"]->(x11),
//   (n13)-[:CALLS]->(n9),
//   (n13)-[:USES, via: "core::result::Result"]->(x14),
//   (n13)-[:CALLS]->(n14),
//   (n13)-[:USES, via: "std::string::String::new"]->(x4),
//   (n13)-[:USES, via: "tonic::Response::new"]->(x11),
//   (n14)-[:CALLS]->(n9),
//   (n17)-[:USES, via: "core::result::Result"]->(x14),
//   (n17)-[:USES, via: "admin_service::error::Error"]->(x10),
//   (n17)-[:CALLS]->(n16),
//   (n18)-[:USES, via: "core::option::Option"]->(x14),
//   (n18)-[:USES, via: "core::result::Result"]->(x14),
//   (n18)-[:USES, via: "tonic::Status::unauthenticated"]->(x11),
//   (n18)-[:USES, via: "std::env::var"]->(x4),
//   (n18)-[:USES, via: "jsonwebtoken::DecodingKey::from_secret"]->(x8),
//   (n18)-[:USES, via: "uuid::Uuid::parse_str"]->(x13),
//   (n18)-[:CALLS]->(n9),
//   (n18)-[:USES, via: "tonic::Status::internal"]->(x11),
//   (n19)-[:USES, via: "core::option::Option"]->(x14),
//   (n19)-[:USES, via: "std::env::var"]->(x4),
//   (n19)-[:USES, via: "jsonwebtoken::DecodingKey::from_secret"]->(x8),
//   (n19)-[:USES, via: "core::result::Result"]->(x14),
//   (n20)-[:CALLS, via: "admin_service::entity::AdminUser::new"]->(x18),
//   (n21)-[:CALLS]->(n17),
//   (n22)-[:CALLS]->(n17),
//   (n23)-[:CALLS]->(n17),
//   (n24)-[:USES, via: "core::option::Option"]->(x14),
//   (n24)-[:CALLS]->(n17),
//   (n25)-[:USES, via: "core::option::Option"]->(x14),
//   (n25)-[:CALLS]->(n17),
//   (n26)-[:USES, via: "core::option::Option"]->(x14),
//   (n26)-[:CALLS]->(n17),
//   (n27)-[:USES, via: "core::option::Option"]->(x14),
//   (n27)-[:CALLS]->(n17),
//   (n28)-[:USES, via: "core::option::Option"]->(x14),
//   (n28)-[:CALLS]->(n17),
//   (n29)-[:USES, via: "core::option::Option"]->(x14),
//   (n29)-[:CALLS]->(n17),
//   (n30)-[:USES, via: "core::option::Option"]->(x14),
//   (n30)-[:CALLS]->(n17),
//   (n31)-[:USES, via: "core::option::Option"]->(x14),
//   (n31)-[:CALLS]->(n17),
//   (n32)-[:USES, via: "core::option::Option"]->(x14),
//   (n32)-[:CALLS]->(n17),
//   (n33)-[:CALLS]->(n17),
//   (n34)-[:CALLS]->(n17),
//   (n35)-[:CALLS]->(n17),
//   (n36)-[:CALLS]->(n17),
//   (n37)-[:CALLS]->(n17),
//   (n38)-[:CALLS]->(n17),
//   (n39)-[:USES, via: "core::option::Option"]->(x14),
//   (n39)-[:USES, via: "chrono::Utc::now"]->(x12),
//   (n39)-[:CALLS]->(n17),
//   (n39)-[:USES, via: "admin_service::error::Error"]->(x10),
//   (n40)-[:CALLS]->(n16),
//   (n41)-[:CALLS]->(n17),
//   (n42)-[:CALLS]->(n17),
//   (n43)-[:USES, via: "core::option::Option"]->(x14),
//   (n43)-[:CALLS]->(n17),
//   (n44)-[:USES, via: "core::option::Option"]->(x14),
//   (n44)-[:CALLS]->(n17),
//   (n45)-[:USES, via: "core::option::Option"]->(x14),
//   (n45)-[:CALLS]->(n17),
//   (n46)-[:USES, via: "core::option::Option"]->(x14),
//   (n46)-[:CALLS]->(n17),
//   (n47)-[:USES, via: "core::option::Option"]->(x14),
//   (n47)-[:CALLS]->(n17),
//   (n48)-[:USES, via: "core::option::Option"]->(x14),
//   (n48)-[:CALLS]->(n17),
//   (n49)-[:USES, via: "core::option::Option"]->(x14),
//   (n49)-[:CALLS]->(n17),
//   (n50)-[:USES, via: "core::option::Option"]->(x14),
//   (n50)-[:CALLS]->(n17),
//   (n51)-[:USES, via: "core::option::Option"]->(x14),
//   (n51)-[:CALLS]->(n17),
//   (n52)-[:CALLS]->(n17),
//   (n53)-[:USES, via: "core::option::Option"]->(x14),
//   (n53)-[:CALLS]->(n17),
//   (n54)-[:USES, via: "core::option::Option"]->(x14),
//   (n54)-[:CALLS]->(n17),
//   (n55)-[:USES, via: "core::option::Option"]->(x14),
//   (n55)-[:CALLS]->(n17),
//   (n56)-[:USES, via: "core::option::Option"]->(x14),
//   (n56)-[:CALLS]->(n17),
//   (n57)-[:CALLS]->(n16),
//   (n58)-[:CALLS]->(n17),
//   (n58)-[:USES, via: "core::option::Option"]->(x14),
//   (n58)-[:USES, via: "chrono::Utc::now"]->(x12),
//   (n58)-[:USES, via: "admin_service::error::Error"]->(x10),
//   (n59)-[:CALLS]->(n17),
//   (n60)-[:USES, via: "core::option::Option"]->(x14),
//   (n60)-[:CALLS]->(n17),
//   (n61)-[:USES, via: "core::option::Option"]->(x14),
//   (n61)-[:USES, via: "chrono::Utc::now"]->(x12),
//   (n61)-[:CALLS]->(n17),
//   (n61)-[:USES, via: "admin_service::error::Error"]->(x10),
//   (n62)-[:USES, via: "std::sync::Arc::new"]->(x4),
//   (n62)-[:USES, via: "admin_service::InMemoryAuditLogRepository"]->(x5),
//   (n62)-[:USES, via: "admin_service::InMemoryAdminUserRepository"]->(x5),
//   (n62)-[:CALLS, via: "admin_service::gm_handlers::GmHandlerState::new"]->(n5),
//   (n63)-[:USES, via: "std::sync::Arc::new"]->(x4),
//   (n63)-[:USES, via: "admin_service::InMemoryAuditLogRepository"]->(x5),
//   (n63)-[:USES, via: "admin_service::InMemoryAdminUserRepository"]->(x5),
//   (n63)-[:USES, via: "function_plane::WasmHost"]->(x7),
//   (n63)-[:CALLS, via: "admin_service::gm_handlers::GmHandlerState::new"]->(n5),
//   (n64)-[:USES, via: "serde_json::to_string"]->(x15);
// ```
// ==== END CYPHER HEADER ====
//! admin-service S4 Phase 2 step 2: 4 GM RPC handler
//!
//! 处理 gm-backend → admin-service 的 4 个 GM RPC:
//! - BanAccount (per RGS-BAS-003 §3.1)
//! - GrantCompensation (per RGS-BAS-003 §3.1)
//! - SetMaintenance (per RGS-BAS-003 §3.3 + DTL-003 §3.3 propagation_status)
//! - QueryAuditLog (per RGS-BAS-003 §3.4 + DTL-003 §3.4 entries[]+has_more)
//!
//! 关联: docs/00-基准与治理/RGS-S4-PHASE2-STEP1-设计.md
//!       docs/00-基准与治理/RGS-TBD-08-03-S4-gm-backend-admin-gRPC-立项.md
//!
//! 数据落地:
//! - BanAccount / GrantCompensation / SetMaintenance: 写 audit_log (per RGS-SEC-100 §7 hash 链)
//! - QueryAuditLog: 从 audit_log 读 (默认 limit=20, cursor pagination)
//!
//! 失败降级: handler 内部若 admin_db 不可达, 返 InMemory fallback (与 gm-backend InMemoryAuditStore 同模式)
//!
//! 实现: 用 `OnceCell<GmHandlerState>` 全局单例, 避免 tonic 0.12 State extractor 复杂。
//! 在 main.rs / lib.rs init 时调 `gm_handlers::init_state(...)` 注入。
//!
//! W17 (2026-08-28): JWT propagation - 从 gRPC metadata 抽 `authorization: Bearer <jwt>`,
//! 验签后用 claims.sub 作 admin_id 写 audit_log (per TBD-08-01 + RGS-BAS-003 §2.1 RBAC)

use chrono::Utc;
use jsonwebtoken::{decode, DecodingKey, Validation};
use serde::{Deserialize, Serialize};
use std::sync::{Arc, OnceLock};
use tonic::{Request, Response, Status};
use uuid::Uuid;

use crate::entity::{AdminUser, AuditLogEntry as DbAuditLogEntry};
use crate::error::Error;
use crate::proto::v1::{
    AuditLogEntry as ProtoAuditLogEntry, BanAccountRequest, BanAccountResponse,
    GrantCompensationRequest, GrantCompensationResponse, PropagationStatus, QueryAuditLogRequest,
    QueryAuditLogResponse, SetMaintenanceRequest, SetMaintenanceResponse,
};
use crate::repository::{AdminUserRepository, AuditLogRepository};
use function_plane::{
    CocDecision, CocPolicyInput, CocPolicyOutput, FunctionMetadata, FunctionStatus, Runtime,
    TriggerType, WasmHost,
};

/// 共享 handler 状态: AuditLogRepository (Pg 或 InMemory) + AdminUserRepository
/// (Q1 RBAC: 需根据 sub 查 admin, 校验 can_admin_domain) + InMemory fallback
/// + WasmHost (Phase B admin COC, per RGS-INC-001 v0.3 §X.1 集成点 file:line 3).
#[derive(Clone)]
pub struct GmHandlerState {
    pub audit_log: Arc<dyn AuditLogRepository>,
    pub users: Arc<dyn AdminUserRepository>,
    pub in_memory_fallback: Arc<std::sync::Mutex<Vec<DbAuditLogEntry>>>,
    /// Phase B admin COC (per RGS-INC-001 v0.3 §X.1):
    /// GM RPC 决策 WasmHost (CocPolicy decision 3 态). `None` 时 跳过决策
    /// (走原 Rust 路径, 等 WasmHost 启动加载 coc.policy module 后才有效).
    pub coc_policy: Option<Arc<WasmHost>>,
}

impl GmHandlerState {
    pub fn new(
        audit_log: Arc<dyn AuditLogRepository>,
        users: Arc<dyn AdminUserRepository>,
    ) -> Self {
        Self {
            audit_log,
            users,
            in_memory_fallback: Arc::new(std::sync::Mutex::new(Vec::new())),
            coc_policy: None,
        }
    }

    /// 注入 WasmHost (per RGS-INC-001 v0.3 §X.1 集成点 + main.rs 启动时).
    pub fn with_coc_policy(mut self, host: Arc<WasmHost>) -> Self {
        self.coc_policy = Some(host);
        self
    }
}

/// Phase B admin COC decision helper (per RGS-INC-001 v0.3 §X.1 + §X.2).
///
/// 调 WasmHost.invoke_coc_policy_sync (per input.action / target_id / amount / target_blacklisted).
/// WasmHost 不存在 / 决策失败时 fallback Allow (POC 简化, Phase 1+ 改 fail-closed).
fn coc_policy_decide_or_default_allow(
    actor_id: Uuid,
    action: &str,
    target_id: &str,
    amount: i64,
    target_blacklisted: bool,
) -> CocPolicyOutput {
    let Some(host) = state().coc_policy.clone() else {
        // WasmHost 未注入 (测试 / 启动早期): 走默认 Allow
        // Phase 1+ 改 fail-closed (per §X.6 护栏 3 WASM 决策不可落库 + 决策可重放)
        return CocPolicyOutput {
            decision: CocDecision::Allow,
            reason: "coc_policy_unavailable_default_allow_POC".to_string(),
            module_version: "unavailable".to_string(),
            module_hash: "0".repeat(64),
            params_hash: "0".repeat(64),
        };
    };

    let input = CocPolicyInput {
        actor_id,
        action: action.to_string(),
        target_id: target_id.to_string(),
        context: serde_json::json!({}),
        trace_id: String::new(), // TODO: 从 tonic metadata 抽 trace_id (per §3.3 透传)
        amount,
        target_blacklisted,
    };

    // FunctionMetadata v0 (per §X.1 WasmHost::invoke_coc_policy_sync 接口):
    // POC 阶段: 任意 FunctionMetadata, version "v0", module 字段不真加载
    // Phase 1+: 从 cluster_ops_db.function_registry 表读 metadata
    let meta = FunctionMetadata::new(
        "coc.policy",
        "v0",
        Runtime::Wasm,
        TriggerType::Grpc,
        None, // wasm_bytes: None 走 mock 决策 (per WasmHost::invoke_coc_policy_sync POC)
    );
    // P0 stage: status = Active so it looks ready (real gating comes from registry)
    let mut meta = meta;
    meta.status = FunctionStatus::Active;
    meta.fuel = 10_000_000;
    meta.memory_mib = 64;

    // WasmHost::invoke_coc_policy_sync 是 sync (per wasm_host.rs)
    host.invoke_coc_policy_sync(&meta, &input).unwrap_or_else(|e| {
        tracing::warn!(
            "admin-service coc_policy_decide WasmHost error: {e}, fallback Allow (POC)"
        );
        CocPolicyOutput {
            decision: CocDecision::Allow,
            reason: format!("coc_policy_error_fallback_allow: {e}"),
            module_version: "error".to_string(),
            module_hash: "0".repeat(64),
            params_hash: input.params_hash(),
        }
    })
}

static STATE: OnceLock<GmHandlerState> = OnceLock::new();

/// main.rs / lib.rs 启动时调一次, 注入 audit_log repository
pub fn init_state(state: GmHandlerState) {
    let _ = STATE.set(state);
}

fn state() -> &'static GmHandlerState {
    STATE
        .get()
        .expect("gm_handlers::init_state must be called before handling RPC")
}

// ============================================================================
// BanAccount
// ============================================================================

pub async fn ban_account(
    request: Request<BanAccountRequest>,
) -> Result<Response<BanAccountResponse>, Status> {
    // Q1 RBAC: handler 入口先校验 actor 有权执行 player.ban (per v0.2 §Q1)
    let admin = extract_admin_user_from_jwt(&request).await?;
    require_coc_role(&admin, "player.ban").map_err(Into::<tonic::Status>::into)?;

    let req = request.into_inner();
    let accepted_at_ms = Utc::now().timestamp_millis();
    let actor_id = admin.id;

    // Phase B admin COC WASM 决策 (per RGS-INC-001 v0.3 §X.1 集成点 file:line 3):
    // ban 操作 amount = 封禁时长 (秒, WAT i32 范围)
    let coc_output = coc_policy_decide_or_default_allow(
        actor_id,
        "player.ban",
        &req.account_id,
        req.duration_seconds as i64,
        false, // TODO: 从 admin-service 黑名单查询 (per §X.3 host_query_db 白名单)
    );
    // (line 88-91 重复定义 actor_id 在下面, 已删除; 保留 let actor_id = admin.id; 这一行)

    // Decision 路由 (per §X.2 3 态语义锁定):
    // - Deny: 写 audit_log decision=denied + 返 permission_denied
    // - RequireSecondReview: 写 audit_log (POC 简化) + 返 failed_precondition
    //   (Phase B #3+#4 worker 2 完成 second_review SQL migration 后, 改写 second_review 表)
    // - Allow: 继续走原 audit_log 路径
    if !matches!(coc_output.decision, CocDecision::Allow) {
        let decision_label = match coc_output.decision {
            CocDecision::Deny => "denied",
            CocDecision::RequireSecondReview => "require_second_review",
            CocDecision::Allow => unreachable!(),
        };
        let coc_audit_entry = DbAuditLogEntry::new(
            actor_id,
            format!("player.ban.coc_{decision_label}"),
            req.account_id.clone(),
            format!(
                "{{\"coc_decision\":\"{decision_label}\",\"coc_reason\":\"{}\",\"coc_module_version\":\"{}\",\"coc_module_hash\":\"{}\",\"coc_params_hash\":\"{}\",\"original_request_id\":\"{}\",\"original_duration_seconds\":{}}}",
                escape(&coc_output.reason),
                escape(&coc_output.module_version),
                escape(&coc_output.module_hash),
                escape(&coc_output.params_hash),
                escape(&req.request_id),
                req.duration_seconds
            ),
            // prev_hash 走现有链 (per §X.6 护栏 7 决策可重放 — audit_log 链不破)
            state()
                .audit_log
                .latest()
                .await
                .ok()
                .flatten()
                .map(|e| e.hash)
                .unwrap_or_else(|| "0".repeat(64)),
        );
        if let Err(e) = state().audit_log.append(&coc_audit_entry).await {
            tracing::warn!(
                "admin-service ban_account coc audit_log.append failed: {e}, fallback to InMemory"
            );
            if let Ok(mut guard) = state().in_memory_fallback.lock() {
                guard.push(coc_audit_entry);
            }
        }
        return match coc_output.decision {
            CocDecision::Deny => Err(Status::permission_denied(format!(
                "coc_decision=deny reason={}",
                coc_output.reason
            ))),
            CocDecision::RequireSecondReview => Err(Status::failed_precondition(format!(
                "coc_decision=require_second_review reason={} (pending SuperAdmin review)",
                coc_output.reason
            ))),
            CocDecision::Allow => unreachable!(),
        };
    }

    let actor_id = admin.id;
    let payload = format!(
        "{{\"request_id\":\"{}\",\"account_id\":\"{}\",\"reason\":\"{}\",\"duration_seconds\":{}}}",
        escape(&req.request_id),
        escape(&req.account_id),
        escape(&req.reason),
        req.duration_seconds
    );
    let prev_hash = state()
        .audit_log
        .latest()
        .await
        .ok()
        .flatten()
        .map(|e| e.hash)
        .unwrap_or_else(|| "0".repeat(64));
    let entry = DbAuditLogEntry::new(
        actor_id,
        "player.ban".to_string(),
        req.account_id.clone(),
        payload,
        prev_hash,
    );

    if let Err(e) = state().audit_log.append(&entry).await {
        tracing::warn!(
            "admin-service ban_account audit_log.append failed: {e}, fallback to InMemory"
        );
        if let Ok(mut guard) = state().in_memory_fallback.lock() {
            guard.push(entry);
        }
    }

    Ok(Response::new(BanAccountResponse {
        status: "queued".to_string(),
        op: "ban".to_string(),
        accepted_at_ms,
        // v0.4 (per RGS-DDD-CARD-9DEC-2026-08-29 DEC-038-07): 默认 false (未强制踢出对战)
        disconnected_sessions: false,
    }))
}

// ============================================================================
// GrantCompensation
// ============================================================================

pub async fn grant_compensation(
    request: Request<GrantCompensationRequest>,
) -> Result<Response<GrantCompensationResponse>, Status> {
    // Q1 RBAC: handler 入口先校验 actor 有权执行 economy.grant (per v0.2 §Q1)
    let admin = extract_admin_user_from_jwt(&request).await?;
    require_coc_role(&admin, "economy.grant").map_err(Into::<tonic::Status>::into)?;

    let req = request.into_inner();
    let accepted_at_ms = Utc::now().timestamp_millis();
    let actor_id = admin.id;

    // Phase B admin COC WASM 决策 (per RGS-INC-001 v0.3 §X.1 集成点 file:line 3):
    // grant 操作 amount = 货币金额 (i64)
    let coc_output = coc_policy_decide_or_default_allow(
        actor_id,
        "economy.grant",
        &req.account_id,
        req.amount as i64,
        false,
    );

    if !matches!(coc_output.decision, CocDecision::Allow) {
        let decision_label = match coc_output.decision {
            CocDecision::Deny => "denied",
            CocDecision::RequireSecondReview => "require_second_review",
            CocDecision::Allow => unreachable!(),
        };
        let coc_audit_entry = DbAuditLogEntry::new(
            actor_id,
            format!("economy.grant.coc_{decision_label}"),
            req.account_id.clone(),
            format!(
                "{{\"coc_decision\":\"{decision_label}\",\"coc_reason\":\"{}\",\"coc_module_version\":\"{}\",\"coc_module_hash\":\"{}\",\"coc_params_hash\":\"{}\",\"original_amount\":{}}}",
                escape(&coc_output.reason),
                escape(&coc_output.module_version),
                escape(&coc_output.module_hash),
                escape(&coc_output.params_hash),
                req.amount
            ),
            state()
                .audit_log
                .latest()
                .await
                .ok()
                .flatten()
                .map(|e| e.hash)
                .unwrap_or_else(|| "0".repeat(64)),
        );
        if let Err(e) = state().audit_log.append(&coc_audit_entry).await {
            tracing::warn!(
                "admin-service grant_compensation coc audit_log.append failed: {e}, fallback to InMemory"
            );
            if let Ok(mut guard) = state().in_memory_fallback.lock() {
                guard.push(coc_audit_entry);
            }
        }
        return match coc_output.decision {
            CocDecision::Deny => Err(Status::permission_denied(format!(
                "coc_decision=deny reason={}",
                coc_output.reason
            ))),
            CocDecision::RequireSecondReview => Err(Status::failed_precondition(format!(
                "coc_decision=require_second_review reason={} (pending SuperAdmin review)",
                coc_output.reason
            ))),
            CocDecision::Allow => unreachable!(),
        };
    }
    let payload = format!(
        "{{\"request_id\":\"{}\",\"account_id\":\"{}\",\"amount\":{},\"currency\":\"{}\",\"reason\":\"{}\"}}",
        escape(&req.request_id),
        escape(&req.account_id),
        req.amount,
        escape(&req.currency),
        escape(&req.reason)
    );
    let prev_hash = state()
        .audit_log
        .latest()
        .await
        .ok()
        .flatten()
        .map(|e| e.hash)
        .unwrap_or_else(|| "0".repeat(64));
    let entry = DbAuditLogEntry::new(
        actor_id,
        "economy.grant".to_string(),
        req.account_id.clone(),
        payload,
        prev_hash,
    );

    if let Err(e) = state().audit_log.append(&entry).await {
        tracing::warn!(
            "admin-service grant_compensation audit_log.append failed: {e}, fallback to InMemory"
        );
        if let Ok(mut guard) = state().in_memory_fallback.lock() {
            guard.push(entry);
        }
    }

    Ok(Response::new(GrantCompensationResponse {
        status: "queued".to_string(),
        op: "compensation".to_string(),
        accepted_at_ms,
        // v0.4 (per RGS-DDD-CARD-9DEC-2026-08-29 DEC-038-07): 默认 0 (未发卡牌/卡包)
        cards_granted: 0,
        packs_granted: 0,
    }))
}

// ============================================================================
// SetMaintenance
// ============================================================================

pub async fn set_maintenance(
    request: Request<SetMaintenanceRequest>,
) -> Result<Response<SetMaintenanceResponse>, Status> {
    // Q1 RBAC: handler 入口先校验 actor 有权执行 cluster.maintenance (per v0.2 §Q1)
    // cluster 域仅 SuperAdmin 有权 (per AdminUser::can_admin_domain: DomainAdmin
    // 只匹配 domain_scope=cluster, 但默认 GM 操作使用 SuperAdmin 路径).
    let admin = extract_admin_user_from_jwt(&request).await?;
    require_coc_role(&admin, "cluster.maintenance").map_err(Into::<tonic::Status>::into)?;

    let req = request.into_inner();
    let accepted_at_ms = Utc::now().timestamp_millis();
    let actor_id = admin.id;

    // Phase B admin COC WASM 决策 (per RGS-INC-001 v0.3 §X.1 集成点 file:line 3):
    // cluster.maintenance amount = ttl_seconds (i64)
    let coc_output = coc_policy_decide_or_default_allow(
        actor_id,
        "cluster.maintenance",
        &req.target_id,
        req.ttl_seconds as i64,
        false,
    );

    if !matches!(coc_output.decision, CocDecision::Allow) {
        let decision_label = match coc_output.decision {
            CocDecision::Deny => "denied",
            CocDecision::RequireSecondReview => "require_second_review",
            CocDecision::Allow => unreachable!(),
        };
        let coc_audit_entry = DbAuditLogEntry::new(
            actor_id,
            format!("cluster.maintenance.coc_{decision_label}"),
            req.target_id.clone(),
            format!(
                "{{\"coc_decision\":\"{decision_label}\",\"coc_reason\":\"{}\",\"coc_module_version\":\"{}\",\"coc_module_hash\":\"{}\",\"coc_params_hash\":\"{}\",\"original_ttl_seconds\":{}}}",
                escape(&coc_output.reason),
                escape(&coc_output.module_version),
                escape(&coc_output.module_hash),
                escape(&coc_output.params_hash),
                req.ttl_seconds
            ),
            state()
                .audit_log
                .latest()
                .await
                .ok()
                .flatten()
                .map(|e| e.hash)
                .unwrap_or_else(|| "0".repeat(64)),
        );
        if let Err(e) = state().audit_log.append(&coc_audit_entry).await {
            tracing::warn!(
                "admin-service set_maintenance coc audit_log.append failed: {e}, fallback to InMemory"
            );
            if let Ok(mut guard) = state().in_memory_fallback.lock() {
                guard.push(coc_audit_entry);
            }
        }
        return match coc_output.decision {
            CocDecision::Deny => Err(Status::permission_denied(format!(
                "coc_decision=deny reason={}",
                coc_output.reason
            ))),
            CocDecision::RequireSecondReview => Err(Status::failed_precondition(format!(
                "coc_decision=require_second_review reason={} (pending SuperAdmin review)",
                coc_output.reason
            ))),
            CocDecision::Allow => unreachable!(),
        };
    }
    let payload = format!(
        "{{\"request_id\":\"{}\",\"enable\":{},\"scope\":\"{}\",\"target_id\":\"{}\",\"ttl_seconds\":{}}}",
        escape(&req.request_id),
        req.enable,
        escape(&req.scope),
        escape(&req.target_id),
        req.ttl_seconds
    );
    let prev_hash = state()
        .audit_log
        .latest()
        .await
        .ok()
        .flatten()
        .map(|e| e.hash)
        .unwrap_or_else(|| "0".repeat(64));
    let entry = DbAuditLogEntry::new(
        actor_id,
        "cluster.maintenance".to_string(),
        req.target_id.clone(),
        payload,
        prev_hash,
    );

    if let Err(e) = state().audit_log.append(&entry).await {
        tracing::warn!(
            "admin-service set_maintenance audit_log.append failed: {e}, fallback to InMemory"
        );
        if let Ok(mut guard) = state().in_memory_fallback.lock() {
            guard.push(entry);
        }
    }

    Ok(Response::new(SetMaintenanceResponse {
        status: "queued".to_string(),
        op: "maintenance".to_string(),
        propagation_status: PropagationStatus::Converged as i32,
        accepted_at_ms,
        // v0.4 (per RGS-DDD-CARD-9DEC-2026-08-29 DEC-038-07): 默认 0 (无维护模式)
        applied_mode_flags: 0,
    }))
}

// ============================================================================
// QueryAuditLog
// ============================================================================

pub async fn query_audit_log(
    request: Request<QueryAuditLogRequest>,
) -> Result<Response<QueryAuditLogResponse>, Status> {
    let req = request.into_inner();
    let limit = if req.limit <= 0 {
        20
    } else {
        req.limit as usize
    };

    let entries: Vec<DbAuditLogEntry> = match state()
        .audit_log
        .list_latest(limit as i64 + 1)
        .await
    {
        Ok(v) => v,
        Err(_) => in_memory_latest(limit),
    };

    let has_more = entries.len() > limit;
    let entries_truncated: Vec<_> = entries.into_iter().take(limit).collect();
    let proto_entries: Vec<ProtoAuditLogEntry> = entries_truncated
        .iter()
        .map(|e| ProtoAuditLogEntry {
            log_id: e.id.to_string(),
            admin_id: e.actor_id.to_string(),
            action: e.action.clone(),
            target_id: e.target.clone(),
            occurred_at_ms: e.created_at.timestamp_millis(),
            // v0.4 (per RGS-DDD-CARD-9DEC-2026-08-29 DEC-038-07): 默认 All (本地 store 不分类)
            audit_type: crate::proto::v1::AuditType::All as i32,
        })
        .collect();

    let next_cursor = if has_more {
        entries_truncated
            .last()
            .map(|e| e.id.to_string())
            .unwrap_or_default()
    } else {
        String::new()
    };

    Ok(Response::new(QueryAuditLogResponse {
        entries: proto_entries,
        has_more,
        next_cursor,
        // v0.4 (per RGS-DDD-CARD-9DEC-2026-08-29 DEC-038-07): 默认 Unspecified (待 filter 解析)
        applied_audit_type: crate::proto::v1::AuditType::Unspecified as i32,
    }))
}

fn in_memory_latest(limit: usize) -> Vec<DbAuditLogEntry> {
    state()
        .in_memory_fallback
        .lock()
        .map(|g| g.iter().rev().take(limit).cloned().collect())
        .unwrap_or_default()
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

// ============================================================================
// W17 JWT propagation (per TBD-08-01 + RGS-BAS-003 §2.1 RBAC)
// ============================================================================

/// JWT claims (per gm-backend issue_jwt 格式)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct JwtClaims {
    pub sub: String,
    pub exp: usize,
    pub roles: Vec<String>,
}

/// Q1 RBAC: GM 指令 action → 目标域映射 (per RGS-ARC-051 §COC command namespace)
///
/// 与 `integration_gm_command_permission_chain.rs` IT 中既有定义保持一致 (per
/// v0.2 §Q1 "IT 为主, UT 补 role_matrix" 决策). handler 入口处按此映射做
/// can_admin_domain 校验.
pub fn action_target_domain(action: &str) -> &'static str {
    match action {
        "player.ban" | "player.unban" | "player.mute" | "player.promote" => "player",
        "economy.grant" | "economy.adjust" => "economy",
        "match.kick" | "match.end" => "match",
        "guild.dissolve" | "guild.promote" => "social",
        "cluster.maintenance" | "cluster.shutdown" => "cluster",
        _ => "unknown",
    }
}

/// Q1 RBAC 入口 helper: 校验 admin 是否有权执行指定 action.
///
/// 校验顺序 (per ARC-051 + RGS-SEC-100 §7):
/// 1. 启用状态 (`is_active`) → 不启用返 `AdminSessionExpired` (session 已失效)
/// 2. 域权限 (`can_admin_domain(target_domain(action))`) → 不足返 `COCRoleRequired`
///
/// 返回 `Result<(), Error>`: 调用方决定如何映射为 `tonic::Status`.
pub fn require_coc_role(admin: &AdminUser, action: &str) -> Result<(), Error> {
    if !admin.is_active() {
        return Err(Error::AdminSessionExpired(admin.username.clone()));
    }
    let required_domain = action_target_domain(action);
    if !admin.can_admin_domain(required_domain) {
        return Err(Error::COCRoleRequired {
            required: format!("role with '{}' scope", required_domain),
            actual: format!("{:?}", admin.role),
        });
    }
    Ok(())
}

/// Q1 RBAC: 从 gRPC metadata 抽 JWT, 验签后查 AdminUser 实体.
///
/// **fail-closed**: 任何一步失败 (无 metadata / 无 Bearer / JWT 验签失败 /
/// sub 非 UUID / admin 不存在) 均返 `Err(tonic::Status::unauthenticated(...))`,
/// 不降级到 "system" — 这是 Q1 关键修复点 (per v0.2 §Q1).
///
/// Returns `Result<AdminUser, tonic::Status>`.
pub async fn extract_admin_user_from_jwt<T>(
    request: &Request<T>,
) -> Result<AdminUser, Status> {
    let auth_value = request
        .metadata()
        .get("authorization")
        .and_then(|v| v.to_str().ok());

    let token = match auth_value {
        Some(s) if s.starts_with("Bearer ") => &s[7..],
        _ => {
            return Err(Status::unauthenticated(
                "missing or malformed authorization metadata",
            ));
        }
    };

    // JWT secret 简化: dev 环境固定 secret, prod 应从 ADMIN_JWT_SECRET env
    let secret = std::env::var("ADMIN_JWT_SECRET")
        .unwrap_or_else(|_| "dev-only-do-not-use-in-prod".to_string());

    let claims = match decode::<JwtClaims>(
        token,
        &DecodingKey::from_secret(secret.as_bytes()),
        &Validation::default(),
    ) {
        Ok(data) => data.claims,
        Err(e) => {
            return Err(Status::unauthenticated(format!("invalid jwt: {e}")));
        }
    };

    // sub 必须是 UUID (admin.id 类型约束)
    let admin_id = Uuid::parse_str(&claims.sub).map_err(|_| {
        Status::unauthenticated(format!("invalid sub in jwt: {}", claims.sub))
    })?;

    // 查 AdminUser; 不存在视为 unauthenticated
    let admin = state()
        .users
        .find_by_id(admin_id)
        .await
        .map_err(|e| Status::internal(format!("admin lookup failed: {e}")))?
        .ok_or_else(|| Status::unauthenticated(format!("admin {} not found", admin_id)))?;

    Ok(admin)
}

/// 兼容层: 保留旧签名以供未来调用; 但 Q1 改造后三个 handler 不再使用本函数.
#[allow(dead_code)]
fn extract_admin_id_from_jwt<T>(request: &Request<T>) -> String {
    // metadata "authorization" key
    let auth_value = request
        .metadata()
        .get("authorization")
        .and_then(|v| v.to_str().ok());

    let token = match auth_value {
        Some(s) if s.starts_with("Bearer ") => &s[7..],
        _ => return "system".to_string(),
    };

    // JWT secret 简化: dev 环境固定 secret, prod 应从 RGS_JWT_SECRET env
    let secret = std::env::var("ADMIN_JWT_SECRET")
        .unwrap_or_else(|_| "dev-only-do-not-use-in-prod".to_string());

    match decode::<JwtClaims>(
        token,
        &DecodingKey::from_secret(secret.as_bytes()),
        &Validation::default(),
    ) {
        Ok(data) => data.claims.sub,
        Err(_) => "system".to_string(),
    }
}

// ============================================================================
// UT 子代理 (2026-08-31 v3 P1 fix Q1): gm_handlers role_matrix
// 3 roles × 3 actions = 9 cases (per v0.2 §Q1 "UT 补 role_matrix" 决策)
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::AdminRole;
    use crate::error::Error;
    use crate::InMemoryAdminUserRepository;
    use crate::InMemoryAuditLogRepository;

    /// helper: 建启用 + 指定 role + scope 的 AdminUser
    fn admin(role: AdminRole, scope: Option<&str>) -> AdminUser {
        let mut u = AdminUser::new("u".to_string(), "h".to_string(), role);
        u.domain_scope = scope.map(|s| s.to_string());
        u
    }

    // --- SuperAdmin: 3 actions 全 ok (per ARC-051 COC) ---
    #[test]
    fn rbac_super_admin_can_ban_player() {
        let a = admin(AdminRole::SuperAdmin, None);
        assert!(require_coc_role(&a, "player.ban").is_ok());
    }
    #[test]
    fn rbac_super_admin_can_grant_economy() {
        let a = admin(AdminRole::SuperAdmin, None);
        assert!(require_coc_role(&a, "economy.grant").is_ok());
    }
    #[test]
    fn rbac_super_admin_can_set_cluster_maintenance() {
        let a = admin(AdminRole::SuperAdmin, None);
        assert!(require_coc_role(&a, "cluster.maintenance").is_ok());
    }

    // --- DomainAdmin(player): 仅 player.ban ok ---
    #[test]
    fn rbac_domain_admin_player_can_ban_player() {
        let a = admin(AdminRole::DomainAdmin, Some("player"));
        assert!(require_coc_role(&a, "player.ban").is_ok());
    }
    #[test]
    fn rbac_domain_admin_player_cannot_grant_economy() {
        let a = admin(AdminRole::DomainAdmin, Some("player"));
        let err = require_coc_role(&a, "economy.grant").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }), "got: {err:?}");
    }
    #[test]
    fn rbac_domain_admin_player_cannot_set_cluster_maintenance() {
        let a = admin(AdminRole::DomainAdmin, Some("player"));
        let err = require_coc_role(&a, "cluster.maintenance").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- DomainAdmin(economy): 仅 economy.grant ok ---
    #[test]
    fn rbac_domain_admin_economy_cannot_ban_player() {
        let a = admin(AdminRole::DomainAdmin, Some("economy"));
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_domain_admin_economy_can_grant_economy() {
        let a = admin(AdminRole::DomainAdmin, Some("economy"));
        assert!(require_coc_role(&a, "economy.grant").is_ok());
    }
    #[test]
    fn rbac_domain_admin_economy_cannot_set_cluster_maintenance() {
        let a = admin(AdminRole::DomainAdmin, Some("economy"));
        let err = require_coc_role(&a, "cluster.maintenance").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- DomainAdmin(cluster): 仅 cluster.maintenance ok ---
    #[test]
    fn rbac_domain_admin_cluster_cannot_ban_player() {
        let a = admin(AdminRole::DomainAdmin, Some("cluster"));
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_domain_admin_cluster_cannot_grant_economy() {
        let a = admin(AdminRole::DomainAdmin, Some("cluster"));
        let err = require_coc_role(&a, "economy.grant").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_domain_admin_cluster_can_set_cluster_maintenance() {
        let a = admin(AdminRole::DomainAdmin, Some("cluster"));
        assert!(require_coc_role(&a, "cluster.maintenance").is_ok());
    }

    // --- Auditor: 全部拒 (无域权限) ---
    #[test]
    fn rbac_auditor_cannot_ban_player() {
        let a = admin(AdminRole::Auditor, None);
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_auditor_cannot_grant_economy() {
        let a = admin(AdminRole::Auditor, None);
        let err = require_coc_role(&a, "economy.grant").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_auditor_cannot_set_cluster_maintenance() {
        let a = admin(AdminRole::Auditor, None);
        let err = require_coc_role(&a, "cluster.maintenance").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- Support: 全部拒 (无域权限) ---
    #[test]
    fn rbac_support_cannot_ban_player() {
        let a = admin(AdminRole::Support, None);
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_support_cannot_grant_economy() {
        let a = admin(AdminRole::Support, None);
        let err = require_coc_role(&a, "economy.grant").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_support_cannot_set_cluster_maintenance() {
        let a = admin(AdminRole::Support, None);
        let err = require_coc_role(&a, "cluster.maintenance").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- 已停用 admin: session expired 优先于 RBAC ---
    #[test]
    fn rbac_disabled_admin_returns_session_expired() {
        let mut a = admin(AdminRole::SuperAdmin, None);
        a.disabled_at = Some(Utc::now());
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(
            matches!(err, Error::AdminSessionExpired(_)),
            "已停用 SuperAdmin 应被 session expired 拒, got {err:?}"
        );
    }

    // --- action_target_domain 映射正确性 (per ARC-051 §COC) ---
    #[test]
    fn action_target_domain_mapping() {
        assert_eq!(action_target_domain("player.ban"), "player");
        assert_eq!(action_target_domain("player.unban"), "player");
        assert_eq!(action_target_domain("economy.grant"), "economy");
        assert_eq!(action_target_domain("economy.adjust"), "economy");
        assert_eq!(action_target_domain("match.kick"), "match");
        assert_eq!(action_target_domain("guild.dissolve"), "social");
        assert_eq!(action_target_domain("cluster.maintenance"), "cluster");
        assert_eq!(action_target_domain("unknown.action"), "unknown");
    }

    // --- 未知 action: SuperAdmin 因 can_admin_domain == true 一律 ok,
    //     其他角色因 "unknown" 不匹配 domain_scope 而被拒 ---
    // 注: 实际 handler 调用 require_coc_role 时传的是具体已知 action
    // (player.ban / economy.grant / cluster.maintenance), 不会出现 unknown;
    // 此测试仅锁定 action_target_domain 与 can_admin_domain 的交互语义.
    #[test]
    fn rbac_unknown_action_super_admin_passes_others_rejected() {
        // SuperAdmin: can_admin_domain = true → 通过 (per ARC-051 全域)
        let sa = admin(AdminRole::SuperAdmin, None);
        assert!(
            require_coc_role(&sa, "mystery.action").is_ok(),
            "SuperAdmin 对任何 action 应通过 (per ARC-051)"
        );
        // 其他角色: "unknown" 不匹配任何 domain_scope → COCRoleRequired
        for role in [
            AdminRole::DomainAdmin,
            AdminRole::Auditor,
            AdminRole::Support,
        ] {
            let a = admin(role, None);
            let err = require_coc_role(&a, "mystery.action").unwrap_err();
            assert!(matches!(err, Error::COCRoleRequired { .. }));
        }
    }

    // ============================================================================
    // UT 追加 (2026-09-01 WBS v0.2 桶 8 B1 增补): 完整 action × role 矩阵
    //
    // 覆盖 B1 brief "本次追加 role_matrix UT":
    // - 全部 11 action × 4 role 矩阵
    // - DomainAdmin("match") / DomainAdmin("social") 分支 (2d587f2 v0.2 未覆盖)
    // - DomainAdmin scope 边界 (None / Some("") / Some("cluster") 等)
    // - 跨 case-sensitivity / unknown 域 / 多 action 顺序
    // ============================================================================

    /// SuperAdmin: 全部 11 action 应通过 (per ARC-051 全域)
    #[test]
    fn rbac_super_admin_passes_all_eleven_actions() {
        let sa = admin(AdminRole::SuperAdmin, None);
        for action in [
            "player.ban",
            "player.unban",
            "player.mute",
            "player.promote",
            "economy.grant",
            "economy.adjust",
            "match.kick",
            "match.end",
            "guild.dissolve",
            "guild.promote",
            "cluster.maintenance",
            "cluster.shutdown",
        ] {
            assert!(
                require_coc_role(&sa, action).is_ok(),
                "SuperAdmin 应通过 {action}"
            );
        }
    }

    // --- DomainAdmin("match"): match.kick / match.end ok, 其它 reject ---
    #[test]
    fn rbac_domain_admin_match_can_kick_match() {
        let a = admin(AdminRole::DomainAdmin, Some("match"));
        assert!(require_coc_role(&a, "match.kick").is_ok());
    }
    #[test]
    fn rbac_domain_admin_match_can_end_match() {
        let a = admin(AdminRole::DomainAdmin, Some("match"));
        assert!(require_coc_role(&a, "match.end").is_ok());
    }
    #[test]
    fn rbac_domain_admin_match_cannot_ban_player() {
        let a = admin(AdminRole::DomainAdmin, Some("match"));
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_domain_admin_match_cannot_dissolve_guild() {
        let a = admin(AdminRole::DomainAdmin, Some("match"));
        let err = require_coc_role(&a, "guild.dissolve").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_domain_admin_match_cannot_set_cluster_maintenance() {
        let a = admin(AdminRole::DomainAdmin, Some("match"));
        let err = require_coc_role(&a, "cluster.maintenance").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- DomainAdmin("social"): guild.dissolve / guild.promote ok, 其它 reject ---
    #[test]
    fn rbac_domain_admin_social_can_dissolve_guild() {
        let a = admin(AdminRole::DomainAdmin, Some("social"));
        assert!(require_coc_role(&a, "guild.dissolve").is_ok());
    }
    #[test]
    fn rbac_domain_admin_social_can_promote_guild() {
        let a = admin(AdminRole::DomainAdmin, Some("social"));
        assert!(require_coc_role(&a, "guild.promote").is_ok());
    }
    #[test]
    fn rbac_domain_admin_social_cannot_ban_player() {
        let a = admin(AdminRole::DomainAdmin, Some("social"));
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_domain_admin_social_cannot_grant_economy() {
        let a = admin(AdminRole::DomainAdmin, Some("social"));
        let err = require_coc_role(&a, "economy.grant").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- DomainAdmin scope 边界: None / Some("") / 大小写不匹配 ---
    #[test]
    fn rbac_domain_admin_with_none_scope_rejects_all() {
        let a = admin(AdminRole::DomainAdmin, None);
        for action in [
            "player.ban",
            "economy.grant",
            "match.kick",
            "guild.dissolve",
            "cluster.maintenance",
        ] {
            let err = require_coc_role(&a, action).unwrap_err();
            assert!(
                matches!(err, Error::COCRoleRequired { .. }),
                "DomainAdmin scope=None 应拒绝 {action}, got {err:?}"
            );
        }
    }
    #[test]
    fn rbac_domain_admin_with_empty_string_scope_rejects_all() {
        let a = admin(AdminRole::DomainAdmin, Some(""));
        for action in [
            "player.ban",
            "economy.grant",
            "match.kick",
            "guild.dissolve",
            "cluster.maintenance",
        ] {
            let err = require_coc_role(&a, action).unwrap_err();
            assert!(
                matches!(err, Error::COCRoleRequired { .. }),
                "DomainAdmin scope=\"\" 应拒绝 {action}, got {err:?}"
            );
        }
    }
    #[test]
    fn rbac_domain_admin_case_mismatch_rejected() {
        // domain_scope="Player" (大写) vs action_target_domain 返回 "player" (小写)
        // Rust string 比较严格区分大小写, 因此不匹配 → reject
        let a = admin(AdminRole::DomainAdmin, Some("Player"));
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- Auditor/Support 即使配上 domain_scope 也不能操作 (per ARC-051) ---
    #[test]
    fn rbac_auditor_with_domain_scope_still_rejected() {
        let a = admin(AdminRole::Auditor, Some("player"));
        let err = require_coc_role(&a, "player.ban").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }
    #[test]
    fn rbac_support_with_domain_scope_still_rejected() {
        let a = admin(AdminRole::Support, Some("economy"));
        let err = require_coc_role(&a, "economy.grant").unwrap_err();
        assert!(matches!(err, Error::COCRoleRequired { .. }));
    }

    // --- action_target_domain 完整覆盖: 11 known + 1 unknown ---
    #[test]
    fn rbac_action_target_domain_complete_coverage() {
        // player
        assert_eq!(action_target_domain("player.ban"), "player");
        assert_eq!(action_target_domain("player.unban"), "player");
        assert_eq!(action_target_domain("player.mute"), "player");
        assert_eq!(action_target_domain("player.promote"), "player");
        // economy
        assert_eq!(action_target_domain("economy.grant"), "economy");
        assert_eq!(action_target_domain("economy.adjust"), "economy");
        // match
        assert_eq!(action_target_domain("match.kick"), "match");
        assert_eq!(action_target_domain("match.end"), "match");
        // social (guild.*)
        assert_eq!(action_target_domain("guild.dissolve"), "social");
        assert_eq!(action_target_domain("guild.promote"), "social");
        // cluster
        assert_eq!(action_target_domain("cluster.maintenance"), "cluster");
        assert_eq!(action_target_domain("cluster.shutdown"), "cluster");
    }

    // --- 顺序校验: session expired 优先于 RBAC, RBAC 优先于 admin 查不到 ---
    #[test]
    fn rbac_session_expired_precedes_rbac_check() {
        // 1. SuperAdmin 启用 → 任意 action 通过
        // 2. 同一 SuperAdmin disabled_at 设置 → 任意 action 返 AdminSessionExpired
        // (注意: session_expired 优先于 can_admin_domain 校验, per RGS-ARC-051)
        let mut sa = admin(AdminRole::SuperAdmin, None);
        assert!(require_coc_role(&sa, "player.ban").is_ok());
        sa.disabled_at = Some(Utc::now());
        let err = require_coc_role(&sa, "player.ban").unwrap_err();
        assert!(
            matches!(err, Error::AdminSessionExpired(_)),
            "disabled SuperAdmin 应返 AdminSessionExpired, got {err:?}"
        );
    }

    // --- 多 action 顺序: 同一 admin 连续跨 action 调用 ---
    #[test]
    fn rbac_same_admin_multi_action_sequence_super_admin() {
        let sa = admin(AdminRole::SuperAdmin, None);
        assert!(require_coc_role(&sa, "player.ban").is_ok());
        assert!(require_coc_role(&sa, "economy.grant").is_ok());
        assert!(require_coc_role(&sa, "match.kick").is_ok());
        assert!(require_coc_role(&sa, "guild.dissolve").is_ok());
        assert!(require_coc_role(&sa, "cluster.shutdown").is_ok());
    }
    #[test]
    fn rbac_same_admin_multi_action_sequence_domain_admin_player() {
        let da = admin(AdminRole::DomainAdmin, Some("player"));
        assert!(require_coc_role(&da, "player.ban").is_ok());
        assert!(require_coc_role(&da, "player.unban").is_ok());
        assert!(require_coc_role(&da, "player.mute").is_ok());
        // 跨域失败
        assert!(matches!(
            require_coc_role(&da, "economy.grant").unwrap_err(),
            Error::COCRoleRequired { .. }
        ));
        assert!(matches!(
            require_coc_role(&da, "cluster.maintenance").unwrap_err(),
            Error::COCRoleRequired { .. }
        ));
    }

    // --- Disabled DomainAdmin: session_expired 优先 ---
    #[test]
    fn rbac_disabled_domain_admin_session_expired_precedes_scope() {
        let mut da = admin(AdminRole::DomainAdmin, Some("player"));
        da.disabled_at = Some(Utc::now());
        // 即使 scope 匹配, 仍因 disabled 返 session expired (不是 COCRoleRequired)
        let err = require_coc_role(&da, "player.ban").unwrap_err();
        assert!(matches!(err, Error::AdminSessionExpired(_)));
    }

    // =========================================================================
    // Phase B admin COC 决策流 UT (per RGS-INC-001 v0.3 §X.1 + §X.2 + DDD Review §9 已知缺口 #10)
    //
    // 范围: 测 GmHandlerState coc_policy 字段初始化 (2 场景) + CocDecision 序列化 (1 场景).
    // 简化: 6 场景 RPC 集成测试 (3 RPC × RequireSecondReview / Deny) 需要 mock WasmHost + 完整 gRPC
    //       入口 + JWT, 标已知缺口后续 Phase 1+ 补 (DDD Review §9 已知缺口 #10 升级).
    //
    // 参考: crates/function-plane/tests/ut_coc_policy_wasm.rs (worker 1 写的 5/5 UT 覆盖 CocPolicy
    //        决策 schema 数据结构), 本测试覆盖 host 端 GmHandlerState 集成.
    // =========================================================================

    /// 1/9: GmHandlerState::new 默认 coc_policy = None (POC: 走 fallback Allow)
    #[test]
    fn test_gm_handler_state_new_coc_policy_none() {
        let audit = Arc::new(InMemoryAuditLogRepository::new()) as Arc<dyn AuditLogRepository>;
        let users = Arc::new(InMemoryAdminUserRepository::new()) as Arc<dyn AdminUserRepository>;
        let state = GmHandlerState::new(audit, users);
        assert!(
            state.coc_policy.is_none(),
            "GmHandlerState::new should set coc_policy = None (POC default)"
        );
    }

    /// 2/9: GmHandlerState::with_coc_policy 注入 WasmHost 后 Some(host)
    #[test]
    fn test_gm_handler_state_with_coc_policy_some() {
        let audit = Arc::new(InMemoryAuditLogRepository::new()) as Arc<dyn AuditLogRepository>;
        let users = Arc::new(InMemoryAdminUserRepository::new()) as Arc<dyn AdminUserRepository>;
        let host = WasmHost::new().expect("WasmHost::new should succeed");
        let state = GmHandlerState::new(audit, users).with_coc_policy(Arc::new(host));
        assert!(
            state.coc_policy.is_some(),
            "GmHandlerState::with_coc_policy should set coc_policy = Some(Arc<WasmHost>)"
        );
    }

    /// 3/9: CocDecision 序列化 (per RGS-INC-001 v0.3 §X.2 3 态 snake_case 编码)
    #[test]
    fn test_coc_decision_serde_snake_case() {
        let cases = [
            (CocDecision::Allow, "\"allow\""),
            (CocDecision::RequireSecondReview, "\"require_second_review\""),
            (CocDecision::Deny, "\"deny\""),
        ];
        for (decision, expected_json) in cases {
            let json = serde_json::to_string(&decision).expect("serialize");
            assert_eq!(
                json, expected_json,
                "CocDecision::{:?} should serialize to {}",
                decision, expected_json
            );
        }
    }
}

