// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "proto.rs", type: "file", path: "crates/match-service/src/proto.rs", crate: "match-service", module_path: "match_service::proto", kind: "src", lines: 10}),
//   (n2:Module {name: "v1", type: "module", fqn: "match_service::proto::v1", kind: "inline"});
// CREATE
//   (n1)-[:CONTAINS]->(n2);
// ```
// ==== END CYPHER HEADER ====
//! match-service proto 模块（per WBS v0.3 §2A.5 WF-1-54.3）
//!
//! W36 (2026-08-30): replay.proto 已移到 crate::replay::v1 (与 crate::common::v1 平级)

#![allow(clippy::all)]

/// match.v1 生成的 gRPC 类型（match 是 Rust 关键字，include_proto 用 r# 前缀）
pub mod v1 {
    tonic::include_proto!("r#match.v1");
}
