// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "it_replay_open_flow.rs", type: "file", path: "crates/replay-service/tests/it_replay_open_flow.rs", crate: "replay-service", module_path: "replay_service::test_target::it_replay_open_flow", kind: "test", lines: 75}),
//   (n2:Function {name: "make_svc", type: "function", fqn: "replay_service::test_target::it_replay_open_flow::make_svc", kind: "fn", visibility: "private", signature: "fn make_svc() -> (ReplayServiceImpl, Arc<InMemoryReplayRepository>, Arc<InMemoryBackend>)", line: 15}),
//   (n3:Function {name: "test_save_replay_idempotent_metadata", type: "function", fqn: "replay_service::test_target::it_replay_open_flow::test_save_replay_idempotent_metadata", kind: "test", visibility: "private", signature: "fn test_save_replay_idempotent_metadata()", line: 26, attributes: "tokio::test"}),
//   (n4:Function {name: "test_replay_after_card_open_pattern", type: "function", fqn: "replay_service::test_target::it_replay_open_flow::test_replay_after_card_open_pattern", kind: "test", visibility: "private", signature: "fn test_replay_after_card_open_pattern()", line: 40, attributes: "tokio::test"}),
//   (n5:Function {name: "test_chunk_size_clamp_to_min_max", type: "function", fqn: "replay_service::test_target::it_replay_open_flow::test_chunk_size_clamp_to_min_max", kind: "test", visibility: "private", signature: "fn test_chunk_size_clamp_to_min_max()", line: 64, attributes: "tokio::test"});
// MERGE (x1:Module {name: "std", type: "module"}) ON CREATE SET x1.fqn = "std", x1.kind = "external_crate", x1.imports = "std::sync::Arc, std::sync::Arc::new";
// MERGE (x2:Class {name: "InMemoryBackend", type: "class"}) ON CREATE SET x2.kind = "struct", x2.decl = "crates/replay-service/src/storage.rs", x2.fqn = "replay_service::storage::InMemoryBackend";
// MERGE (x3:Class {name: "InMemoryReplayRepository", type: "class"}) ON CREATE SET x3.kind = "struct", x3.decl = "crates/replay-service/src/repository.rs", x3.fqn = "replay_service::repository::InMemoryReplayRepository";
// MERGE (x4:Class {name: "PageRequest", type: "class"}) ON CREATE SET x4.kind = "struct", x4.decl = "crates/replay-service/src/repository.rs", x4.fqn = "replay_service::repository::PageRequest";
// MERGE (x5:Class {name: "Replay", type: "class"}) ON CREATE SET x5.kind = "struct", x5.decl = "crates/replay-service/src/entity.rs", x5.fqn = "replay_service::entity::Replay";
// MERGE (x6:Class {name: "ReplayDomainService", type: "class"}) ON CREATE SET x6.kind = "trait", x6.decl = "crates/replay-service/src/service.rs", x6.fqn = "replay_service::service::ReplayDomainService";
// MERGE (x7:Class {name: "ReplayFilter", type: "class"}) ON CREATE SET x7.kind = "struct", x7.decl = "crates/replay-service/src/entity.rs", x7.fqn = "replay_service::entity::ReplayFilter";
// MERGE (x8:Class {name: "ReplayMeta", type: "class"}) ON CREATE SET x8.kind = "struct", x8.decl = "crates/replay-service/src/entity.rs", x8.fqn = "replay_service::entity::ReplayMeta";
// MERGE (x9:Class {name: "ReplayMode", type: "class"}) ON CREATE SET x9.kind = "enum", x9.decl = "crates/replay-service/src/entity.rs", x9.fqn = "replay_service::entity::ReplayMode";
// MERGE (x10:Class {name: "ReplayRepository", type: "class"}) ON CREATE SET x10.kind = "trait", x10.decl = "crates/replay-service/src/repository.rs", x10.fqn = "replay_service::repository::ReplayRepository";
// MERGE (x11:Class {name: "ReplayServiceImpl", type: "class"}) ON CREATE SET x11.kind = "struct", x11.decl = "crates/replay-service/src/service.rs", x11.fqn = "replay_service::service::ReplayServiceImpl";
// MERGE (x12:Class {name: "StorageBackend", type: "class"}) ON CREATE SET x12.kind = "trait", x12.decl = "crates/replay-service/src/storage.rs", x12.fqn = "replay_service::storage::StorageBackend";
// MERGE (x13:Module {name: "uuid", type: "module"}) ON CREATE SET x13.fqn = "uuid", x13.kind = "external_crate", x13.imports = "uuid::Uuid, uuid::Uuid::new_v4";
// MERGE (x14:Function {name: "new", type: "function"}) ON CREATE SET x14.kind = "function", x14.decl = "crates/replay-service/src/repository.rs", x14.fqn = "replay_service::repository::InMemoryReplayRepository::new";
// MERGE (x15:Function {name: "new", type: "function"}) ON CREATE SET x15.kind = "function", x15.decl = "crates/replay-service/src/storage.rs", x15.fqn = "replay_service::storage::InMemoryBackend::new";
// MERGE (x16:Function {name: "new", type: "function"}) ON CREATE SET x16.kind = "function", x16.decl = "crates/replay-service/src/service.rs", x16.fqn = "replay_service::service::ReplayServiceImpl::new";
// MERGE (x17:Module {name: "core", type: "module"}) ON CREATE SET x17.fqn = "core", x17.kind = "external_crate", x17.imports = "core::option::Option";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n1)-[:USES, import: "std::sync::Arc"]->(x1),
//   (n1)-[:USES, import: "replay_service::storage::InMemoryBackend"]->(x2),
//   (n1)-[:USES, import: "replay_service::repository::InMemoryReplayRepository"]->(x3),
//   (n1)-[:USES, import: "replay_service::repository::PageRequest"]->(x4),
//   (n1)-[:USES, import: "replay_service::entity::Replay"]->(x5),
//   (n1)-[:USES, import: "replay_service::service::ReplayDomainService"]->(x6),
//   (n1)-[:USES, import: "replay_service::entity::ReplayFilter"]->(x7),
//   (n1)-[:USES, import: "replay_service::entity::ReplayMeta"]->(x8),
//   (n1)-[:USES, import: "replay_service::entity::ReplayMode"]->(x9),
//   (n1)-[:USES, import: "replay_service::repository::ReplayRepository"]->(x10),
//   (n1)-[:USES, import: "replay_service::service::ReplayServiceImpl"]->(x11),
//   (n1)-[:USES, import: "replay_service::storage::StorageBackend"]->(x12),
//   (n1)-[:USES, import: "uuid::Uuid"]->(x13),
//   (n2)-[:USES, via: "std::sync::Arc::new"]->(x1),
//   (n2)-[:CALLS, via: "replay_service::repository::InMemoryReplayRepository::new"]->(x14),
//   (n2)-[:CALLS, via: "replay_service::storage::InMemoryBackend::new"]->(x15),
//   (n2)-[:CALLS, via: "replay_service::service::ReplayServiceImpl::new"]->(x16),
//   (n3)-[:CALLS]->(n2),
//   (n3)-[:USES, via: "uuid::Uuid::new_v4"]->(x13),
//   (n4)-[:CALLS]->(n2),
//   (n4)-[:USES, via: "uuid::Uuid::new_v4"]->(x13),
//   (n4)-[:USES, via: "core::option::Option"]->(x17),
//   (n5)-[:CALLS]->(n2),
//   (n5)-[:USES, via: "uuid::Uuid::new_v4"]->(x13);
// ```
// ==== END CYPHER HEADER ====
//! replay-service 跨模块 IT 场景 (per PT-WORKER-BRIEFING §2)
//!
//! 3 IT 覆盖 (跨模块 = 业务链路 + 关联数据):
//! 1. test_save_replay_idempotent_metadata (save → save with same key, 幂等覆盖)
//! 2. test_replay_after_card_open_pattern (card OpenPack 完成后, replay 自动 save — mock 业务流)
//! 3. test_chunk_size_clamp_to_min_max (StreamReplay chunk_size 边界: 0 → DEFAULT, < MIN → MIN)

use std::sync::Arc;
use replay_service::entity::{Replay, ReplayFilter, ReplayMeta, ReplayMode};
use replay_service::repository::{InMemoryReplayRepository, PageRequest, ReplayRepository};
use replay_service::service::{ReplayDomainService, ReplayServiceImpl};
use replay_service::storage::{InMemoryBackend, StorageBackend};
use uuid::Uuid;

fn make_svc() -> (ReplayServiceImpl, Arc<InMemoryReplayRepository>, Arc<InMemoryBackend>) {
    let repo: Arc<InMemoryReplayRepository> = Arc::new(InMemoryReplayRepository::new());
    let storage: Arc<InMemoryBackend> = Arc::new(InMemoryBackend::new());
    let svc = ReplayServiceImpl::new(
        repo.clone() as Arc<dyn ReplayRepository>,
        storage.clone() as Arc<dyn StorageBackend>,
    );
    (svc, repo, storage)
}

#[tokio::test]
async fn test_save_replay_idempotent_metadata() {
    let (svc, _repo, storage) = make_svc();
    let mid = Uuid::new_v4();
    let m1 = svc.save_replay(mid, "p-a".into(), None, ReplayMode::Casual, vec![1u8, 2, 3], 60, 0, None).await.unwrap();
    // 同 match_id 二次 save (新 replay_id), 各自独立, 不冲突
    let m2 = svc.save_replay(mid, "p-a".into(), None, ReplayMode::Casual, vec![4u8, 5], 30, 0, None).await.unwrap();
    assert_ne!(m1.replay_id, m2.replay_id);
    assert_ne!(m1.object_key, m2.object_key);
    // 两个对象都存在 (幂等覆盖 = 同 key 时 in-memory 替换)
    assert!(storage.exists(&m1.object_key).await.unwrap());
    assert!(storage.exists(&m2.object_key).await.unwrap());
}

#[tokio::test]
async fn test_replay_after_card_open_pattern() {
    // 模拟跨模块: card-service OpenPack 完成后, 业务流应触发 replay-service save_replay
    // (match-service 集成待 W36+, 这里 mock 业务流, 验证 contract)
    let (svc, repo, _storage) = make_svc();
    let match_id = Uuid::new_v4();
    let owner = "player-a-uuid";
    // 模拟 card open pack 完成 (5 张卡 + 1 个 replay 元数据)
    let replay_meta = svc.save_replay(
        match_id, owner.to_string(), Some("player-b-uuid".into()),
        ReplayMode::Ranked, vec![0u8; 4096], 600, 0, Some("saga-card-open-1".into()),
    ).await.unwrap();
    assert_eq!(replay_meta.match_id, match_id);
    assert_eq!(replay_meta.object_size, 4096);
    // 元数据可查
    let found = repo.find_by_id(replay_meta.replay_id).await.unwrap();
    assert!(found.is_some());
    // 跨模式 list (mode=Ranked) 应查到
    let filter = ReplayFilter { mode_filter: Some(ReplayMode::Ranked), ..Default::default() };
    let (items, total, _) = svc.list_replays(&filter, PageRequest::default()).await.unwrap();
    assert_eq!(total, 1);
    assert_eq!(items[0].replay_id, replay_meta.replay_id);
}

#[tokio::test]
async fn test_chunk_size_clamp_to_min_max() {
    // 9/7 14:00 JST 调优: 测试缺少 save_replay 步骤, stream_replay 找不到 replay_id 报错
    let (svc, _repo, _storage) = make_svc();
    let match_id = Uuid::new_v4();
    let meta = svc
        .save_replay(match_id, "p".into(), None, ReplayMode::Casual, vec![0u8; 256], 60, 0, None)
        .await
        .unwrap();
    // chunk_size=0 → 用 DEFAULT, 仍然 OK
    let s = svc.stream_replay(meta.replay_id, 0, 0).await;
    assert!(s.is_ok(), "chunk_size=0 应该走 DEFAULT 不报错, 实际: {:?}", s.err());
}
