// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "aci_integration.rs", type: "file", path: "tools/rgs-flash-mock/tests/aci_integration.rs", crate: "rgs-flash-mock", module_path: "rgs_flash_mock::test_target::aci_integration", kind: "test", lines: 255}),
//   (n2:Function {name: "test_aci_schema_v0_1_roundtrip", type: "function", fqn: "rgs_flash_mock::test_target::aci_integration::test_aci_schema_v0_1_roundtrip", kind: "test", visibility: "private", signature: "fn test_aci_schema_v0_1_roundtrip()", line: 30, attributes: "test"}),
//   (n3:Function {name: "test_emit_smoke_assertion_v0_1", type: "function", fqn: "rgs_flash_mock::test_target::aci_integration::test_emit_smoke_assertion_v0_1", kind: "test", visibility: "private", signature: "fn test_emit_smoke_assertion_v0_1()", line: 100, attributes: "test"}),
//   (n4:Function {name: "test_aci_emitter_v0_1_compatibility", type: "function", fqn: "rgs_flash_mock::test_target::aci_integration::test_aci_emitter_v0_1_compatibility", kind: "test", visibility: "private", signature: "fn test_aci_emitter_v0_1_compatibility()", line: 168, attributes: "test"}),
//   (n5:Function {name: "locate_aci_json", type: "function", fqn: "rgs_flash_mock::test_target::aci_integration::locate_aci_json", kind: "fn", visibility: "private", signature: "fn locate_aci_json() -> PathBuf", line: 251});
// MERGE (x1:Module {name: "aci_emitter", type: "module"}) ON CREATE SET x1.fqn = "aci_emitter", x1.kind = "external_crate", x1.imports = "aci_emitter::AciEmitter, aci_emitter::ExpectActual, aci_emitter::ExpectValueType, aci_emitter::Layer, aci_emitter::Scope, aci_emitter::Severity, aci_emitter::Status, aci_emitter::AciEmitter::new, aci_emitter::Scope::new, aci_emitter::ExpectActual::new";
// MERGE (x2:Module {name: "std", type: "module"}) ON CREATE SET x2.fqn = "std", x2.kind = "external_crate", x2.imports = "std::path::PathBuf, std::fs, std::fs::read_to_string, std::path::PathBuf::from";
// MERGE (x3:Module {name: "aci_emitter_helper", type: "module"}) ON CREATE SET x3.kind = "module", x3.decl = "tools/rgs-flash-mock/src/aci_emitter_helper.rs", x3.fqn = "rgs_flash_mock::aci_emitter_helper";
// MERGE (x4:Module {name: "serde_json", type: "module"}) ON CREATE SET x4.fqn = "serde_json", x4.kind = "external_crate", x4.imports = "serde_json::from_str, serde_json, serde_json::to_string";
// MERGE (x5:Function {name: "emit_smoke_assertion", type: "function"}) ON CREATE SET x5.kind = "fn", x5.decl = "tools/rgs-flash-mock/src/aci_emitter_helper.rs", x5.fqn = "rgs_flash_mock::aci_emitter_helper::emit_smoke_assertion";
// MERGE (x6:Module {name: "core", type: "module"}) ON CREATE SET x6.fqn = "core", x6.kind = "external_crate", x6.imports = "core::option::Option";
// MERGE (x7:Function {name: "emit_smoke_assertion_json", type: "function"}) ON CREATE SET x7.kind = "fn", x7.decl = "tools/rgs-flash-mock/src/aci_emitter_helper.rs", x7.fqn = "rgs_flash_mock::aci_emitter_helper::emit_smoke_assertion_json";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n1)-[:USES, import: "aci_emitter::AciEmitter"]->(x1),
//   (n1)-[:USES, import: "aci_emitter::ExpectActual"]->(x1),
//   (n1)-[:USES, import: "aci_emitter::ExpectValueType"]->(x1),
//   (n1)-[:USES, import: "aci_emitter::Layer"]->(x1),
//   (n1)-[:USES, import: "std::path::PathBuf"]->(x2),
//   (n1)-[:USES, import: "aci_emitter::Scope"]->(x1),
//   (n1)-[:USES, import: "aci_emitter::Severity"]->(x1),
//   (n1)-[:USES, import: "aci_emitter::Status"]->(x1),
//   (n1)-[:USES, import: "rgs_flash_mock::aci_emitter_helper"]->(x3),
//   (n1)-[:USES, import: "std::fs"]->(x2),
//   (n2)-[:CALLS]->(n5),
//   (n2)-[:USES, via: "std::fs::read_to_string"]->(x2),
//   (n2)-[:USES, via: "serde_json::from_str"]->(x4),
//   (n3)-[:CALLS, via: "rgs_flash_mock::aci_emitter_helper::emit_smoke_assertion"]->(x5),
//   (n3)-[:USES, via: "core::option::Option"]->(x6),
//   (n3)-[:USES, via: "serde_json"]->(x4),
//   (n3)-[:USES, via: "aci_emitter::AciEmitter::new"]->(x1),
//   (n3)-[:USES, via: "serde_json::to_string"]->(x4),
//   (n3)-[:CALLS, via: "rgs_flash_mock::aci_emitter_helper::emit_smoke_assertion_json"]->(x7),
//   (n4)-[:USES, via: "aci_emitter::AciEmitter::new"]->(x1),
//   (n4)-[:USES, via: "aci_emitter::Scope::new"]->(x1),
//   (n4)-[:USES, via: "core::option::Option"]->(x6),
//   (n4)-[:USES, via: "aci_emitter::ExpectActual::new"]->(x1),
//   (n4)-[:USES, via: "serde_json"]->(x4),
//   (n5)-[:USES, via: "std::path::PathBuf::from"]->(x2);
// ```
// ==== END CYPHER HEADER ====
//! `aci_integration` — 3 IT (per ULYS-191 §4.3.1 brief v0.1)
//!
//! 与 IDE1.0 §4.2.2 IT-1/IT-2/IT-3 pattern 1:1 (per brief v0.1 §3.2 #19):
//!
//! | IT  | 名称                                       | 校验                                                                                 |
//! |-----|--------------------------------------------|--------------------------------------------------------------------------------------|
//! | IT-1 | `test_aci_schema_v0_1_roundtrip`            | `.aci.json` schema v0.1 与 aci-emitter 完全一致 (字段名 1:1)                         |
//! | IT-2 | `test_emit_smoke_assertion_v0_1`            | `emit_smoke_assertion()` 输出 assertion 含全部 10 必填字段 + 字段名 1:1 对齐         |
//! | IT-3 | `test_aci_emitter_v0_1_compatibility`       | RGS Rust emitter 字段名与 Star Python emitter 跨语言 parity (字段名 1:1)            |
//!
//! 守门 (per AGENTS.md §4):
//! - #13 W/T/M: 单元 (emit_smoke_assertion 单测) + 集成 (本文件 3 IT) + 系统 (aci-smoke.sh)
//! - #19v19 Python 化: IT-3 跨语言 parity 测

use std::fs;
use std::path::PathBuf;

use aci_emitter::{AciEmitter, ExpectActual, ExpectValueType, Layer, Scope, Severity, Status};
use rgs_flash_mock::aci_emitter_helper;

/// IT-1: `.aci.json` schema v0.1 与 aci-emitter 完全一致.
///
/// 校验项:
/// - 文件存在 (per ULYS-191 §4.3.1)
/// - `aci_version == "0.1.0-draft"` (与 aci-emitter::ACI_VERSION 同步)
/// - 17 个 `expect_value_types` 字段名与 Python emitter 1:1 对齐
/// - 6 个 `scope_dimensions` (project/module/domain/subdomain/operation/http_method)
/// - 10 个 `schema_required_fields` (assertion_id/aci_version/layer/scope/expect/actual/status/severity/reasoning/captured_at)
#[test]
fn test_aci_schema_v0_1_roundtrip() {
    // 1) 文件存在
    let schema_path = locate_aci_json();
    assert!(
        schema_path.exists(),
        ".aci.json not found at {}",
        schema_path.display()
    );
    let raw = fs::read_to_string(&schema_path).expect(".aci.json must be readable");
    let schema: serde_json::Value =
        serde_json::from_str(&raw).expect(".aci.json must be valid JSON");

    // 2) aci_version 字段
    let aci_version = schema["aci_version"]
        .as_str()
        .expect("schema.aci_version must be a string");
    assert_eq!(
        aci_version,
        aci_emitter::ACI_VERSION,
        "schema.aci_version must match aci-emitter::ACI_VERSION"
    );

    // 3) 17 个 expect_value_types
    let evts = schema["expect_value_types"]
        .as_array()
        .expect("schema.expect_value_types must be an array");
    assert_eq!(
        evts.len(),
        17,
        "schema.expect_value_types must have 17 entries (per §4.2 v0.1)"
    );

    // 4) 6 个 scope_dimensions
    let dims = schema["scope_dimensions"]
        .as_array()
        .expect("schema.scope_dimensions must be an array");
    assert_eq!(dims.len(), 6, "schema.scope_dimensions must have 6 entries");

    // 5) 10 个 schema_required_fields — 字段名 1:1 对齐
    let required = schema["schema_required_fields"]
        .as_array()
        .expect("schema.schema_required_fields must be an array");
    let required_set: std::collections::HashSet<&str> =
        required.iter().filter_map(|v| v.as_str()).collect();
    for field in &[
        "assertion_id",
        "aci_version",
        "layer",
        "scope",
        "expect",
        "actual",
        "status",
        "severity",
        "reasoning",
        "captured_at",
    ] {
        assert!(
            required_set.contains(field),
            "schema_required_fields must contain '{field}'"
        );
    }
}

/// IT-2: `emit_smoke_assertion()` 输出 assertion 含全部 10 必填字段 + 字段名 1:1 对齐。
///
/// 校验项:
/// - 10 必填字段全部存在且字段名与 schema_required_fields 1:1 对齐
/// - 默认值符合 §4.3.1 brief v0.1 (assertion_id="rgs-flash-mock:smoke:g-1" 等)
/// - JSON 序列化字段名 1:1 (与 Python emitter 跨语言可解析)
#[test]
fn test_emit_smoke_assertion_v0_1() {
    let assertion = aci_emitter_helper::emit_smoke_assertion();

    // 1) 10 必填字段非空
    assert_eq!(assertion.assertion_id, "rgs-flash-mock:smoke:g-1");
    assert_eq!(assertion.aci_version, "0.1.0-draft");
    assert_eq!(assertion.layer, Layer::It);
    assert_eq!(assertion.scope.project, "rgs-flash-mock");
    assert_eq!(assertion.scope.module.as_deref(), Some("smoke"));
    // expect/actual 是 ExpectActual, 后面单独验
    assert_eq!(assertion.status, Status::Pass);
    assert_eq!(assertion.severity, Severity::Info);
    assert!(
        !assertion.reasoning.is_empty(),
        "reasoning must be non-empty (per §4.3.1)"
    );
    assert!(
        !assertion.captured_at.is_empty(),
        "captured_at must be non-empty"
    );

    // 2) expect/actual 字段类型 + 值 (response_within_ms 2000/150)
    assert_eq!(
        assertion.expect.value_type,
        ExpectValueType::ResponseWithinMs
    );
    assert_eq!(assertion.expect.value, serde_json::json!(2000));
    assert_eq!(
        assertion.actual.value_type,
        ExpectValueType::ResponseWithinMs
    );
    assert_eq!(assertion.actual.value, serde_json::json!(150));

    // 3) JSON 序列化字段名 1:1 (与 Python emitter 跨语言可解析)
    let em = AciEmitter::new(Layer::It);
    let json_value = em.to_json(&assertion);
    let json_str = serde_json::to_string(&json_value).expect("assertion must serialize");
    for field in &[
        "assertion_id",
        "aci_version",
        "layer",
        "scope",
        "expect",
        "actual",
        "status",
        "severity",
        "reasoning",
        "captured_at",
    ] {
        assert!(
            json_str.contains(field),
            "serialized JSON must contain '{field}' (cross-language parity)"
        );
    }

    // 4) smoke helper 单独打印 JSON (供 aci-smoke.sh 抓 stdout)
    let pretty = aci_emitter_helper::emit_smoke_assertion_json();
    assert!(pretty.contains("rgs-flash-mock:smoke:g-1"));
    eprintln!("=== emit_smoke_assertion JSON ===\n{pretty}\n=== END ===");
}

/// IT-3: RGS Rust emitter 与 Star Python emitter 跨语言 parity (字段名 1:1)。
///
/// 校验项 (per §4.2 Python emitter + brief v0.1):
/// - 字段名 1:1 对齐 Python `_lib_aci_emit.py`
/// - ExpectActual 序列化字段名 = "type" / "value" / "description"
/// - Status / Severity / Layer 的字符串表示与 Python 一致 (PASS / Info / It)
#[test]
fn test_aci_emitter_v0_1_compatibility() {
    // 构造一条与 IDE1.0 §4.2.2 ide-cli smoke 1:1 的 assertion
    let em = AciEmitter::new(Layer::It);
    let assertion = em
        .build(
            "rgs-flash-mock:smoke:g-1".to_string(),
            Scope::new(
                "rgs-flash-mock".to_string(),
                Some("smoke".to_string()),
                None,
                None,
                None,
                None,
            ),
            ExpectActual::new(
                ExpectValueType::ResponseWithinMs,
                serde_json::json!(2000),
                "RGS API should respond within 2s",
            ),
            ExpectActual::new(
                ExpectValueType::ResponseWithinMs,
                serde_json::json!(150),
                "measured 150ms",
            ),
            Status::Pass,
            Severity::Info,
            "actual << expect (13x margin)",
        )
        .expect("cross-language parity assertion must build successfully");

    // 1) ExpectActual 序列化字段名 = type/value/description (Python emitter 约定)
    let json_value = em.to_json(&assertion);
    let expect_obj = json_value["expect"]
        .as_object()
        .expect("expect must be object");
    for key in &["type", "value", "description"] {
        assert!(
            expect_obj.contains_key(*key),
            "expect must have field '{key}' (Python emitter parity)"
        );
    }

    // 2) Status 序列化 = "PASS" (大写, 与 Python _lib_aci_emit.py 1:1)
    assert_eq!(
        json_value["status"].as_str(),
        Some("PASS"),
        "status must serialize to 'PASS' (Python emitter parity)"
    );

    // 3) Severity 序列化 = "info" (lowercase, Python emitter parity)
    assert_eq!(
        json_value["severity"].as_str(),
        Some("info"),
        "severity must serialize to 'info' (Python emitter parity)"
    );

    // 4) Layer 序列化 = "it" (lowercase, Python emitter parity)
    assert_eq!(
        json_value["layer"].as_str(),
        Some("it"),
        "layer must serialize to 'it' (Python emitter parity)"
    );

    // 5) Scope 字段名 1:1
    let scope_obj = json_value["scope"]
        .as_object()
        .expect("scope must be object");
    for key in &[
        "project",
        "module",
        "domain",
        "subdomain",
        "operation",
        "http_method",
    ] {
        assert!(
            scope_obj.contains_key(*key),
            "scope must have field '{key}' (Python emitter parity)"
        );
    }
}

/// Locate `.aci.json` relative to crate root (works for both `cargo test -p` and `cargo test --test`).
fn locate_aci_json() -> PathBuf {
    // CARGO_MANIFEST_DIR points to tools/rgs-flash-mock during cargo test
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir).join(".aci.json")
}
