// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "mtls_mock_phase_c.rs", type: "file", path: "crates/player-service/tests/mtls_mock_phase_c.rs", crate: "player-service", module_path: "player_service::test_target::mtls_mock_phase_c", kind: "test", lines: 115}),
//   (n2:Module {name: "tests", type: "module", fqn: "player_service::test_target::mtls_mock_phase_c::tests", kind: "inline"}),
//   (n3:Class {name: "MockCert", type: "class", fqn: "player_service::test_target::mtls_mock_phase_c::MockCert", kind: "struct", visibility: "private", line: 16, attributes: "derive"}),
//   (n4:Class {name: "MockPlayerMtlsClient", type: "class", fqn: "player_service::test_target::mtls_mock_phase_c::MockPlayerMtlsClient", kind: "struct", visibility: "private", line: 23}),
//   (n5:Class {name: "HandshakeState", type: "class", fqn: "player_service::test_target::mtls_mock_phase_c::HandshakeState", kind: "enum", visibility: "private", line: 30, attributes: "derive"}),
//   (n6:Function {name: "new", type: "function", fqn: "player_service::test_target::mtls_mock_phase_c::MockPlayerMtlsClient::new", kind: "method", visibility: "private", signature: "fn new(cert: MockCert) -> Self", line: 38}),
//   (n7:Function {name: "handshake", type: "function", fqn: "player_service::test_target::mtls_mock_phase_c::MockPlayerMtlsClient::handshake", kind: "method", visibility: "private", signature: "fn handshake(&self) -> Result<(), String>", line: 46}),
//   (n8:Function {name: "get_state", type: "function", fqn: "player_service::test_target::mtls_mock_phase_c::MockPlayerMtlsClient::get_state", kind: "method", visibility: "private", signature: "fn get_state(&self) -> HandshakeState", line: 73}),
//   (n9:Function {name: "player_cert", type: "function", fqn: "player_service::test_target::mtls_mock_phase_c::player_cert", kind: "fn", visibility: "private", signature: "fn player_cert() -> MockCert", line: 82}),
//   (n10:Function {name: "mtls_player_handshake_success", type: "function", fqn: "player_service::test_target::mtls_mock_phase_c::mtls_player_handshake_success", kind: "test", visibility: "private", signature: "fn mtls_player_handshake_success()", line: 93, attributes: "tokio::test"}),
//   (n11:Function {name: "mtls_player_handshake_invalid_fingerprint", type: "function", fqn: "player_service::test_target::mtls_mock_phase_c::mtls_player_handshake_invalid_fingerprint", kind: "test", visibility: "private", signature: "fn mtls_player_handshake_invalid_fingerprint()", line: 100, attributes: "tokio::test"}),
//   (n12:Function {name: "mtls_player_handshake_subject_mismatch", type: "function", fqn: "player_service::test_target::mtls_mock_phase_c::mtls_player_handshake_subject_mismatch", kind: "test", visibility: "private", signature: "fn mtls_player_handshake_subject_mismatch()", line: 108, attributes: "tokio::test"});
// MERGE (x1:Module {name: "std", type: "module"}) ON CREATE SET x1.fqn = "std", x1.kind = "external_crate", x1.imports = "std::sync::Arc, std::sync::Arc::new";
// MERGE (x2:Module {name: "tokio", type: "module"}) ON CREATE SET x2.fqn = "tokio", x2.kind = "external_crate", x2.imports = "tokio::sync::RwLock, tokio::sync::RwLock::new";
// MERGE (x3:Module {name: "core", type: "module"}) ON CREATE SET x3.fqn = "core", x3.kind = "external_crate", x3.imports = "core::result::Result";
// CREATE
//   (n1)-[:CONTAINS]->(n2),
//   (n1)-[:CONTAINS]->(n3),
//   (n1)-[:CONTAINS]->(n4),
//   (n1)-[:CONTAINS]->(n5),
//   (n4)-[:HAS_METHOD]->(n6),
//   (n4)-[:HAS_METHOD]->(n7),
//   (n4)-[:HAS_METHOD]->(n8),
//   (n1)-[:CONTAINS]->(n9),
//   (n1)-[:CONTAINS]->(n10),
//   (n1)-[:CONTAINS]->(n11),
//   (n1)-[:CONTAINS]->(n12),
//   (n2)-[:CONTAINS]->(n9),
//   (n2)-[:CONTAINS]->(n10),
//   (n2)-[:CONTAINS]->(n11),
//   (n2)-[:CONTAINS]->(n12),
//   (n1)-[:USES, import: "std::sync::Arc"]->(x1),
//   (n1)-[:USES, import: "tokio::sync::RwLock"]->(x2),
//   (n6)-[:USES, via: "std::sync::Arc::new"]->(x1),
//   (n6)-[:USES, via: "tokio::sync::RwLock::new"]->(x2),
//   (n7)-[:USES, via: "player_service::test_target::mtls_mock_phase_c::HandshakeState"]->(n5),
//   (n7)-[:USES, via: "core::result::Result"]->(x3),
//   (n10)-[:CALLS, via: "player_service::test_target::mtls_mock_phase_c::MockPlayerMtlsClient::new"]->(n6),
//   (n11)-[:CALLS, via: "player_service::test_target::mtls_mock_phase_c::MockPlayerMtlsClient::new"]->(n6),
//   (n12)-[:CALLS, via: "player_service::test_target::mtls_mock_phase_c::MockPlayerMtlsClient::new"]->(n6);
// ```
// ==== END CYPHER HEADER ====
// mTLS mock 单元测试 (per 9/3 12:36 JST 拍板 main-mtls-mock)
// 不依赖 k3s 真实 svc, 验证 player 域 mTLS client code + cert verification 逻辑
// 真跑需 SRE Lead 拍板触发阶段 B (cert 导出 + svc 真实 mTLS) 或走 9/3 mock 路径
// 编译期锚定 + 单元测试 mock, 跟 L-CAND-006 SOP cert fingerprint 比对一致
//
// Per 5 worker 派工新约束 L12 (commit 747b6d5):
//   - worker 不 commit, 报告即可
//   - per-worker CARGO_TARGET_DIR=target-r1-player
//   - 主会话统一 git add 5 files + 1 commit

use std::sync::Arc;
use tokio::sync::RwLock;

/// Mock cert metadata (per L-CAND-006 §1.2 MANIFEST.toml fingerprint 比对)
#[derive(Debug, Clone)]
struct MockCert {
    domain: String,
    fingerprint_sha256: String,
    subject: String,
}

/// Mock player 域 mTLS client (不依赖 k3s svc)
pub struct MockPlayerMtlsClient {
    cert: MockCert,
    /// Mock transport 状态: 模拟 5 域 mTLS handshake
    handshake_state: Arc<RwLock<HandshakeState>>,
}

#[derive(Debug, PartialEq, Clone)]
pub enum HandshakeState {
    Init,
    CertSent,
    Verified,
    Error(String),
}

impl MockPlayerMtlsClient {
    pub fn new(cert: MockCert) -> Self {
        Self {
            cert,
            handshake_state: Arc::new(RwLock::new(HandshakeState::Init)),
        }
    }

    /// Mock mTLS handshake: 验证 cert fingerprint
    pub async fn handshake(&self) -> Result<(), String> {
        // 1. 状态 Init → CertSent
        *self.handshake_state.write().await = HandshakeState::CertSent;
        // 2. 验证 cert fingerprint (per L-CAND-006 §1.4 fingerprint 比对)
        // SHA-256 fingerprint 格式 "AB:CD:..." 应该是 95 字符 (32 bytes * 3 - 1)
        if self.cert.fingerprint_sha256.len() != 95 {
            let err = format!(
                "invalid fingerprint length: {}",
                self.cert.fingerprint_sha256.len()
            );
            *self.handshake_state.write().await = HandshakeState::Error(err.clone());
            return Err(err);
        }
        // 3. 验证 subject (per cert subject "CN = player-service")
        if !self.cert.subject.contains("player-service") {
            let err = format!(
                "subject mismatch: expected player-service, got {}",
                self.cert.subject
            );
            *self.handshake_state.write().await = HandshakeState::Error(err.clone());
            return Err(err);
        }
        // 4. 验证通过
        *self.handshake_state.write().await = HandshakeState::Verified;
        Ok(())
    }

    pub async fn get_state(&self) -> HandshakeState {
        self.handshake_state.read().await.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn player_cert() -> MockCert {
        MockCert {
            domain: "player".to_string(),
            fingerprint_sha256:
                "11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11"
                    .to_string(),
            subject: "CN = player-service".to_string(),
        }
    }

    #[tokio::test]
    async fn mtls_player_handshake_success() {
        let client = MockPlayerMtlsClient::new(player_cert());
        assert!(client.handshake().await.is_ok());
        assert_eq!(client.get_state().await, HandshakeState::Verified);
    }

    #[tokio::test]
    async fn mtls_player_handshake_invalid_fingerprint() {
        let mut cert = player_cert();
        cert.fingerprint_sha256 = "short".to_string();
        let client = MockPlayerMtlsClient::new(cert);
        assert!(client.handshake().await.is_err());
    }

    #[tokio::test]
    async fn mtls_player_handshake_subject_mismatch() {
        let mut cert = player_cert();
        cert.subject = "CN = other-service".to_string();
        let client = MockPlayerMtlsClient::new(cert);
        let err = client.handshake().await.unwrap_err();
        assert!(err.contains("subject mismatch"));
    }
}
