// ==== BEGIN CYPHER HEADER (generated by tools/cypher-header-gen; do not edit) ====
// ```cypher
// CREATE
//   (n1:File {name: "proto.rs", type: "file", path: "crates/operate-service/src/proto.rs", crate: "operate-service", module_path: "operate_service::proto", kind: "src", lines: 5}),
//   (n2:Module {name: "v1", type: "module", fqn: "operate_service::proto::v1", kind: "inline"});
// CREATE
//   (n1)-[:CONTAINS]->(n2);
// ```
// ==== END CYPHER HEADER ====
#![allow(clippy::all)]

pub mod v1 {
    tonic::include_proto!("operate.v1");
}
